### ISSUE TITLE
Kodi 17.0-builds Non critical issues (not Nakamori related)

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#101]
[ ] Context menu is duplicated - as kodi default items are there
[x] "Refresh" of container to update status watch is broken in 17.a3

[x] FATAL: D:\bin\Kodi\addons\inputstream.mpd\inputstream.mpd.dll is a system dll and should never be released
[x] ERROR: CAddonCallbacksAddon - V1::KodiAPI::AddOn::CAddonCallbacksAddon::GetAddonSetting - can't find setting 'URL9' in 'InputStream SmoothStreamingMedia'
[x] FATAL: D:\bin\Kodi\addons\inputstream.smoothstream\inputstream.smoothstream.dll is a system dll and should never be released

[ ] WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
[ ] WARNING: XFILE::CDirectoryFactory::Create - unsupported protocol(androidapp) in androidapp://sources/apps/
[x] ERROR: XFILE::CDirectory::GetDirectory - Error getting
[x] ERROR: Could not encode thumbnail: special://masterprofile/Thumbnails/3/38ecaff0.jpg

Probably mine only problems, but will monitor them
Edit from da3dsoul: not just you, they are bugs with Kodi, some left over from Jarvis.

**Comment by bigretromike** [comment]
- [ ] 'refresh' don't work

**Comment by bigretromike** [comment]
kodi 17 now is more sensitive for windows and show them in different way (more linear)
redo the 'refresh' part.
Just need to test on 16.

**Comment by bigretromike** [comment]
Current master is 100% compatible with 17b3

**Comment by da3dsoul** [comment]
Well... It's as compatible as it can be with the stupid limitations of Krypton 'deprecating' many features between alpha and beta of a single release.

**Comment by bigretromike** [comment]
Beta4 and 7 days after Beta5. Time to test against it ;-)

**Comment by bigretromike** [comment]
```
21:16:34 T:1552   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for http://127.0.0.1:8111/jmmserverrest/getimage/1/2656
21:16:34 T:5712   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for http://127.0.0.1:8111/JMMServerREST/GetImage/7/2877
21:16:40 T:1272   ERROR: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/5/55325a14.jpg
21:16:40 T:5712   ERROR: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/6/6e608c49.jpg
21:16:41 T:1272   ERROR: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/6/63591b08.jpg
21:16:41 T:1552   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for http://127.0.0.1:8111/JMMServerREST/GetThumb/1/11639/1.7778
21:16:41 T:6520   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for http://127.0.0.1:8111/jmmserverrest/getimage/1/11639
21:16:42 T:5712   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for http://127.0.0.1:8111/JMMServerREST/GetThumb/1/10972/1.7778
21:16:42 T:1272   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for http://127.0.0.1:8111/jmmserverrest/getimage/1/10972
21:16:43 T:6520   ERROR: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/6/62f69b86.jpg
21:16:46 T:5712   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for http://127.0.0.1:8111/jmmserverrest/getimage/1/10972
21:16:46 T:1552   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for http://127.0.0.1:8111/JMMServerREST/GetThumb/1/10972/1.7778
```

Thats the only problem I have, the jmmserverrest error could be because of using jmm3.6.1.0 and missing assets there. I could assume that kodi try to "download" image and even if it fails he try to load them out of cache that did not get created because of not download image... that could be a thing

**Comment by bigretromike** [comment]
As Kodi hit 17 as stable, and we are fine with compatibility for long time now. I'm closing
