### ISSUE TITLE
Jumpy - aka Transcoding for Kodi

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#116]
Currently Jumpy (Transcoding via Universal Media Server) is supported via adding plugin.video.nakamori to force_resolve in gui settings of Jumpy.

This is ok, but not great.

**Comment by bigretromike** [comment]
There is no need to force_resolve but duration/fast-fowarding is missing

**Comment by bigretromike** [comment]
2.1.x still works the same; default jump + ums settings results in playing (streaming/transcoding) video to remote device but duration/fast-forward is still missing.

**Comment by bigretromike** [comment]
Order error was fix in this commit: https://github.com/bigretromike/nakamori/commit/cbb9c71e0ac6770b5844fb273c31121700188e19
Time for duration/fast-forward (I think its device-render.conf thing but last time I investigated it it could be also jumpy problem)

**Comment by da3dsoul** [comment]
I think the seeking may be fixed now.

**Comment by bigretromike** [comment]
Will gladly check this later today

**Comment by bigretromike** [comment]
I wasn't able to make it work on few renders.

**Comment by bigretromike** [comment]
Im checking with UpnPlay and VLC; 

Update: if I use UPnPlay with VLC as render I have 14sec seek bar and can work only with that range, it play fine but when i move seek bar it work within those first 14sec. Probably UMS-Render-Config thing and Jumpy not getting proper duration from Nakamori (probably - as changelog stand for that thing working)

**Comment by bigretromike** [comment]
upnplay+vlc give me a few sec (max 2minutes seekbar)
vlc (as it have network dlna client) gives mi bigger delay before start playing and same bare + vlc don't show titles with dot `.` at beginnig ;_;

upnplay also try to recognize lengh of video after playing it i see big numbers there like a conversion error. 24minuts is 24242:00:00 etc. 

As the player play long after hitting end of seekbar, the seek bar works only on his range.. sadly..

still.. no a big progress here

**Comment by bigretromike** [comment]
> *** setResolvedUrl ***
> raw : http://127.0.0.1:8112/videolocal/1/0/992/file.mkv
> name: You Jerks! And You Claim to Have Gintama?! (Part 2)
> type: 4
> url : http://127.0.0.1:8112/videolocal/1/0/992/file.mkv
> details : {'media': {'duration': '1418925:00', 'streams': [{'duration': 1419, 'width': u'640', 'videocodec': u'h264', 'type': 'video', 'height': u'480'}, {'audiochannels': 2, 'type': 'audio', 'audiolanguage': u'jpn', 'audiocodec': u'aac'}, {'subtitlelanguage': u'jpn', 'type': 'subtitle'}]}}
> data : {"ListItem": {"rating": 4.81, "year": 2006, "duration": 1418925, "size": 119702867, "plot": "Hidden due to user setting.\nCheck Show Plot for Unwatched Items in the Video Library Settings.", "votes": 21, "title": "You Jerks! And You Claim to Have Gintama?! (Part 2)", "tagline": "Meta Tags | ... | Fictional World", "iconimage": null, "label": "You Jerks! And You Claim to Have Gintama?! (Part 2)", "type": "Video", "tvshowtitle": "Gintama", "aired": "0", "season": 4, "label2": null, "sorttitle": "You Jerks! And You Claim to Have Gintama?! (Part 2)", "path": "http://127.0.0.1:8112/videolocal/1/0/992/file.mkv", "isplayable": "true", "episode": 2, "thumbnailimage": "0", "originaltitle": "You Jerks! And You Claim to Have Gintama?! (Part 2)", "streams": [{"duration": 1419, "width": "640", "videocodec": "h264", "type": "video", "height": "480"}, {"audiochannels": 2, "type": "audio", "audiolanguage": "jpn", "audiocodec": "aac"}, {"subtitlelanguage": "jpn", "type": "subtitle"}], "mpaa": "0"}}
> [jumpy] xbmc-urlresolver : http://127.0.0.1:8112/videolocal/1/0/992/file.mkv
> [jumpy] media: container: null, bitrate: 0, size: 0, video codec: null, duration: 23648:45:00.00, width: 0, height: 0, frame rate: null, mime type: null
> [jumpy] latest version is 0.3.10

Looks like duration is with :00 which make it minutes?

'duration': '1418925:00'  /60 = 23648,75  this is how long file upnplay show.

**Comment by bigretromike** [comment]
http://www.universalmediaserver.com/forum/viewtopic.php?f=6&t=288

Jumpy is no longer maintained for new UMS release. The King is Dead, Long live the King;

I will look for other solution.
