### ISSUE TITLE
Search PSN style

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#121]
That would be good thing for Jumpy/DLNA support without input.
Also would be useful to bypass 'ALL'

**Comment by bigretromike** [comment]
Need reconsider this as the "fuzzy" and "new search" is superior to this solution. 

For DLNA this would work fine

**Comment by da3dsoul** [comment]
I think what we have now is ideal. No point in making a pointlessly complex search when this works.

**Comment by bigretromike** [comment]
Its faster for non keyboard users to have psn way also but maybe jmm is not ready for it

**Comment by da3dsoul** [comment]
There are too many things to sort through. We would need to completely redesign the search system in Shoko with an index to make a PSN style search fast enough to be user friendly

**Comment by bigretromike** [comment]
Like you said. This is not needed in shoko then.

**Comment by da3dsoul** [comment]
I'll close this for now. If it becomes a thing later, we can look at it.

**Comment by bigretromike** [comment]
I could make this on kodi side;
Let me think about this, because this could speed up control with controllers and big collections.
I will add this (probably not the fast way) and if this wont be used much (or none) I will scrap this out.

**Comment by da3dsoul** [comment]
I can make an endpoint and return for a starts with search. Making the UI and input is on you, though. Since we can match multiple titles, it will return the title that is matching. The UI should display the that it matches, not the user's desired language selection.

**Comment by da3dsoul** [comment]
Right. It should also ignore gek... The Japanese word for movie

**Comment by bigretromike** [comment]
hmmm.. i was thinking more of query all so i would use same things as other filters, but if you are able to make `startwith` search that would be awesome ;-) the gui is on me

**Comment by da3dsoul** [comment]
https://github.com/japanesemediamanager/ShokoServer/commit/4c65ab647db8097bffc230b4e3bd69e27cbea322

**Comment by bigretromike** [comment]
`api/serie/startswith` >= 3.6.0.7

**Comment by bigretromike** [comment]
As they idea was really great, and with da3dsoul `api/serie/startswith` which is almost perfect for this, this will be closed till later (if needed) as Jumpy have been unmaintained because of internal UMS staff conflict with last plugin author; And Jumpy is broken with never UMS version (there is unofficial 0.3.10 version that works but until things get clear we wont invest time in deprecated code that could be wipe out from UMS in near feature).
