### ISSUE TITLE
Error during addGUIItem

### ISSUE THREAD

**Issue by ElementalCrisis** [bigretromike/nakamori#130]
Running JMM 3.6 with Nakamori 1.4.0 I'm getting the following error "Error during addGUIItem", it's not stopping me from using Nakamori but pops up every time I open Nakamori. 

[kodi.txt](https://github.com/bigretromike/nakamori/files/333523/kodi.txt)

**Comment by da3dsoul** [comment]
-Facepalm- that's my fault

**Comment by da3dsoul** [comment]
I'm playing Skyrim, so fixing it right now isn't happening. Change details['year'] to str(details['year']

**Comment by da3dsoul** [comment]
At line 128

**Comment by bigretromike** [comment]
2day, but commit is made
