### ISSUE TITLE
after long movie kodi crashed

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#131]

**Comment by da3dsoul** [comment]
Kodi 16.1? It's a thing that happens. It's fixed I'm 17

**Comment by bigretromike** [comment]
oh, didnt know. I just hit this now on 16.1 after watching 2h+ movie from nakamori im unsure of this happend more since I ususly dont watch so long series.

**Comment by bigretromike** [comment]
> 20:53:51 T:864   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
> 20:53:51 T:3640   ERROR: EXCEPTION: XBMC is not playing any media file
> 20:53:52 T:864 WARNING: RunScript called for a non-script addon 'plugin.video.nakamori'. This behaviour is deprecated.
> 20:53:54 T:1488   ERROR: EXCEPTION: access_violation
> 20:53:54 T:1488   ERROR: ---Error during buildTVSeasons---
> 20:53:54 T:1488   ERROR: <type 'exceptions.RuntimeError'> at line 481 in file nakamori.py : access_violation
> 20:53:54 T:1488   ERROR: EXCEPTION: access_violation
> 20:53:54 T:1488   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.RuntimeError'>
>                                             Error Contents: access_violation
>                                             Traceback (most recent call last):
>                                               File "C:\Users\x\AppData\Roaming\Kodi\addons\plugin.video.nakamori-1.4.0\nakamori.py", line 983, in <module>
>                                                 buildTVSeasons(parameters)
>                                               File "C:\Users\x\AppData\Roaming\Kodi\addons\plugin.video.nakamori-1.4.0\nakamori.py", line 601, in buildTVSeasons
>                                                 xbmcplugin.endOfDirectory(handle)
>                                             RuntimeError: access_violation
>                                             -->End of Python script error report<--
> 20:54:03 T:864  NOTICE: CJoystick::EnumJoysticksCallback : Enabled Joystick: BD Remote Control
> 20:54:03 T:864  NOTICE: CJoystick::EnumJoysticksCallback : Total Axis: 0 Total Hats: 0 Total Buttons: 0

That looks strange

**Comment by da3dsoul** [comment]
I've not had an issue in a while. It's possible it was our fault and fixed it by accident.

**Comment by bigretromike** [comment]
Did you watched long episodes (1h +) ? I haven't had time lately. But I think that last time we checked it was also related with things that were already remaked.

I will close it for now, as we are unable to hit this bug anytime soon.
