### ISSUE TITLE
Paginating results

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#134]
> Sure, you need to send the following in the query string X-Plex-Container-Size (The maximum number of items to retrieve), X-Plex-Container-Start the start offset,  MEdiaContainer TotalSize have the total number of objects MediaContainer.Offset the current offset, and MediaContainer.Size the current size asked.
> Also, i don't mind if you touch something else, not related to plex, like AnimeTitles and make it in your own way. if is more suitable, since currently plex do not care about Anime Titles(edited)
> off course those fields are not choosed by me 😛
> I just view last code, and in the refactor y erased the start (offset) part will re add.
> Example usage: http://192.168.1.8:8111/JMMServerKodi/GetFilters/1?X-Plex-Container-Size=2&X-Plex-Container-Start=4
> If the clients (Android phone, is the one parsing the json) then i'm all in to generate suitable formats. But if the client you speak is the Kodi Server.. Hmm........
> If you don't like the X-Plex-Container-Size names, you can actually do something about it, like passing the IProvider object to the Init Function in BaseObject.cs and define in IProvider, two properties like StartField and SizeField, and in KodiProvider.cs put your own names, and in PlexProvider.cs leave the originals.(edited)

This is option for big collection in Group 'ALL' not sure if ever needed but can be useful. Max provided those information so lets save them in safe place ;-)

**Comment by da3dsoul** [comment]
Make this an extension of the "Truncate" option. Probably, by default paginate by 26, so that the entire show is displayed normally.

**Comment by bigretromike** [comment]
paging is also for series lists :-) and 26 would be small. Im currently looking if Kodi support dynamic list building but its probably not so adding seperate item to go thru list like "next" "back" or just use it when list have more than X items in list. Also if the second option would be enabled then it would break "-continue-" button because it wouldn't be able to move on selected item if it was out of the current view

**Comment by bigretromike** [comment]
idea:
query series with level=1 (minimum information, fastest)
if size > user_input_setting
use pagination and disable continue (current)
that would drastically improve series like bleach/gintama/one piece

**Comment by bigretromike** [comment]
bleach works super fast in compare to legacy api and looking thru series in all with paginating would kill user experience.
