### ISSUE TITLE
Series Name Does Not Display Correctly

### ISSUE THREAD

**Issue by ElementalCrisis** [bigretromike/nakamori#137]
Using Nakamori 2.0.0 and JMM 3.6
![kodi_2016-07-19_05-18-50](https://cloud.githubusercontent.com/assets/9443295/16949575/6159068a-4d70-11e6-8062-436694e624ec.png)

**Comment by ElementalCrisis** [comment]
I fixed it, completely deleting Nakamori and reinstalling seemed to do the trick.

**Comment by bigretromike** [comment]
That strange O_o, only thing would be you install beta or alpha and never downloaded new one from repo, because all of them were 2.0.0

**Comment by da3dsoul** [comment]
-facepalm- were you still using the beta version I asked you to try

**Comment by da3dsoul** [comment]
That was probably it

**Comment by ElementalCrisis** [comment]
I had updated Nakamori after I read BRM's message but maybe that was the issue.
