### ISSUE TITLE
Fanart No Longer Used?

### ISSUE THREAD

**Issue by ElementalCrisis** [bigretromike/nakamori#138]
I've noticed that with Nakamori 2.0.0 fanart is no longer being used, It's just taking the AniDB series poster and stretching it to fit the container. 

Older Version:
![kodi_2016-03-15_03-47-30](https://cloud.githubusercontent.com/assets/9443295/16950088/3f4213cc-4d73-11e6-835a-8bc352462a99.png)

2.0.0
![kodi_2016-07-19_05-37-32](https://cloud.githubusercontent.com/assets/9443295/16950057/13aeab8a-4d73-11e6-92cf-7d5a33e83fa1.png)

Was this an actual change or is it a bug?

**Comment by da3dsoul** [comment]
I don't have this issue. Try with Jarvis.

**Comment by bigretromike** [comment]
Mostly fanart are used everywhere and just fit/croped like you see. That is a skin thing more than nakamori, but we can look into it more.

**Comment by ElementalCrisis** [comment]
Running 16.1 and also have this issue on the default skin as well. I just used Mimic to compare.

**Comment by da3dsoul** [comment]
Mhmm I dunno then

**Comment by da3dsoul** [comment]
These are definitely different

**Comment by da3dsoul** [comment]
[screenie](https://dl.dropboxusercontent.com/content_link/kBjVOjGp8gaoH8TWjmf0wEi0KQvmRVmxHepijuuqTzYODYIKFxqhOQsDqAlVphAs/file)

**Comment by bigretromike** [comment]
screenie error 403 ;-)

**Comment by da3dsoul** [comment]
There! Posting attachments from mobile is so much more difficult

**Comment by bigretromike** [comment]
@ElementalCrisis care to test with both JMM-Nancy (aka 3.7) and nakamori 2.1.0-nancy ?:-)
As 2.1.0 wont work on anything lower than 3.7(nancy)

**Comment by da3dsoul** [comment]
Really? After having me make everything backwards compatible, 2.1 isn't? `if 'jmmserverkodi' in key.lower():` isn't so hard, is it?

**Comment by bigretromike** [comment]
It use /jmmserverkodi/ like it did

On July 28, 2016 6:10:24 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>Really? After having me make everything backwards compatible, 2.1
>isn't? `if 'jmmserverkodi' in key.lower():` isn't so hard, is it?
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/138#issuecomment-235943763

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
I thought you were having it user API/ now. Or was that just a way of abbreviating jmmserverkodi and jmmserverplex etc

**Comment by da3dsoul** [comment]
Well does that version query still work?

**Comment by bigretromike** [comment]
I think so if i understand your sentence :-)

On July 28, 2016 7:03:50 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>Well does that version query still work?
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/138#issuecomment-235958888

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
I checked it once again with @ElementalCrisis its more of "what jmm server image send you now" most of the time its ok, sometimes you hit bad fanart from jmm
