### ISSUE TITLE
Nakamori 2.0.0 no longer shows Episodes, Specials

### ISSUE THREAD

**Issue by hidden4003** [bigretromike/nakamori#143]
When I go into the series instead of Episodes, Specials I see the series name repeated. JMM 3.5.0.2 nakamori 2.0.0
i.e. instead of
```
..
Episodes
Specials
```
i see
```
..
Series name
Series name
```

**Comment by bigretromike** [comment]
How do you enter that series you talk of ?

On July 29, 2016 12:58:06 AM GMT+02:00, hidden4003 <notifications@github.com> wrote:
>When I go into the series instead of Episodes, Specials I see the
>series name repeated. JMM 3.5.0.2 nakamori 2.0.0
>i.e. instead of
>```
>..
>Episodes
>Specials
>```
>i see
>```
>..
>Series name
>Series name
>```
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/143

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hidden4003** [comment]
Yes, id I enable mode with images then images are correct, they still show Episodes / Specials / Credits but the text below images says SeriesName / SeriesName.

It doesn't matter how I enter either through All > SeriesName > or through Continue Watching > SeriesName.

**Comment by bigretromike** [comment]
OK, will take A look after collection get reimport.
Also is that JMM3.6-beta or 3.5.0.2 you using?

**Comment by hidden4003** [comment]
JMM 3.5.0.2

**Comment by hidden4003** [comment]
Made some screenshots for you:
![screen1](https://cloud.githubusercontent.com/assets/197087/17239408/7f011570-556c-11e6-9cc4-13cd12fc5831.jpg)
![screen2](https://cloud.githubusercontent.com/assets/197087/17239410/844d18b2-556c-11e6-87c2-54ddcb732434.jpg)

**Comment by bigretromike** [comment]
Professional issue commit is professional! 
Fixing, will push update on repo so it will auto-update.

**Comment by bigretromike** [comment]
Give me a minute to push 2.0.1 onto repo
