### ISSUE TITLE
Play without changing status of watched

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#146]
Could be a option to make it not check watched because ... maybe ? because you skiped to end of it to check if you watched - and it trigger % check. 

Need vote

**Comment by da3dsoul** [comment]
It already has the option? watched_mark

**Comment by bigretromike** [comment]
Im talking about context menu option, not settings

**Comment by da3dsoul** [comment]
Wouldn't be too hard.

**Comment by bigretromike** [comment]
It was hard ;-)
But I made it ! :-p
Seen in 2.0.7
