### ISSUE TITLE
Watched states don't persist

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#148]
Just to be clear, this is not a Nakamori bug. It is a JMM bug. It's just here to point out for people

**Comment by bigretromike** [comment]
hmm does watch status reset of reboot and got not saved to db ?

**Comment by da3dsoul** [comment]
I don't know the details, but they seemingly randomly revert

**Comment by bigretromike** [comment]
after jmm reboot or kodi reboot ?

**Comment by da3dsoul** [comment]
Rebooting Kodi doesn't necessarily do it, I days seemingly because I haven't figured out what causes it

**Comment by bigretromike** [comment]
hmmm so its cache problem then ? kodi send status to cache, cache is not saved?

**Comment by bigretromike** [comment]
will take a look on this to test it to see if I can reproduce it

**Comment by da3dsoul** [comment]
I think this is fixed

**Comment by bigretromike** [comment]
Im assuming this was fixed in 3.6-beta 
Strange that there is no 3.6-stable until now... 
I will mark it as fix'd then - but sadly its in jmm beta build currently.
