### ISSUE TITLE
If you change menus while video is playing, it will refresh and possibly change selection

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#149]
This is better than it was, as it would toggle the watched state before, but I would like to fix it.

**Comment by bigretromike** [comment]
how you would change menu while playing ?

**Comment by da3dsoul** [comment]
Press escape or tab

**Comment by bigretromike** [comment]
oh, nice finding !

**Comment by bigretromike** [comment]
I fix this issue, new few testings and will try to make it look better as now it doing one function twice ;-P

**Comment by bigretromike** [comment]
This made gui a bit slower on 3.5 as there is missing cache - but it shouldnt be that bad as we move to service queue later on. Fixed in 2.0.7
