### ISSUE TITLE
Custom Cast Menu with Search by Cast

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#152]
Kodi's Cast Menu is likely not going to get any better anytime soon. I don't think JMM can search by cast member yet, but it can be done. We should make a cast menu that is basically a normal directory. Clicking on a cast member searches for shows with them. The summary is a short bio. The 'genre' is the character they play. The fanart is a hires Google image, we can probably run a Google search to return a URL for a picture similar to the way artist pictures in Android music apps do.

**Comment by bigretromike** [comment]
Also castandrole inside kodi wont support adding pictures and after you click them some kind of serach is going on. If we could make custom window with all info pictures etc we ciuld try to redirect that from picture action... Also searching by voice actor is posibble but we would need to make db table to store them and index each series that have them in cast which is possible 

On August 17, 2016 10:19:50 AM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>Kodi's Cast Menu is likely not going to get any better anytime soon. I
>don't think JMM can search by cast member yet, but it can be done. We
>should make a cast menu that is basically a normal directory. Clicking
>on a cast member searches for shows with them. The summary is a short
>bio. The 'genre' is the character they play. The fanart is a hires
>Google image, we can probably run a Google search to return a URL for a
>picture similar to the way artist pictures in Android music apps do.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/152

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
Basicly the same id. I saw few approches of this problem with custom windows and directory structures. Directories are easier windows are nicer and harder to make.

On August 17, 2016 10:19:50 AM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>Kodi's Cast Menu is likely not going to get any better anytime soon. I
>don't think JMM can search by cast member yet, but it can be done. We
>should make a cast menu that is basically a normal directory. Clicking
>on a cast member searches for shows with them. The summary is a short
>bio. The 'genre' is the character they play. The fanart is a hires
>Google image, we can probably run a Google search to return a URL for a
>picture similar to the way artist pictures in Android music apps do.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/152

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
Well confluence is ugly, which is why directories didn't look nice. With the theme I use or estuary, directories would look nice. That's why I suggested directories, you know suffer from it being easy.

**Comment by bigretromike** [comment]
- [ ] Search by cast/voice JMM implementation
- [ ] Search by cast/voice API implementation
- [ ] Search by cast/voice Menu
- [ ] Search by cast/voice Directorie
- [ ] Search by cast/voice linked to castandrole windows (? if possible)

**Comment by da3dsoul** [comment]
No we should still do this, even with #170. Cast info takes up too much bandwidth.

**Comment by bigretromike** [comment]
Proper api atribut will cut it out if its not needed

On October 27, 2016 3:10:56 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>No we should still do this, even with #170. Cast info takes up too much
>bandwidth.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/152#issuecomment-256636145

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
If you are still interested at this @da3dsoul fell free to add it to shoko (api/issue) as for now I assigned this to you. If you not interested please close this.

**Comment by da3dsoul** [comment]
Update.
Here's a query for searching by cast. We'll need to make an xref table for speedup and fuzzy searching. The xref table should have AniDB ID, MainTitle, Character Name, Seiyuu Name, and an int Enum representing the importance of the role.
The Example uses Hanazawa Kana. The end result should allow fuzzy searching, with corrections for name ordering, romanization differences, and simple misspellings. An example of a simple misspelling is my habit of saying Kanazawa Hana, then realizing it's wrong....

The example also gives a basic outline of the Enum.
```
use JMMServer
select anime.MainTitle as 'Series Name', chars.CharName as 'Character Name', anime2char.CharType as 'Role', va.SeiyuuName as 'Seiyuu'
from AniDB_Anime anime
inner join AniDB_Anime_Character anime2char on anime2char.AnimeID = anime.AnimeID
inner join AniDB_Character chars on chars.CharID = anime2char.CharID
inner join AniDB_Character_Seiyuu vas on vas.CharID = chars.CharID
inner join AniDB_Seiyuu va on va.SeiyuuID = vas.SeiyuuID
where SeiyuuName like 'Hanazawa Kana'
order by case
when CharType like 'main character in' then '1'
when CharType like 'secondary cast in' then '2'
when CharType like 'appears in' then '3'
when CharType like 'cameo appearance in' then '4'
else CharType end asc, MainTitle
```

**Comment by bigretromike** [comment]
Is this in proper place ?:-) shouldn't this be on shoko-issue-tracker? That would be a nice feature to have as now Kodi support characters in correct manner

**Comment by da3dsoul** [comment]
It's also in Shoko's tracker

**Comment by bigretromike** [comment]
https://github.com/japanesemediamanager/ShokoServer/issues/595  for reference

**Comment by da3dsoul** [comment]
Okay, cast now loads in ms. I just need to implement API, and we can make some menus

**Comment by bigretromike** [comment]
ok, i will release now; because Im starting getting asci-encoding errors which I think you fix in mean time

**Comment by da3dsoul** [comment]
I've not? Can you post a log somewhere not in this issue?

**Comment by bigretromike** [comment]
will update, check then. if so I will make issue

**Comment by bigretromike** [comment]
shoko 3.8.1 update + 2.1.17 = everything is all right, as I suspected. I probably used dev version and not clean after it. Also I finally (i think) resolve issue with my audio setup - so will watch more again ;-)

**Comment by bigretromike** [comment]
https://github.com/bigretromike/nakamori/commit/a4b0f586384a5558c8a315c9e692f52d3757c285
@da3dsoul great job !
