### ISSUE TITLE
Respect setting to automatically go to first unwatched episode

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#153]
I already know how to do this.

**Comment by bigretromike** [comment]
so basicly this remove need of -continue- item ?

**Comment by da3dsoul** [comment]
Basically, but it can stay in case you to manually do it

**Comment by bigretromike** [comment]
ok. so this will be a setting inside nakamori right ? so maybe after your implementation we switch -continue- default False and your Auto first unwatched True ?

**Comment by da3dsoul** [comment]
No, this is a Kodi option for normal video libraries. Now that we have an easy way to read settings, I thought it would be cool to use that.

**Comment by bigretromike** [comment]
true true :+1:

**Comment by bigretromike** [comment]
so maybe as we can easy access settings we could check if that setting is on, if on then turn off -continue- and vice versa

**Comment by da3dsoul** [comment]
I'd leave it there, if you scroll around, it's nice to be able to just hit continue and go back to the next episode. It's not hard to turn off if you want the Kodi option but no menu item. It's why I made the setting in the first place

**Comment by bigretromike** [comment]
you have a good point, it also depend of user experience :-)
I will wait for you to finish this and see what you came up with

**Comment by da3dsoul** [comment]
Mk. I'll open idea and write it up now. I was working on JMM

**Comment by da3dsoul** [comment]
Mk go ahead and take a look at it

**Comment by da3dsoul** [comment]
This is implemented. Reopen if you want something different
