### ISSUE TITLE
Add proper resume

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#154]
View offset is the last closed stream position. We will need to refresh the XML to get the updated position. I will test and get this working sometime. Work all week and school's first week.

**Comment by bigretromike** [comment]
Why only in last open stream?every file have its offset also there are two offsets one internal (sometimes kodi ask do you want resume) and external one (our that we dont update in our player)

On August 22, 2016 7:47:29 AM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>View offset is the last closed stream position. We will need to refresh
>the XML to get the updated position. I will test and get this working
>sometime. Work all week and school's first week.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/154

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
JMM keeps track of the position as it's streams. By last stream I mean per file. Kodi's isn't reliable as it doesn't keep the data for URLs reliably, that's why we use the new watched system. Refreshing the XML is necessary as the position we have is from the previous stream, not the one we just played. We could have our own db for it, but no point as JMM already does.

**Comment by bigretromike** [comment]
But having our db would skip the refresh part, or we can add api call that return info about episode so we dont have to refresh each time new thing is added the nakamori service alreafy have sqlite implementation as he use queue and most of this we are taking will be move to service as it will be in backgroud acording to kodi dev team 

On August 22, 2016 10:04:24 AM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>JMM keeps track of the position as it's streams. By last stream I mean
>per file. Kodi's isn't reliable as it doesn't keep the data for URLs
>reliably, that's why we use the new watched system. Refreshing the XML
>is necessary as the position we have is from the previous stream, not
>the one we just played. We could have our own db for it, but no point
>as JMM already does.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/154#issuecomment-241340486

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
I'm pretty sure that already exists, that's why I said I'd test

**Comment by bigretromike** [comment]
Ok but have in mind that soon nakamori will be expanded with service plugin 

On August 22, 2016 10:15:16 AM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>I'm pretty sure that already exists, that's why I said I'd test
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/154#issuecomment-241342667

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
Yep

**Comment by da3dsoul** [comment]
OK, an episode's key will load the XML for only that episode, so it should be plenty fast, especially if I rewrite the roles and tags to only be on the first episode, or better, part of the directory, so it only gets added to the series XML (once) and not individual episode's XML

**Comment by bigretromike** [comment]
I understand that that changes will be on the jmmserver side and then ported to nakamori? Good thing, as from I remamber tags/cast are now linked to first episode of directory so if you query one episode it would end up with tags and casts. Also did you looked into kodi v17 new castandrole window which was improved with new Skin it look decent and maybe we could benefit from it as it just went Beta

**Comment by da3dsoul** [comment]
Most of the JMM side was there before, just not always working. I'm rewriting the optimizations I had before in case you didn't see in JMM's commits. No I haven't seen it yet. The more info dialog hasn't seemed to work for me at all in Krypton.

**Comment by bigretromike** [comment]
No, I didn't inspect jmmserver commits. Alot of code didnt work because there are tons of iproviders, scenarios and bundles of data that use same structure/naming but end up looking different - as we use those pesky mediaContainers. I will check krypton soon as I update all my media centers to it as it looks that krypton will hit stable soon now (Alpha -> Beta -> RC -> Stable)

**Comment by da3dsoul** [comment]
I'm waiting for ReKOver before I move my desktop to it. The inability to overwrite the context menu pisses me off as well. With each version they seem to be taking away and deprecating more and more Python capabilities without any improvement to plugin API of any kind.

**Comment by bigretromike** [comment]
that can be true, probably they force more and more to use json-rpc-api for most things. I wouldn't mind even but make it better and add thing that was asked 7 years ago ;-) its time, you know. but yeah, open source - if you really want something commit it ;-)

**Comment by da3dsoul** [comment]
I don't like huge projects, as soon as I'm familiar with something, it changes

**Comment by da3dsoul** [comment]
Or they bash my programming skills and write something even more stupid

**Comment by bigretromike** [comment]
:-) so true

**Comment by bigretromike** [comment]
Let's update this...

We could use db for this (the one in nakamori): id_file | time 
or we could reuse shoko offset/position for streams if there ever was something like that implemented 
or add /api/episode/position to manipulate offset/position for both stream and local files to enable anyone to use this.

What you think @da3dsoul

**Comment by da3dsoul** [comment]
Add an endpoint to Shoko. It already has the ability, and we should make as many features able to be used in multiple clients as possible

**Comment by bigretromike** [comment]
Will do, could you point me to value that shoko use for file that store it ?or its not there and need to be added?

**Comment by da3dsoul** [comment]
Try VideoLocal.SetResumePosition

**Comment by bigretromike** [comment]
`/api/file/offset` added;
doing nakamori part now;
