### ISSUE TITLE
Respect Kodi setting to hide plot on unwatched episodes

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#155]

**Comment by da3dsoul** [comment]
Should probably hide thumbnails as well.

**Comment by da3dsoul** [comment]
videolibrary.showunwatchedplots

**Comment by da3dsoul** [comment]
Default true. False hides then

**Comment by bigretromike** [comment]
I see you dig up to kodi settings, impresive that you want to respect those settings :-) 
Good job @da3dsoul

**Comment by bigretromike** [comment]
If you are up the task (and im 100000% sure as you likely already onto this) I will wait for this, and push release with it on board.

**Comment by da3dsoul** [comment]
Added

**Comment by bigretromike** [comment]
You are to quick ;-)

**Comment by da3dsoul** [comment]
Yeah, I could have a really nice job...but I fucking hate school. Unfortunately, I also recognize I don't know enough to have the cool, fun programming job I want. I could probably get a shitty underpaid and overworked programming job for noobs right out of college with no experience.

**Comment by bigretromike** [comment]
or we can make real test units and get the know-how to get better jobs ;-) buahaha

**Comment by da3dsoul** [comment]
Haha it's why I do this...not because I find projects I like, install them, get everything up and running, then find a bug that pisses me off enough to start on it.

**Comment by bigretromike** [comment]
:-)
