### ISSUE TITLE
Adding python tests

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#156]
the code is getting bigger and bigger
is one point of time we should add python tests so we can test the logic of those function even before testing it on kodi and jmm.

As im new to python I will start reading about this.

But is there a point ? Im looking for similar approach from others add-on developers and im not sure. 

@da3dsoul any thoughts ?

**Comment by bigretromike** [comment]
that would also add ability to add travis or other automats like jenkins and also prevent us from braking old things that we forgot about when adding new ones.

**Comment by da3dsoul** [comment]
Start here https://www.jetbrains.com/help/idea/2016.2/code-inspection.html

**Comment by bigretromike** [comment]
Im familiar with this.
Im talking more like this: http://docs.python-guide.org/en/latest/writing/tests/

**Comment by da3dsoul** [comment]
I see. Due to the network interaction, it would be annoying, but possible.

**Comment by bigretromike** [comment]
yeah - but main question is, if its worth the trouble

**Comment by da3dsoul** [comment]
I'd say no.

**Comment by bigretromike** [comment]
thats what my intuition also says, but my curiosity tell me the other way ;-) I will have this on hold ;-) play with it a but on local host and see how hard it can be

**Comment by bigretromike** [comment]
you forget to include "it"

**Comment by da3dsoul** [comment]
https://www.jetbrains.com/help/pycharm/2016.1/type-hinting-in-pycharm.html I know I was looking up the link

**Comment by da3dsoul** [comment]
With that, IntelliJ knows exactly what everything is and how to analyze it

**Comment by bigretromike** [comment]
That dosn't look as bad as I would imaged. Only sad part its easier in python 3, but kodi use 2.7

**Comment by da3dsoul** [comment]
This is IntelliJ! There's a plugin for that. I'm testing one now...

**Comment by bigretromike** [comment]
:O 
✅

**Comment by bigretromike** [comment]
> When Python 3 is specified as the project interpreter, you can use annotations to specify the expected return type:
> ...
> For Python 2, you can specify return types in the Python stubs.

So for me its a bit depend from python version ;-)

**Comment by da3dsoul** [comment]
Yeah. I need to get the debugger up and running. But when that happens, IntelliJ will write all of those for us.

**Comment by bigretromike** [comment]
^_^

**Comment by da3dsoul** [comment]
IntelliJ is supposed to write those for us...it's a work in progress

**Comment by bigretromike** [comment]
You would be they greatest salesman :-) you would sell IntelliJ easily, even knowing its free

**Comment by da3dsoul** [comment]
Well I have been a salesman for Verizon. I did great and made like $750 every paycheck (two weeks). Unforgettably, they closed the place in town since they were scum that shorted everyone's pay. I will receiving a nice check in a few weeks from the lawsuit, though.

**Comment by bigretromike** [comment]
^_^ you sold that story to lawyer like a pro ;-)

**Comment by hidden4003** [comment]
> I see. Due to the network interaction, it would be annoying, but possible.

Network interaction is not needed, you put the expected minimal response into the test, then when you get some bug, you add new test with buggy response, fix the code to make test pass. That way you can make sure your code handles all the previous bugs correctly.

**Comment by bigretromike** [comment]
This is correct. 

I'm experimenting with porting `bash` to `python` code with unit-tests.

Thanks for bumping this. I hope to get to this in some day.

**Comment by bigretromike** [comment]
as test make perfect sense for only the part of nakamori plugin, its not as needed as I think It was;
In the end @da3dsoul you were right;
