### ISSUE TITLE
Manual mark as watched/unwatched doesn't work

### ISSUE THREAD

**Issue by hidden4003** [bigretromike/nakamori#157]
Kodi 17 krypton Skin Estouchy
Android 5.1 
JMM Server both 3.5.0.2 and 3.6.0.2
Nakamori 2.0.10

Only in one series Hitsugi no Chaika after episode ends there is no popup "Mark as watched", if I mark it as watched manually it can only be seen in nakamori but JMM Desktop does not show the episode as watched.

Mark as unwatched doesn't work in all series, if I do clear cache and restart Kodi it keeps showing me that episode is not watched but JMM Desktop still shows it as watched. Restarted everything, desktop shows episode watched, nakamori shows unwatched.
XML shows viewCount=1 for the episode.

**Comment by da3dsoul** [comment]
Mhmm.... I'll look at it further

**Comment by da3dsoul** [comment]
Wait.... Krypton makes a difference. I'll test at work on my phone

**Comment by da3dsoul** [comment]
Use the one that has a capital u and w for unwatched/watched. Until we figure out how to override or remove the other mark as watched

**Comment by bigretromike** [comment]
yup, duplicate menu is bad :/

**Comment by bigretromike** [comment]
https://github.com/bigretromike/nakamori/issues/150

**Comment by hidden4003** [comment]
Makes sense meaning I used kodi built in thing and it saved it somewhere inside kodi, and now that value is overriding the one we get in xml showing the episode as unwatched.

**Comment by da3dsoul** [comment]
Yep. Exactly what happens. It's why I rewrote the watched system. It removes the calls the Kodi watched system and handles the flag completely from JMM

**Comment by da3dsoul** [comment]
Clear the cache in Kodi to 'resync' with JMM

**Comment by bigretromike** [comment]
cache is in C:/Users/youruser/appdata/roaming/kodi/cache

**Comment by da3dsoul** [comment]
Better link %appdata%\kodi\cache

**Comment by bigretromike** [comment]
yeah, same thing :-) forgot that one ;-)

**Comment by bigretromike** [comment]
instead of deleting cache I would just mark it as unwatched and then marked as watched (the proper one ;-) )

**Comment by da3dsoul** [comment]
I say clear cache because while testing, it can be so screwed you don't know what matches JMM anymore

**Comment by bigretromike** [comment]
that is also a way :-) if he marked more than few

**Comment by hidden4003** [comment]
Yep works now.
