### ISSUE TITLE
missing menus

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#158]
"Vote needed" - missing context menu to vote
"Unsort" - should not have menu for vote etc as its unknow id
"Tags" - missing series context menu

**Comment by da3dsoul** [comment]
Tags has the context menu for me. You need to actually select a series, but it is there

**Comment by da3dsoul** [comment]
I found the issue with voting

**Comment by da3dsoul** [comment]
The s in series and E in episode for the settings need to be capitalized

**Comment by bigretromike** [comment]
lol, who would knew

**Comment by da3dsoul** [comment]
Okay all of these are fixed
