### ISSUE TITLE
Marking as watched is extreamly slow on "All" list

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#160]
This is because now we mark it in jmm server and then refresh list of episodes/series and that operation is slow on "All" tab.

I propose that we check current tab and if its "all" we do it old way, mark it on server and mark it with build in function "toggle" as it will be definitly faster and we wont lost the advantage of using the better refresh way on episodes

**Comment by da3dsoul** [comment]
That's mostly my fault. The randomized images commit I made caused a massive slowdown by accident.

**Comment by bigretromike** [comment]
Also but reloading all list to refresh on state is killing it to 

On September 6, 2016 7:38:46 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>That's mostly my fault. The randomized images commit I made caused a
>massive slowdown by accident.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/160#issuecomment-245028868

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
Now it takes approximately 5 seconds to load the All list for me. That's good enough in my book. If we can, further speed up would be nice, most of the time is now Nakamori parsing and building the info for Kodi.

**Comment by da3dsoul** [comment]
According to my debugger, it took less than a second to load from JMM server

**Comment by da3dsoul** [comment]
Happiness! I put in plenty of work to get it there...

**Comment by bigretromike** [comment]
https://github.com/bigretromike/nakamori/issues/163

**Comment by bigretromike** [comment]
for Kodi 16.1 and 17-beta1
Both version (2.0.11) and current master load all in 26seconds

**Comment by da3dsoul** [comment]
Regenerate contracts

**Comment by da3dsoul** [comment]
#163 again

**Comment by bigretromike** [comment]
I would see only paging as result...
But main question is:
1. Does Kodi support paging on listItem ?
2. Can kodi add listitems to already drawn list ?

**Comment by bigretromike** [comment]
As replay to me: 
ad1. No kodi dont support pagination (you add "next page" by hand)
ad2. you could but in the end you need to refresh/redraw it so .... 

Currently the ALL is an issue as itself - we cut the load time we can go back to this

**Comment by bigretromike** [comment]
'All' filter for 1700+ items generate in few seconds. This shouldn't be a big problem now;
