### ISSUE TITLE
Automatically disable gzip on fast connections

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#161]
Because why save bandwidth

**Comment by bigretromike** [comment]
So its good time to make nancy use gzip ;-) 


On September 6, 2016 7:40:18 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>Because why save bandwidth in a virtual pipe...
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/161

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
but you have right. There is there any benefit in this ? any time/resource wise ? even 1% ?

**Comment by da3dsoul** [comment]
Enabling gzip causes a slight overhead on server and client. In exchange, less data is sent back and forth. In local settings, there is no point in conserving bandwidth

**Comment by bigretromike** [comment]
so no real data... ok... go for it ! We had it off at beginning and it was doing ok

**Comment by bigretromike** [comment]
that would be if (settings.gzip==off or localhost) so if one of them would be present then no gzip

**Comment by da3dsoul** [comment]
Yeah it's not so much a numbers problem. Enabling gzip on localhost is like zipping a folder before and after moving a file on your computer. It's just pointless

**Comment by da3dsoul** [comment]
Probably make a small helper function that says `return addon.getSetting('ipaddress') == 'localhost' or addon.getSetting('ipaddress') == '127.0.0.1'` then call it as `if addon.getSetting('use_gzip') == 'true' and not localhost()`

**Comment by bigretromike** [comment]
you did wheel.. but thank to introduce of hostnames as you wanted.. now it can be anything :-) so we just check for "localhost" "127.0.0.1" and also "::1"

**Comment by da3dsoul** [comment]
True there's probably a way to figure out if it's localhost other than that

**Comment by bigretromike** [comment]
yes it is. we could query on start api call like /api/version 
and then you would know if there is jmm-server running on same machine ;-)
that would work if someone is using hostnames instead of ips also someone could use local ip for same machine - but to be honest most people will leave it at default (127.0.0.1) and any other change (beside ipv6 network only that will change it to ::1) will be external machine.

**Comment by da3dsoul** [comment]
Well I'll probably change this so that any ping of less than 10ms disables it. Makes it more simple.

**Comment by da3dsoul** [comment]
That way, it's always on LAN or so fast we don't care

**Comment by bigretromike** [comment]
dont do that
i have <1ms on all my servers on LAN, but we discuss to disable it on localhost only

**Comment by da3dsoul** [comment]
Oh fine.

**Comment by bigretromike** [comment]
also ping could be blocked and you have to handle this and that.. we check setting , easier and more fool-proof

**Comment by da3dsoul** [comment]
Right some places have security

**Comment by da3dsoul** [comment]
Get version doesn't work. It responds fine from my phone at work

**Comment by da3dsoul** [comment]
Eh string compare is good enough

**Comment by bigretromike** [comment]
you testing nancy right ?:P

**Comment by da3dsoul** [comment]
No...

**Comment by da3dsoul** [comment]
I'm using master to help squash bugs

**Comment by bigretromike** [comment]
i was referring /api/version on nancy build but ok. we will do string compare

**Comment by da3dsoul** [comment]
K
