### ISSUE TITLE
Newly added - series vote missmatching

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#162]
I added "new game!" but each episode have 3 digit value as rating (look like size name)

**Comment by da3dsoul** [comment]
Hang on

**Comment by da3dsoul** [comment]
First, it's a JMM bug, second, what branch are you on, as I fixed it awhile ago

**Comment by da3dsoul** [comment]
That, or I'm misunderstanding

**Comment by bigretromike** [comment]
im using stable -2.0.11

**Comment by da3dsoul** [comment]
No I meant which JMM server

**Comment by da3dsoul** [comment]
Do you mean the rating is like 685.54 (made up number)? Instead of 6.85

**Comment by bigretromike** [comment]
maybe (but it has 0 votes)... aparantly .. but those look more like 685.00 
i will try to include log is few sec

**Comment by bigretromike** [comment]
`<Video GenericId="17354" AnimeType="AnimeEpisode" thumb="http://127.0.0.1:8111/JMMServerREST/GetSupportImage/plex_404.png" parentThumb="http://127.0.0.1:8111/JMMServerREST/GetThumb/1/11736/0,6667" grandparentThumb="http://127.0.0.1:8111/JMMServerREST/GetThumb/1/11736/0,6667" key="http://127.0.0.1:8111/JMMServerKodi/GetMetadata/1/5/17354" index="3" type="episode" title="What Happens If I`m Late to Work?" year="2016" updatedAt="1473360612" addedAt="1473360612" lastViewedAt="1473368384" originallyAvailableAt="2016-07-18" original_title="Chikoku Shitara Dou Narundarou" rating="580" viewCount="1" EpisodeType="1" EpisodeNumber="3">`

**Comment by bigretromike** [comment]
rating="580"

**Comment by bigretromike** [comment]
its nakamori fault then, not sure why

**Comment by da3dsoul** [comment]
Yeah, that's what I was saying. Knew it was JMM's fault. Swear I fixed it though.

**Comment by bigretromike** [comment]
maybe you fixed it after 3.6.0.4

**Comment by da3dsoul** [comment]
The rating on mine is 4.74

**Comment by bigretromike** [comment]
its not on all of them, few have 4.12 few have 412

**Comment by da3dsoul** [comment]
No it was like back in 3.5 then again in 3.6.0.1

**Comment by bigretromike** [comment]
then its not fixed as there is no patern on them which have and which dont bad rating value

**Comment by da3dsoul** [comment]
Run this update AnimeGroup_User set PlexContractVersion = 0 and restart JMM server

**Comment by bigretromike** [comment]
its not like they all have bad rating, its only few of them - but jmmd have good ones.. so its maybe something with super ultra stable media container

**Comment by bigretromike** [comment]
also this is newly added series, after upgrade.

**Comment by da3dsoul** [comment]
From SQL

**Comment by da3dsoul** [comment]
Yeah same

**Comment by bigretromike** [comment]
to bypass safe lock:
```
update AnimeGroup_User set PlexContractVersion = 0 WHERE AnimeGroup_UserID > 0;
```
Also that didnt help
