### ISSUE TITLE
Cleanup and Optimize

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#163]
It's a good time. JMM server now takes less time than this to load.

**Comment by bigretromike** [comment]
I wont believe till I see it ! checking

**Comment by bigretromike** [comment]
For Kodi 16.1
Both version load all in 26seconds

**Comment by da3dsoul** [comment]
use this https://dl.dropboxusercontent.com/u/31454410/regenContracts.sql

**Comment by da3dsoul** [comment]
then restart server

**Comment by bigretromike** [comment]
yeah, that speed up regeneration :+1:

**Comment by da3dsoul** [comment]
After regenerating, it should be lightning fast to load in Kodi

**Comment by da3dsoul** [comment]
It took about 5s for 400 groups. Don't know how many you have

**Comment by bigretromike** [comment]
1513 series. sadly

**Comment by da3dsoul** [comment]
Mmm you know groups exist? And that they can only group direct sequels.

**Comment by da3dsoul** [comment]
By the math, 20 seconds is reasonable

**Comment by da3dsoul** [comment]
Still cutting 4s of that per 400 will make that ~6s

**Comment by bigretromike** [comment]
Server isin't the fastes on my end ;-)
so math dont apply from your machine

**Comment by da3dsoul** [comment]
... My processor has a really bad single thread rating. I didn't think there would be worse.

**Comment by bigretromike** [comment]
i5-4460 + 4GB Ram + MariaDB 
want db for testing ?:-)

**Comment by bigretromike** [comment]
also jmm work realy unstable recently - love to crash on ocassions :/

**Comment by bigretromike** [comment]
"All.XML" that is 13mb maybe its buffore size that make it hard. or there is to much of iteration over something ... will try out that debug thing today

**Comment by da3dsoul** [comment]
I've not had it crash at all on 3.6.1.0

**Comment by da3dsoul** [comment]
Try the no cast option and see if helps any

**Comment by da3dsoul** [comment]
I'm just curious

**Comment by bigretromike** [comment]
oh sh*t, 4sec

**Comment by da3dsoul** [comment]
Haha #152 and that problem is solved.

**Comment by bigretromike** [comment]
Yea, that or better optimatization :+1: or even compression

**Comment by bigretromike** [comment]
This is already in progress and this issue was about jmm and legacy nakamori.
