### ISSUE TITLE
disable episode image for series you are watching 

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#168]
While watching i saw image that spoiled story a bit. We have spoiler filter for tags, we could add api call to jmm for this on json format to send less data and add a proper option. This could be a 'watching' thing so you dont spoil story and can browse not seen one. Also if you watched episode you would see image with this. Good indicator of watched episodes also :-)

**Comment by da3dsoul** [comment]
Already there iirc, there's a Kodi option to disable it, and it made it adhere to the setting

**Comment by da3dsoul** [comment]
Hmm there's an error in that. First, the setting is Show Plot for Unwatched Episodes. Second, I made a logic error and it is always hidden when enabled

**Comment by da3dsoul** [comment]
Also apparently I had decided not to block images. I'll make another setting

**Comment by da3dsoul** [comment]
I need to stop programming past 11 am

**Comment by bigretromike** [comment]
Nah its fine :-) i know about plot setting also it would be great thing to send data to nancy with POST so we could write what we need vs default get give you everything 

On October 9, 2016 8:39:51 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>I need to stop programming past 11 am
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/168#issuecomment-252504052

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
![screenie](https://dl.dropboxusercontent.com/u/31454410/Github%20Issues/screenshot017.png)

**Comment by bigretromike** [comment]
<3

On October 9, 2016 8:47:53 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>![screenie](https://dl.dropboxusercontent.com/u/31454410/Github%20Issues/screenshot017.png)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/168#issuecomment-252504532

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
Sorry, but if the name of the episode is a spoiler, that's not my problem anymore....
