### ISSUE TITLE
Add cast images

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#170]
https://github.com/xbmc/xbmc/pull/10619 <-- this is PR for it being pushed. We wait for merge + release.. until then Note taken

**Comment by phil65** [comment]
merged.

**Comment by da3dsoul** [comment]
Cool. I'll implement it in the morning.

**Comment by da3dsoul** [comment]
My checkbox will remain, though. Cast is nice and all, but not if I can't search it. Hmm. A callback for that would be fabulous.

**Comment by bigretromike** [comment]
Great news then. One is done now we need to resolve somehow contex menu issue (sort, edit)

**Comment by bigretromike** [comment]
@phil65 care to help with this one http://forum.kodi.tv/showthread.php?tid=294077 ?

**Comment by da3dsoul** [comment]
Right. I was going to do this

**Comment by bigretromike** [comment]
Hahaha yeah you said so :-) im waiting till 3.7 stable and will rewrite nakamori with apiv2

On November 9, 2016 3:00:13 PM GMT+01:00, da3dsoul <notifications@github.com> wrote:
>Right. I was going to do this
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/170#issuecomment-259420912

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
downloading Beta 7 (I know Beta-6 included this cast thing) and testing xD
