### ISSUE TITLE
Select first unwatched episode not working

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#175]
Only on Krypton, doesn't throw an error

**Comment by bigretromike** [comment]
testing it out:-) you could write where that setting was and it was in advanced ;-)

For 1 non fully watched series: it select 02 episode (which is 3 item or 2 when continue is disabled)
for fully watched series: it stay on ... 
on other non fully watched series its on ...

We could check the setting if its on and if its on then invoke 'continue' action as its basically the same

**Comment by bigretromike** [comment]
This option is broken or does nothing for add-ons as even if it mark ... as unwatched episode it should reset the position as I have it on "Always" so it should always stay on "..." if it work but it look as it doesn't as you pick "continue" and then backspace and when you reenter the position is on proper item, you can use backspace also to test this. so imo the best hack would be the way you did few other settings "if is set then run -continue- action"

**Comment by da3dsoul** [comment]
Ah yeah I keep it on advanced. You know I like my settings haha. It only has issues in Krypton. I don't have continue or parent ... item. It already invokes continue internally.

**Comment by da3dsoul** [comment]
I find it weird because moving the selection on watched states works.

**Comment by da3dsoul** [comment]
Maybe adding a sleep (500) would help. Idk it's worth a try.

**Comment by bigretromike** [comment]
hard to tell. but as I looked for your option in menu I found that before krypton it was in Library setting not in Video setting so they try to move it to video items or its only for Library as the new add-on system was introduced

**Comment by da3dsoul** [comment]
I dunno, but it is listed the same in the settings XML

**Comment by da3dsoul** [comment]
I suppose I'll test the JSON RPC result, to make sure it is returning correctly, after that, it's probably an issue getting the control list

**Comment by bigretromike** [comment]
Is this fixed? As it something I didn't used?

**Comment by da3dsoul** [comment]
Nope

**Comment by bigretromike** [comment]
Is this relevant anymore ? It could be moved to be used in Library and not in Addons (like state from 27.dec.2016)
Did you successfully test JSON RPC result ? or we are not interested in this anymore ?

I have this option enabled but it doesn't work as it is overwrite with "last selected item" 
If you want to force it you could check for this setting (or add ours in settings as someone could want different behavior) and trigger "-continue-" behavior. 
Also this behavior is working if you browser serie with shortcuts/keyboard as you use backspace to go up so the selection is preserved.

**Comment by da3dsoul** [comment]
This finally pissed me off enough to sit down and try.
