### ISSUE TITLE
Support User Votes

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#177]
Certain skins support showing the user's vote as well as the community vote. Make and parse API to retrieve the vote we set.

**Comment by da3dsoul** [comment]
I'm going to revise this.

**Comment by da3dsoul** [comment]
It may also be necessary to override the vote value (by setting) so that it can be shown in other skins without support.

**Comment by bigretromike** [comment]
But also we want option to mark episode (if there is no way to add it without skin edit) by adding symbol (utf8?) or item next to episode. also I see this as Option so if someone like the minimalistic style then we wont force it.

**Comment by da3dsoul** [comment]
I don't know a skin that doesn't support it.

**Comment by bigretromike** [comment]
ok, I was afraid we would have to add some hidden column to add "star/vote" something. but we can always add it as text

**Comment by da3dsoul** [comment]
I know at least Confluence, KOver, Mimic, and Estuary all support it.

**Comment by da3dsoul** [comment]
details['userrating']=int(rating)

**Comment by bigretromike** [comment]
let check if user already voted o current episode so it will skip "vote_always"
