### ISSUE TITLE
Automark don't always work (Kore related?)

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#178]
When watching sometimes episode get marked sometimes it don't. The message is visable but selection is not moved and mark is not present. 
The only error I can read out of log is this

```
AddOnLog: Joystick Support: Failed to initialize directinput joystick: no buttons, hats or axes
```

Error looks like Kore-related. 
I will try to narrow kore-kodi relation with not marking....

Using Kore to navigate, Kodi 17rc1

**Comment by da3dsoul** [comment]
I can't reproduce (I do have a gamepad). Every once in awhile, it won't refresh the watched icon until a manual refresh, but that's not new.

**Comment by bigretromike** [comment]
I didn't know that one, never had the issue before.

On January 16, 2017 8:38:01 PM GMT+01:00, da3dsoul <notifications@github.com> wrote:
>I can't reproduce (I do have a gamepad). Every once in awhile, it won't
>refresh the watched icon until a manual refresh, but that's not new.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/178#issuecomment-272946166

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
I think it is related with timming. Because it tend to be often when I use "vote always after watching"

Could you remind me why we want from: use buildin watch toggle + send sync to server to: send sync and refresh list ? Was it because it would sometimes confuse watched/unwatched episode or what ? @da3dsoul

**Comment by da3dsoul** [comment]
It's because when you use Kodi's internal watched states, it caches them. Then whenever you try to override them, it takes the cached value instead. If an episode gets out of sync, it's a pain to fix. An episode can get out of sync in several ways: the server doesn't mark properly due to an error in either the server or Nakamori, Kodi doesn't mark due to an error in Kodi, or you mark it as watched or unwatched in Kodi and try to mark it on anything else. This way, the server handles it and Kodi can't cache it.

**Comment by bigretromike** [comment]
Hmmm... We could just make if (send-json) == 200: toggle_mark, that would; and somekind of "sync_episodes" that would iterate by each and set it... that would make it easier on big episode list so it wont have to refresh and probably fix this issue. What do you think ? Any cons ?

**Comment by da3dsoul** [comment]
We can't touch or even check the status of the Kodi cache, so no. If we can't guarantee that we are overriding the cache, or at least make sure that it is staying updated, then we need it to stay as a reload. If we could edit list items after creation, then we could make an API to retrieve only the watched states for all of the episodes and set them instead of reloading them all. The point is, I want to know if Shoko has it marked. I don't care if I watched it in Kodi if Shoko doesn't know about it, as many of my filters rely on watched status

**Comment by bigretromike** [comment]
sending api_call for mark and getting in respond 200 is 99,99% guarantee that shoko marked it (0.01% if for a bug in shoko) the logic of reading it to mark is assuming that shoko is broken and didn't marked it. 
I understand the concept you presented.
But knowing that each time you api_mark give you 200 only if it successful give you 99,99% that It is marked and marking it then in kodi is only the logic thing. if its anything than 200 then we dont call api_mark and we dont desync kodi cache. 

As its like you said that we cannot edit single items in List it this would help with #160 a lot;

But I have a question: if we use Toggle_Watch and that information will be in cache, and read list of episode from api that have different watch playcount we will overwrite cache right? 
But if that would be the case we wouldn't desync watch states in first place or that desync is only in current view and when you reenter same series is synced already?

**Comment by bigretromike** [comment]
also the #160 could be less of an issue if it load super fast ;-)

**Comment by da3dsoul** [comment]
No, once you mark it once with toggle watched, it won't let you override it at all. I tested thoroughly for various ways to make it work, but we can't use toggle watched at all, or else it causes issues. You need to delete the cache to be able to override it again

**Comment by bigretromike** [comment]
Then we stick with current thing

**Comment by da3dsoul** [comment]
It's annoying, but waiting for code 200 only means that it works on server side, it still doesn't account for Kodi breaking, which I've had happen. Once that happens, I need to delete my cache and Kodi it's super slow for music until it's rebuilt. I'm done trying to use toggle watched unless I have a guarantee that I can disable the cache for just it from the addon. I don't use only Nakamori to handle Shoko, and I don't use Kodi for only Nakamori, so there can't be any situations where the set up becomes specialized for only working together.

**Comment by da3dsoul** [comment]
Yeah. We should work on making loading faster so it's not a worry.

**Comment by bigretromike** [comment]
All is working better after that one submit, so we could leave with it. I'm more annoyed with this bug than #160

**Comment by bigretromike** [comment]
For me it looks like (I have VoteAlways enabled):
1. watching episode
2. watching being stoped with (stop) but after 80% (default) so it trigger mark
3. When the Vote GUI is shown - but when its before drawing ListItems (the background have empty List) and I make vote it won't mark episode.

The only thing that came to mind is that the status is send, and refresh is executed before listitem are drawn (from cache) so the data isin't updated.

Maybe any new ideas @da3dsoul  ?

**Comment by da3dsoul** [comment]
Dunno. Sounds like it's probably the cause, though

**Comment by bigretromike** [comment]
This is still relevant; (2.1.10 - 2.1.12); 
Is not that frequent. 
Maybe a little delay before Vote Menu show up ? What do you thing - or there is other way to check if listitem is populated ? (if its the reason for this error);

**Comment by bigretromike** [comment]
This is likely related to this: https://github.com/bigretromike/nakamori/issues/213 as I'm working on #213 this one is getting close.
