### ISSUE TITLE
bad Search Thumb

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#18]
Currently its "Others" not "Search"

**Comment by da3dsoul** [comment]
We really should fix this, it's painfully easy, and will clear it from the issues list

**Comment by da3dsoul** [comment]
Honestly, we should make our own thumbs, so bandwidth is solely for needed info

**Comment by bigretromike** [comment]
That is a great idea !!!!!!!!!!!!

On August 17, 2016 9:12:25 AM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>Honestly, we should make our own thumbs, so bandwidth is solely for
>needed info
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/18#issuecomment-240331743

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
Any ideas @da3dsoul , i know you are good with ps ;-) it probably will better tgan my own nakamori-logo but I wont get jelly abour it ;-)

**Comment by da3dsoul** [comment]
Haha. I'll look into it. Been busy. I might draw some stuff up in class today.

**Comment by bigretromike** [comment]
Also we could just add some anime-related image from any-chan and slap text on it :+1: I don't want to force you to make another A PS like icon that will hunt us with lawsuits ;-)

**Comment by da3dsoul** [comment]
Haha that was a joke to make fun of @ElementalCrisis

**Comment by bigretromike** [comment]
:+1: also no blood ;p

**Comment by da3dsoul** [comment]
Dammit. There goes my plan for Higurashi thumbs

**Comment by bigretromike** [comment]
hahah, psycho edition for Halloween would be cool but lets stick to regular version ;-)

**Comment by ElementalCrisis** [comment]
@da3dsoul is just upset that he can never top that PS looking icon.

**Comment by da3dsoul** [comment]
Hahaha it was fabulous

**Comment by bigretromike** [comment]
But there is allways a chance to work as art designer in some dark alley china town business that sells "Abode Photocrop SC 11.0"

**Comment by bigretromike** [comment]
maybe something like this ? https://www.iconfinder.com/iconsets/world-of-anime + text that would be a proper otaku way ;p but im curios what will you came out with ;o

**Comment by bigretromike** [comment]
or circle/folder style like this: http://www.deviantart.com/morelikethis/437929500

**Comment by bigretromike** [comment]
so many great icons. Im starting to hate those generic ones

**Comment by da3dsoul** [comment]
God so many good icons. None of them would make good media icons, but they are damn cool.
