### ISSUE TITLE
Seperate legacy version

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#184]
for people using older version because of reasons
there will be final legacy version out in repo as separate plugin

**Comment by da3dsoul** [comment]
I'm fine with it, it's getting messy to keep up

**Comment by bigretromike** [comment]
Also this will be only done - AFTER 2.1.0 release as the old one will be replaced with 2.1.0 and the "new" old one will be added as seperate plugin name to avoid upgrade conflicts.
