### ISSUE TITLE
Ignore Vota_Always when user already voted

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#185]
We should probably skip voting even when always_after_watch_vote is enabled when user once more rewatch it.

**Comment by da3dsoul** [comment]
Check if user rating exists, if not vote

**Comment by da3dsoul** [comment]
Check my latest commit on server and Nakamori, I added support for user rating

**Comment by bigretromike** [comment]
Yeah thats what I want. 
Also are you familliar with "userrating" if present will be shown in listitem as rating ? or it will be ignored and need to be replace by use when drawing item ?

**Comment by da3dsoul** [comment]
Depends on the skin for how it's displayed. It's a separate info label
