### ISSUE TITLE
Need of build_tv_seasons

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#186]
We used to use "seasons" as builder for directories like "episodes" "credits" "trailers". Current API return them as episode with different type (same as AniDB does).

We can stick with "old" way and make those in virtual directories and query for same url twice (one when entering series and invoking season_build) and one after entering directory like "episodes"
or we can drop this in favor of icons in menu, or virtual directories inside serie (its one less enter in directory for people that want to watch series) also this way we could add "hide" options to hide extra things

I would like to know your opinion on this one @da3dsoul as you are more into kodi-skin thing and will know if we can pull this of (with icons/symbols) or we better of the old way

**Comment by bigretromike** [comment]
Also I never recall if there was a single series that really had more than 1 season and was linked to same anidb_id

**Comment by da3dsoul** [comment]
Depends on how you count seasons. TvDB seasons are different. In my case, I group series by 'season', and like that menu. The code should be cleaned up (you could refactor half of that into helper functions), but I like the layout as is.

**Comment by bigretromike** [comment]
Thanks to new eps_list its simpler to create those I need to add level below to check if episode have files to not create empty dictionaries

**Comment by da3dsoul** [comment]
Well the server isn't ever supposed to add empty directories

**Comment by da3dsoul** [comment]
Well the server isn't ever supposed to add empty directories

**Comment by bigretromike** [comment]
but it does . also its good way for 3rd party go have ability to know what shoko knows about series and what episode are missing. Ultimate way to check if you miss something that was added to anidb ? would be great to have missing episodes in red colors so when you watch series and somehow you end up missing some ep in middle of season you would know that inside kodi ;-)

**Comment by da3dsoul** [comment]
That's true, but I'm not sure how that would work. You can't control Color. We could prefix [Missing File] to it I guess

**Comment by da3dsoul** [comment]
But we need to stop writing slow dirty hacks when the problem is a bug in the server. If an empty directory is provided, then fix it, not check everything to see if it's empty.

**Comment by bigretromike** [comment]
problem is in logic of server.
you ask for episode and server provide it
you dont ask for episode that have files
we can ad filter like ?local=1  to show episodes that have files
api should expose those episode as cuting this information off will cut ability to tell 3rd party supported that there is missing episode

**Comment by bigretromike** [comment]
or vice verse ?all=1 when you want all episodes not only the one you have

**Comment by da3dsoul** [comment]
I think the inverse is better. For normal Kodi serving (legacy), it only gave files you have, so the code is already done

**Comment by bigretromike** [comment]
legacy nakamori use legacy shoko/jmm.

We do as you pleased - I care little which version we pick, but both need to be available [as apiv2 is for everyone ]

**Comment by bigretromike** [comment]
https://github.com/japanesemediamanager/ShokoServer/commit/c7806f12429a8252b346049ecc631b81e4b194b5  pushed. now its only 'local' episodes to query all add &all=1 in call
