### ISSUE TITLE
List of things not working in 2.1

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#190]
First, I will point out that most of these are on the server end, but they apply here

- [x] Episode Type menu has no icons
- [x] Some filters don't have art, Movies, Years, Tags
- [x] Episodes are out of order
- [x] Episode URLs are sometimes 'None'
- [x] Search Works (I know I'm just gloating)
- [x] Search > box > Serie > .. > you end up with search box
- [x] Year and Tag Filters are not populated
- [x] Loading groups throws an error after taking too long
- [x] Loading Episodes takes forever, and sometimes works
- [x] "NEWADDON Invalid Date Format "01.01 00:00:00.0001" error

This will updated as time goes on.

**Comment by da3dsoul** [comment]
Okay the error with groups is that it's trying to load as episode types instead of groups, and being mad that the JSON wasn't what it expected.

**Comment by bigretromike** [comment]
Mine episodes aren't out of order ?!
loading episode work always for me - i will double check more groups

only thing that kills me is "all" its taking to long on 1700+ series collection but that something to work out

**Comment by bigretromike** [comment]
Some filters missing images are probably related with this: https://github.com/japanesemediamanager/ShokoServer/issues/560

**Comment by da3dsoul** [comment]
Do you have Use Server Sort enabled? I do

**Comment by bigretromike** [comment]
nope - im using default ones 👍 thats why i need you for high-tech-advanced-settings ;-)

Im investingating search problem that when you go back from serie you end up with searchbox

**Comment by bigretromike** [comment]
lol, the search box error is in legacy version also 👍

**Comment by bigretromike** [comment]
Search tool - rewriten - https://github.com/bigretromike/nakamori/commit/0dab7ef710b09ec2fccac8761e37d37a6ef73cad

**Comment by bigretromike** [comment]
Tag/year api fix : https://github.com/japanesemediamanager/ShokoServer/commit/8b6abb9267b006cdbcbcfa4d6895cece0753aee2

**Comment by bigretromike** [comment]
tag/year support https://github.com/bigretromike/nakamori/commit/61bdd00dd0eb0ef6a124499dc4b3d8851da80294

**Comment by bigretromike** [comment]
Also as the nature of filter-TAG_YEAR I would skip images as current it need to iterate thru series that are inside it... I was hoping that this would be in image_db inside server as default picture that server would populate/update - of course if you think you know how to speed that up..... just do it but that ain't priority as thanks to "search" + "fuzzy" which you could easly search for same tag without needed to scroll down ;-) 👋

**Comment by bigretromike** [comment]
about: "Episodes are out of order" i tested it few times with "Use server sorting" and the only diff is that when its on there is no number next to titles but the order looks ok - but maybe my test group was to small

**Comment by da3dsoul** [comment]
Fixed sorting in several areas. I'll keep note of anything not sorted properly

**Comment by bigretromike** [comment]
If I remamber good the episode aint any more in bad order ? @da3dsoul anything we can put off the list ?

**Comment by da3dsoul** [comment]
Correct that is fixed

**Comment by bigretromike** [comment]
Also as I walk thru all of them: Some filters don't have art, Movies, Years, Tags - also is fixed as I see poster for all of them (with exception of Movies as I dont have that filter)

**Comment by bigretromike** [comment]
Do you 'spam log' or you randomly hit those "Episode URLs are sometimes 'None'" @da3dsoul

**Comment by da3dsoul** [comment]
Randomly hit them. Also, the art thing happens still.

**Comment by bigretromike** [comment]
maybe it was because of last changes you made that broke playing files ? 👍 
Also Years and Tags have arts , some have some don't.
The random function you added to api hit random serie in tag/year if that one have no art then to bad.

**Comment by bigretromike** [comment]
@da3dsoul what you think, was the empty URL because of that ? as it was imposible to populate them with master API since the fix

**Comment by da3dsoul** [comment]
What do you mean? Which fix?

**Comment by bigretromike** [comment]
you change somehting in api that i mark you where. that file url couldn't populate so it was empty.

**Comment by bigretromike** [comment]
also they are empty if you have episode data but not file

**Comment by da3dsoul** [comment]
If they are empty, they won't show up. The serie all parameter works now. The issue is when the URL was empty, but the file exists.

**Comment by da3dsoul** [comment]
My latest commits don't do anything about it

**Comment by bigretromike** [comment]
one of your commits change level !=1 to >0 and as the code couldn't have other value than 0 because it wasn't pass down, it wouldn't list files under ep. thats why Unsort didn't worked (one of reasons)

**Comment by da3dsoul** [comment]
Ah, that would make sense, but should files always be populated inside episodes? Marking things as != 0 is dangerous, and could lead to your 500mb issue

**Comment by da3dsoul** [comment]
Actually, nvm. I checked the JSON, and the files info was being sent

**Comment by bigretromike** [comment]
:-) its fixed now it now handle `level` correctly but that little change cut out files out of eps.

**Comment by da3dsoul** [comment]
I see. It was hard coded weird

**Comment by bigretromike** [comment]
I didn't get any `None` types in url, and it was probably a bug after api changes.
Until we get it once more I close this one;

**Comment by da3dsoul** [comment]
I've not seen it recently, either. Fair game
