### ISSUE TITLE
skin questions

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#195]
Could you add a semi section like tv-shows have but for nakamori ? with continue watching etc ?
Would be cool - or is that impossible without having those items in library ?

**Comment by da3dsoul** [comment]
Screenshot it. I don't know what you mean

**Comment by bigretromike** [comment]
![111](https://cloud.githubusercontent.com/assets/6052025/22783665/165108aa-eecd-11e6-8177-f503de85685f.jpg)
Something like this

**Comment by da3dsoul** [comment]
That's done with skin widgets

**Comment by da3dsoul** [comment]
No idea how

**Comment by bigretromike** [comment]
but im asking because "user_rate" is added manualy so this could be added also ;-)
And would be cool to be able to see custom/pre-define filters series out there like in "tv shows" menu;

**Comment by bigretromike** [comment]
or are you throwing `that` skin away ?

**Comment by da3dsoul** [comment]
No. User rating was also already there. I just made it prettier. I'll need to re merge it with the latest stable version

**Comment by bigretromike** [comment]
making it prettier is also a good tweak :-)
more of those and skin have its reason 
especially when its updated from source;

**Comment by da3dsoul** [comment]
https://dl.dropboxusercontent.com/u/31454410/skin.estuary.zip Here is the link for the latest version (17.0 stable). I'll be updating again when relevant.

**Comment by bigretromike** [comment]
no git repo ?:P

**Comment by da3dsoul** [comment]
Not really no. I have a fork, but due to the way that Phil updates Estuary, I need to do a manual merge against a new repo every version.

**Comment by bigretromike** [comment]
oh, thats bad. also there are 2 skins in the zip. is one orginal and other on yours ? or what?

**Comment by da3dsoul** [comment]
That was unintentional. I'll fix it

**Comment by da3dsoul** [comment]
https://dl.dropboxusercontent.com/u/31454410/estuary_delta.zip correct link

**Comment by bigretromike** [comment]
up and live;
i deleted `.idea` and make proper zip from it (naming);
