### ISSUE TITLE
sorting tv-shows by Air (Premiere) Dates 

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#197]
> I've asked this before, but is there any plans to implement sorting tv-shows by Air (Premiere) Dates in Nakamori? Currently sorting by Date seems to be doing something else
since anidb has this information available, it should be possible to implement?
- Anvi (via Discord)

**Comment by da3dsoul** [comment]
Date sorting has been broken in kodi for awhile. I can't figure out what is wrong with it. If you use the Browsing -> Use Server Sorting in Nakamori Settings and set a sort method in your desired filter, it works. It doesn't allow for the convenient on demand sorting in kodi, though.

**Comment by bigretromike** [comment]
maybe the sorting option can be added to skin, with some workaround ?

**Comment by da3dsoul** [comment]
It's not a skin issue, it's a Kodi date parsing issue. It doesn't help that the air date is almost never correct in API right now.

**Comment by bigretromike** [comment]
hmmm... So I assume we want to go to `Years` then pick year, and then it should sort via `Date` if we get proper air date from api? or we see this in different section (imo, i would stick with `years` so we wont end up with another pre-defined hardcoded filter)

**Comment by bigretromike** [comment]
If I recall there been some tweaks for this by you @da3dsoul into server, right; It should be better after new server version;

**Comment by da3dsoul** [comment]
Maybe idr

**Comment by bigretromike** [comment]
17.5 came up; anything changed ?
