### ISSUE TITLE
Please keep backwards compatibility in mind

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#198]
Duration is changing in Kodi 18. I saw that you already changed it to work. Good job, but that also broke duration in every version prior. GetUserAgent is also new, and threw a fatal error on startup. Just keep in mind that not only is not everyone going to update quickly, but some of use will keep kodi 16 for a long time to come. Kodi 16 just works, 17 still randomly crashes.

**Comment by bigretromike** [comment]
This is a very important note.
As Stable is now 17, but from your information it looks its not that polished as we would like to see.
It also depend if we are talking about android version or pc, as pc never crashed for me as im using it on 3 pc's. 
This will need to be address. We can check what kodi version is used or we use dedicated version for older kodi (15/16) and for current one. this way we can set which version of kodi is needed to install plugin as its there already - but that way we need to keep up with both version with updates. 
Which path would you like we to take ? kodi-dedicated or check-kodi-version ?

**Comment by da3dsoul** [comment]
This is on desktop that it's crashed. I use seek a lot, as I'm often interrupted. That's usually what causes the crashing.
 We should Check version. It's too annoying to deal with more than one branch.

**Comment by bigretromike** [comment]
We could move function that are kodi-depended to seperate modules and import proper one for detected version, this way we would have same code base and use same functions but with different output as it would import only one (proper one)

**Comment by da3dsoul** [comment]
Good plan, but it would be an annoying refactor. I'm trying to fix stream info. It was thoroughly fucked up

**Comment by bigretromike** [comment]
I would stick with 17, but as I just remamber about 17 android 5+ needs and you reporting pc version is less stable than I would like to, we will do it anyway.

The only problem is pin point what is not working in 16, user-agent is simple to change. but what about rest?

**Comment by da3dsoul** [comment]
I'll test more when I get this working. I have a build of 16 portable on my laptop

**Comment by bigretromike** [comment]
maybe 17.1 will fix your problem
https://github.com/xbmc/xbmc/milestone/99?closed=1

looks like fixing alot of things as 17 is like refactored version and it the most buggies version out there. but as you see from shoko/jmm it the same deal.

**Comment by da3dsoul** [comment]
@bigretromike see the above commit

**Comment by bigretromike** [comment]
15.2 is also a thing... as it looks like... need to get more data on this subject

**Comment by bigretromike** [comment]
Instead of `DialogBusy` I used `DialogProgress` which should be backwards compatible; 
care to check @da3dsoul ?

**Comment by bigretromike** [comment]
Some data you would like to see @da3dsoul: 
18.x 3%
****17.x** 75% 
**16.x** 13%**
15.x 6%
14.x 1%
unk 2%
Looks like nakamori works on 18.x also as I didn't test it there. 
I will try my best to not break anything on 16.x 👍 as its second major version that use Nakamori

**Comment by bigretromike** [comment]
18.x 3%
**17.x 81%
16.x 6%**
15.x 6%
14.x 1%
unk 3%

It's a good sign that more people start using kodi 17.x 👍

**Comment by da3dsoul** [comment]
We have a Leia changes issue, so I'll close this
