### ISSUE TITLE
Sort by rating and numeric episode/watched count.

### ISSUE THREAD

**Issue by Andy2244** [bigretromike/nakamori#199]
Hi, i try to switch from mediaportal/MyAnime3 and i really miss the option to sort by AniDB rating, since thats my default sorting for most categories. I also miss that i can't directly see how many episodes a series has and how many i have already watched, this was shown in the listview in MyAnime3.

Maybe those features could be added, this would be nice.

thx
Andy

**Comment by da3dsoul** [comment]
Kodi does not have this ability unfortunately. If you make a filter with a set sorting, and then enable this in Nakamori Settings, then it will work:
Nakamori Addon Settings -> Browsing -> Use Server Sorting

**Comment by Andy2244** [comment]
ah oki thx this should work too.
