### ISSUE TITLE
Auto-Update in repo fixed

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#201]
There was an error made by me on repo. 
It would ignore anything added to requirements for plugin.
Now auto-update should work fine and install missing modules;

I fixed script for making the repository - now anything edited in addon.xml in plugin/module/service will also be on repository to enforce updates.

@da3dsoul sorry for the trouble and thanks for fast workaround;

If changing anything in script.module/service remember to include proper version in addon.xml in nakamori (the version there is a minimal version) as we don't want to leave out people not using repository out -as they will be inform by Kodi that they need update manually module;

**Comment by da3dsoul** [comment]
Well it doesn't do anything yet, but I will. :)

**Comment by bigretromike** [comment]
hahaha :-) It is fully automated - I could run script with cron :-) but better not push all the updated xD 
Now its more bulletproof than before and there was a but that would only work for both script and service on same version but its gone.

Auto-update now install all needed modules from repo so we ready to go with those;
