### ISSUE TITLE
Series/episodes not shown in list

### ISSUE THREAD

**Issue by hidden4003** [bigretromike/nakamori#202]
I had an issue with some series and even episodes not being show in Kodi. Tested on Kodi 16, 2.1.4, 2.0.22, 2.0.21, 2.1.4 (current) PC, and Kodi 16 (SPMC) Nakamori 2.0.22, Kodi 17 Nakamori 2.0.22 Android.
Shoko 3.7.0.6 (latest stable).

Only way I was able to fix it is to enable "Use server title" in the settings.
Default setting of "en" and Main title was not working properly. 
Issue is that my shoko desktop does not have the main title for anime in question, I did anidb and tvdb info updates that didn't help.

Series in question in my case were: "Seitokai Yakuindomo" was not in list at all and "Seitokai Yakuindomo *" was only showing 5 episodes instead of 13. 

![image](https://cloud.githubusercontent.com/assets/197087/24141632/bb6b9b56-0e2c-11e7-8c49-59cd507a9e6d.png)

Log with logspam enabled attached
[kodi.zip](https://github.com/bigretromike/nakamori/files/857650/kodi.zip)

Maybe you should fallback to server title in case the main title fails?

**Comment by bigretromike** [comment]
Anything will be better than "hiding" it from list. Even "Missing Data" would be better, but yes. Falling back to server title would be a good idea, also we could fallback to synonym[user_lang], then official[user_lang] and then to server.

I'm getting this to my collection right now. Will investigate later this day or tomorrow. 
Thank you for issue.

**Comment by bigretromike** [comment]
I downloaded both serie, added it. 
I have eng-main title in setting - but the serie show up correctly (also both have main/end title) - same with "use server titles"

As this, both show up correctly;

This is for today - I'm working on injecting your data from spamlog to my test setup - to be able to get reproduce your behavior.

Only thing that come in mind is that when you switched version the library used cached version of modules/plugins.

Will give you more information later.

**Comment by bigretromike** [comment]
I downloaded both serie, added it. 
I have eng-main title in setting - but the serie show up correctly (also both have main/end title) - same with "use server titles"

As this, both show up correctly;

This is for today - I'm working on injecting your data from spamlog to my test setup - to be able to get reproduce your behavior.

Only thing that come in mind is that when you switched version the library used cached version of modules/plugins.

Will give you more information later.

**Comment by bigretromike** [comment]
@hidden4003 There was a fix made by @da3dsoul https://github.com/bigretromike/nakamori/commit/92ca18ad0e9d31cd0e756299eae485514d436b85 did this resolve your problem ?

**Comment by bigretromike** [comment]
@hidden4003 ? are we good ?

**Comment by bigretromike** [comment]
as there been more than week for test this, im closing. If the error persist @hidden4003 please reopen;
