### ISSUE TITLE
Nancy 1.x doesn't support asynchronous requests

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#204]
Due to that, file offset and trakt syncing just time out.

**Comment by da3dsoul** [comment]
The solution to this is to capture the progress and only send it after the video is stopped.

**Comment by bigretromike** [comment]
sure ? I remamber that trying it with fiddle And if I spam it with requests I still got all them done correctly

**Comment by bigretromike** [comment]
I will look it up at weekend then; solution would be make 1 api call for both things, until we migrate to Nancy2.0 if its really the case

**Comment by bigretromike** [comment]
OK, I tested. Nancy in latest stable version is async. If its not they someone f***ed it up. 
I can spam it with 10 x ALL, 10x series_all, 10xepi_info I get all quick request respond then I get the slower ones...

**Comment by bigretromike** [comment]
also: https://github.com/NancyFx/Nancy/wiki/Async

**Comment by da3dsoul** [comment]
You didn't notice I wrote that latest commit that made Nancy requests async? I found that article and fixed it, so yes it works now.

**Comment by da3dsoul** [comment]
They are not async in latest stable. Easy way to tell, play a file in Kodi, then start issuing requests in fiddler.

**Comment by bigretromike** [comment]
Strange as I tested with version that I posted above and it looks as async, maybe the problem is not async but the quantity of request ? maybe we should slow them down ?

**Comment by da3dsoul** [comment]
No it's fine to close this, as it will be fixed in the next release of shoko. I was just pointing it out. I happened to notice because halfway through a show I started getting a bunch of timeout notices

**Comment by bigretromike** [comment]
hmmm then im thinking it was also a timeout (full quote) problem. 
This could be tested on one point...

anyway, any eta for shoko? or its still 2018 ?:-)

**Comment by da3dsoul** [comment]
It's getting there. avael came back and started doing some much needed work on desktop. You might interested in github.com/japanesemediamanager/shokoserver/issues/545

**Comment by bigretromike** [comment]
Look nice
