### ISSUE TITLE
request for skin support: Rapier

### ISSUE THREAD

**Issue by dmean** [bigretromike/nakamori#205]
Any chance Rapier might be supported? I've been using it for years and Gade is very active with it. He is also very good about supporting user requested plug-ins, so there's a good chance he would be able to provide any needed info for getting Nakamori to work with it.

http://forum.kodi.tv/forumdisplay.php?fid=120

**Comment by da3dsoul** [comment]
What about it doesn't work? Most skins just work

**Comment by bigretromike** [comment]
Looking at the skin: http://i66.tinypic.com/sxg61i.png
Isn't it hard to read ? 

Also yeah, da3dsoul have point. 

It should work out-of-box, the only tweak that it could be missing is those awesome start that da3dsoul added to default skin. But who knows, Rapier could have that also. 

@dmean could you point whats not working - then we could gladly came with solution for it.

**Comment by dmean** [comment]
Thanks for the checking on this.

Running Kodi Kryption 17.1. The latest Rapier version for Krypton, 10.4.5, and the latest Nakamori off the Shoko website, 2.0.18.  

I'm afraid I haven't been able to get any of it working. This is my first time to try Nakamori, so I didn't know if I was doing it wrong or if it wasn't working with the skin. Looks like I'm just doing it wrong.

I got the repo installed and installed the main addon and all the helper parts. Went through the settings and thought I had it configured correctly. But then I couldn't figure out how to actually make it work with the skin. Didn't see reference to it anywhere in any of the settings. Even checked to see if it was actually a scraper to use when importing my anime into Kodi. Right now I've just got a smart playlist to show the contents of my anime drive. Couldn't see any way to do that with the addon.

I'll keep playing around with it and see if I can figure it out. Hate to waste your time on it. I'm sure I'm just not "getting it" since you both said it should work. I'll install Mimic and see if that helps me figure it out.

**Comment by da3dsoul** [comment]
Okay then. First off, do you have ShokoServer? That is required as Nakamori is a bridge between Shoko and Kodi. Second, it is a video add-on, so it'll be where those go. You'll need to edit the settings if the server application is not running on the same machine.

**Comment by bigretromike** [comment]
@dmean its true as da3dsoul wrote above.

Nakamori is not scrapper plugin. So to use it you need to go to add-on menu and launch it from there (later you can add it to video, or other places as shortcut).

Secondly, I assume that you have ShokoServer as Nakamori act as bridge (like da3dsoul) wrote above, mainly without running shokoserver (with added your anime drive there) you wont see anything in Nakamori addon. Shoko will do all the magic with your anime drive and you can explore/watch your anime collection via Shoko Application and/or use Nakamori to explore and interact with it via Kodi. 

As Kodi use somehting called Library in which you add folder/drives with your video/music/images the same concept for Nakamori is Shoko. Shoko manage your collection and Nakamori make it visible to Kodi.

I will close this issue then as this is not a skin problem (for now) but more of setting up .

Also remember to change ip of your shoko server inside Nakamori plugin settings so you can connect to it.

Have a great day
