### ISSUE TITLE
possible problem with external player

### ISSUE THREAD

**Issue by Ninimeth** [bigretromike/nakamori#206]
I've got playercorefactory.xml set up to play all the video files from Kodi with MPC-HC . I've run into a problem with that and Nakamori. Whenever I click "Play" on a file, Kodi just freezes up. With logging turned on, the running info at the top left just stops and the screen freezes on the episode info page. I have to ctl-alt-delete to quit Kodi.

I tried the same files through a normal Kodi source/playlist and they all played fine in MPC-HC. I removed the playercorefactory.xml file and they all played correctly through Nakamori in the Kodi internal player. It is just videos played through Nakamori to MPC-HC that is a problem. 

I've even uninstalled the SQL Server instance and reinstalled it and started over with a fresh Shoko Server twice now with the same result. Videos played through Nakamori to MPC-HC just freeze Kodi for me.

Kodi 17.1
Shoko Server 3.7.0.6
Nakamori 2.1.7

Here is the log file.

[log file on pastebin](https://pastebin.com/tTk7cTB9)

**Comment by da3dsoul** [comment]
I know dsplayer isn't working, but I didn't realize this wasn't. Use Ctrl+f and look for ".avi" in the log, then paste the link into the open dialog for mpc and see if it works. If it does, try running mpc via command line with mpc-hc.exe "[path]" /fullscreen /close and see if it works

**Comment by Ninimeth** [comment]
Launching the link from the command line worked perfectly. Even tried a new mkv file I hadn't tried before. Hit play in Nakamori, waited for the freeze, got the link from the log file, and launched it from command line. Worked just fine.

Oh, and I forgot to mention I'm using MPC-HC 1.7.11, the 64-bit version.

Let me know if there is some kind of other log file you need. I saw Kodi has a list of component log files to choose from.

**Comment by da3dsoul** [comment]
Hmm. It sounds like it's not even actually sending the link to mpc if that's the case. I wonder if it's the same issue as with dsplayer. I never got too far trying to figure out what went wrong there. If you can manage to get detailed logs from the video 'playback', it might help.

**Comment by da3dsoul** [comment]
If it's the same issue as dsplayer and we fix this, I'll be very excited to finally get that working

**Comment by bigretromike** [comment]
Im testing this. The only difference in log i gave is the local files use SMB url and Nakamori use http thru Shoko.

**Comment by bigretromike** [comment]
almost got this;

**Comment by bigretromike** [comment]
@Ninimeth fell free to test this build; I did and mpc-hc64.exe work correct with this. @da3dsoul dsplayer test ?
