### ISSUE TITLE
Series in groups are not marked as watched

### ISSUE THREAD

**Issue by Silentorchestra** [bigretromike/nakamori#207]
Groups of series refuse to be marked as watched and display that I have not watched any episode in a series. 
![untitled](https://cloud.githubusercontent.com/assets/27804703/25663577/5a4c08b6-3018-11e7-805b-258437060b57.jpg)
Yet if I open up a group in Nakamori the series within are marked as watched.
![screenshot002](https://cloud.githubusercontent.com/assets/27804703/25663725/c0c1a4b6-3018-11e7-954e-49cc3faf10a7.png)
Seems to be quite a strange issue...

**Comment by da3dsoul** [comment]
Versions, please. I know it's broken on latest

**Comment by da3dsoul** [comment]
Eh fuck it, I'll fix it now

**Comment by bigretromike** [comment]
@Silentorchestra mind telling the skin ? also thanks for pointing out the issue

**Comment by Silentorchestra** [comment]
Its nebula and no prob :)

**Comment by da3dsoul** [comment]
Fixed in next shoko ​​server

**Comment by da3dsoul** [comment]
Do be aware, unless you want everything to be unfinished, you should check Use Local File count.....

**Comment by bigretromike** [comment]
or have `full` collection with everything that is listed on AniDB ;-), but LocalFileCount is a thing to go - but you need to look out for missing episodes if there any

**Comment by da3dsoul** [comment]
There's often things on AniDB that are pointless to have. For example, nearly every movie has like 5 episodes, the first is the full movie, the rest are the weird groups that release a movie in 4 parts. No point in having all of them. Then there's Bakemonogatari. Commie doesn't include recap episodes, and I don't want them anyway. That's my reasoning, but it's my opinion, so it's a setting.

**Comment by bigretromike** [comment]
definitely a nice setting to have
