### ISSUE TITLE
Make TAG shorter so it wont overlap plot

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#211]
Tag is verrrry long. It tend to overlap on plot and you need to wait few seconds just to read plot in default skin on some views.

**Comment by da3dsoul** [comment]
Have you not used my skin? Mine doesn't have that issue.

**Comment by bigretromike** [comment]
I used it but I also wanted to support other skins so we wouldn't have to mod each by hand in case someone would like to use different ones 👍

**Comment by da3dsoul** [comment]
![img](https://dl.dropbox.com/s/op6rbdb2anrqp0b/screenshot004.png)

**Comment by da3dsoul** [comment]
Scrolling ftw

**Comment by bigretromike** [comment]
`Content length exceeded`

**Comment by da3dsoul** [comment]
Content Length is never enough!
