### ISSUE TITLE
Leia API changes

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#214]
https://forum.kodi.tv/showthread.php?tid=303073

Still beta, and nothing interesting for now. 
But this can be useful later.

https://alwinesch.github.io/python_v18.html

**Comment by bigretromike** [comment]
For now there was no major change or deprecation that we should worry about;

**Comment by bigretromike** [comment]
PIL. will be dropped;

**Comment by da3dsoul** [comment]
We don't use it, but that's odd

**Comment by bigretromike** [comment]
We USE it. Check how titles for calendar are created, lol

**Comment by da3dsoul** [comment]
Oh. I haven't even looked at the calendar code

**Comment by bigretromike** [comment]
We use it to overcome the limitation of Font support in Kodi, you have to edit skin files to add more fonts, and there is almost non smaller font. 
So I used PIL with custom font to be able to control size and font without hacking each time skin you use.
I saw script that hack your installed skin but that would only work if you dont update skins (or reddo it each time you update)
I prefer more clean approach without editing skins. 
But will have to look for other solution, but I think that PIL will be moved to module in repo if its not build in because I saw few Team-Kodi members using it to theirs addons.

**Comment by bigretromike** [comment]
https://codedocs.xyz/xbmc/xbmc/  full documentation as for RC2 which should be last RC before release. Time to python3+k18 combo.

**Comment by bigretromike** [comment]
> In the next couple of weeks a PR will go into kodi that keeps python sessions open as long a user navigates inside an addon.
> Reason is that this pushes performance significantly because modules are taken from python cache instead reloading / rereading them on every click.
> 
> From development side this means: Only the default python script (defined in addon.xml. commonly default.py or addon.py) are re-interpreted on every click.
> All imported (sub-) modules will be taken from cache and not reinterpreted.
> 
> What does this mean for you python addon dev?
> 
> - arguments passed from kodi to addon are only available in default script, if you need them in any of your submodule script you either pass the current arguments from default script into your submodules, or you call sys.argv inside your functions where the code is executed. Storing the value of sys.arg[#] in a global variable at the head of your submodule will not work because the code is only executed once on first module startup, but not on subsequent calls.
> - For compatibility reasons sys.argv[0] (base_url) and sys.argv[1] (plugin_handle) stay same when reused. This means that it is possible now to store them in a global variable in submodules.
> - if you are debugging / developing a submodule, you may have to first select an other addon and then return to your addon to get a fresh reload. Or switch reusing of python session off (see below)
> 
> Reusing of python sessions can be disabled in addon.xml, metadata section:
> 
> <extension point="xbmc.addon.metadata">
>   <reuselanguageinvoker>false</reuselanguageinvoker>
> </extension>

source: https://forum.kodi.tv/showthread.php?tid=303073&pid=2729071#pid2729071

**Comment by da3dsoul** [comment]
I'll keep this in mind, but it shouldn't be an issue

**Comment by bigretromike** [comment]
PIL won't be dropped: [source](https://forum.kodi.tv/showthread.php?tid=339970)

**Comment by bigretromike** [comment]
```
ListItem.setInfo()
Added labels setoverview, tag, sortepisode, sortseason, episodeguide, showlink. Extended labels genre, country, director, studio, writer, tag, credits to also use a list of strings. 
```

```
ListItem.addSeason(number, name = "") 
```

Looks like nothing more was added for our needs.

**Comment by da3dsoul** [comment]
We could use it, but only if skins do anything useful with the changes

**Comment by bigretromike** [comment]
We can use it anyway, we don't know what skins people will use, and it would be a nice thing to populate every data we can :-) so others addons/scripts/skins can benefit 👍

**Comment by da3dsoul** [comment]
Yep

**Comment by bigretromike** [comment]
Service related new things we can use:
```
XBMCAddon::xbmc::Player::onAVStarted
Will be called when Kodi has a video or audiostream. 
```

```
XBMCAddon::xbmc::Player::onAVChange
Will be called when Kodi has a video, audio or subtitle stream. Also happens when the stream changes. 
```

**Comment by bigretromike** [comment]
Leia is already on third release (18.0, .1, .2) so its time to close this one.
