### ISSUE TITLE
Context menu addition possible...

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#215]
If we change type from `video` to `files` there wont be default context menu;
but we would have to change some code and im not 100% what we will lose that way (maybe nothing);

What do you think @da3dsoul

**Comment by da3dsoul** [comment]
IDK sounds like a lot of effort but might be worth it

**Comment by bigretromike** [comment]
if infolabel aren't ignored then it shouldn't be that big of deal;

**Comment by bigretromike** [comment]
https://forum.kodi.tv/showthread.php?tid=325059  more info about similar thing (using play vs setresolveurl)

**Comment by da3dsoul** [comment]
That is some hacky shit right there. Try it

**Comment by bigretromike** [comment]
trying with little (-1 context menu item) can't tell if im doing something bad or what.. still doing research

**Comment by bigretromike** [comment]
if you set `isFolder = True` most of context menu is gone and its all fine except that name is without episode number - maybe something else. But for now im adding dummy empty items to move those options out of view.

**Comment by bigretromike** [comment]
I added `blank` items to move the default lower;
Had to add `resume` support by hand because it was handle by default context menu;
I couldn't find the post about making video as `files` to bypass the context menu and changing `setContent` ot `mediatype` to `file`/`files` didn't gave the results that was perfect. `isFolder` is quick and dirty hack but I can just assume that there could be a bigger problems later on with incorrect `content` and that could also break compatibility with external plugins/skins. 

I'm not sure if every platform share the number of max displayed items in content menu; 

The only other way to bypass it is to make WindowsXML or service that would catch the context_menu action and display custom made one. Not something I can do - maybe after redoing Calendar. 

For now this is the best option that wont confuse users (because of two 'mark as watched', 'More info" and 'Information' etc)

Fell free to hack shit out of it if that can work. Reopen if needed;
