### ISSUE TITLE
tags/years show wrong number

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#218]
while entering "tags", they are displayed with 0 next to it 
which looks like tag is empty but its not 

same goes to 'years'

**Comment by da3dsoul** [comment]
You mean the Filter?

**Comment by bigretromike** [comment]
Yeah

On September 19, 2017 8:40:05 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>You mean the Filter?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/218#issuecomment-330632552

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
This is on the server side. Hit update all stats and see if that fixes it

**Comment by bigretromike** [comment]
Nope, that didn't resolve my problem :-)

**Comment by bigretromike** [comment]
Its nakamori problem, server api give proper 'size' but its somehow ignored by nakamori.

**Comment by da3dsoul** [comment]
Ah I misread what the issue actually was

**Comment by bigretromike** [comment]
Strange I see `0` on one machine, but there is no number on other machine.
Both have `0` because when I enter 'Information' I see there is '0 episodes'

**Comment by da3dsoul** [comment]
Are you saying the series/group count is wrong?

**Comment by bigretromike** [comment]
No, it was the Filters for TAGS. Server respond with proper count of item in it, but Kodi would show it as `0` on one machine and ex `7` on other. so maybe it was (if still) problem with default skin as on one machine I could used your skin and on other it was default. also it could be a cache error where Kodi would cache size of those `filters`
