### ISSUE TITLE
idea: cache

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#219]
- [x] what if `cache` and `refresh`
- [ ] while `flag` in `queue`

**Comment by da3dsoul** [comment]
... What?

**Comment by bigretromike** [comment]
That a note for me so I will remember my idea from sick trip 

On September 19, 2017 8:32:55 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>... What?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/219#issuecomment-330630605

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
At

**Comment by bigretromike** [comment]
https://github.com/bigretromike/nakamori/commit/f92a0a806ac9fed726c38eb03f920fd100dba67e

**Comment by bigretromike** [comment]
No need to queue watch flags or votes. If there will be connection issue then media file will stop playing (with 1 exception, when using video proxy like eigakan) no need to wait with those. First half is there and was tested. Work very well when using VERY-VERY-BIG collection with slow internet connection away from home. First loading will take long time and the result will be cached for some time. that way next time it will be almost instant.
