### ISSUE TITLE
Can you update this in the repo?

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#221]
I made some changes that will make the cast list look better, as well as updating against phli65
https://www.dropbox.com/s/bmhr8ma1qki0gy8/estuary_delta.zip?dl=0

**Comment by bigretromike** [comment]
yup

**Comment by bigretromike** [comment]
done

**Comment by bigretromike** [comment]
if you want to make it more automatic I can use your git repo for this and build from master 👍

**Comment by da3dsoul** [comment]
Don't bother, there's too much manual stuff I need to do

**Comment by bigretromike** [comment]
oh, ok
