### ISSUE TITLE
Trakt full support

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#225]
I saw that Cazzar plex already support Trakt so it was finally fixed. 
We can make it work in Nakamori as it have still `(WIP)` tag

**Comment by da3dsoul** [comment]
Probably. I won't touch it, but probably

**Comment by bigretromike** [comment]
ok then, I will handle trakt support

**Comment by bigretromike** [comment]
Nakamori uses Shoko API where it should. Some data is send to trakt. Not sure if I have bad ids or it need to be manually liked but its somehow works. And the real problem is around Shoko end. 

https://github.com/ShokoAnime/ShokoServer/issues/754
