### ISSUE TITLE
shuttering/audio problems

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#226]
https://forum.kodi.tv/showthread.php?tid=323557

Just because the official channel is wayyy to populated with problems and with almost 100 views no replay.

**Comment by bigretromike** [comment]
looks like it could be a BT problem.

**Comment by da3dsoul** [comment]
BT as in BitTorrent?

**Comment by bigretromike** [comment]
bluetooth

**Comment by da3dsoul** [comment]
That makes a bit of sense actually

**Comment by bigretromike** [comment]
to bad there is no software way to tell it was this one fking-dongle without wasting few days to check it.
