### ISSUE TITLE
Python 3 edition

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#229]
as for now Leia 18.0 will ship with python 2.7
anything above will be shipping with 3.0 

test builds can be found here:
http://mirrors.kodi.tv/test-builds/

They giving two options ship plugin with both support or with 3.0 only support.

**Comment by da3dsoul** [comment]
It'll be easy

**Comment by bigretromike** [comment]
yeah, i tried yestarday. the 2 > 3 is super easy and its build into python.
I was thinking that we will want to have both version in one file... or should we end up with to seperate ? 
then afte 18, we would have another 'legacy' version ;-)

**Comment by da3dsoul** [comment]
I say legacy. We're going to have some major API changes again soon as well, and I'd rather not write for backwards compatibility on this one

**Comment by bigretromike** [comment]
if this is true then yes. we should drop all if not most backwards compatibility then. 
We need to discuss 2+3 version vs each python version in separate files.

I dont wan't to end up with 30% of file being `if` and `try` just to support both version, but also I don't know about adding same thing to both version on same time just to have them sync. 

If 2+3 workaround wont take 30% of file I would prefer that. I will try to sit down today and merge those.

**Comment by bigretromike** [comment]
https://github.com/bigretromike/nakamori/commit/b4b2d6a39af0b10ba5e5c03a2596dde3ef05c614 half thing done. Python 3 works but don't connect to server. Maybe your pyCharm debugging thing will help, because i had to reinstall everything

**Comment by bigretromike** [comment]
@da3dsoul

**Comment by bigretromike** [comment]
Where are here. Didn't have working files to test, and TagModule throw some error - which confuse me right now but yeah. Got most thing there: https://github.com/bigretromike/nakamori/commit/e566ac452afa5c7da919fe08866fe00833884f07

**Comment by da3dsoul** [comment]
You can remove the tag module. It's in server now

**Comment by bigretromike** [comment]
calendar v2 probably broke this;
