### ISSUE TITLE
New context menu for calendar

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#230]
- [ ] show info
- [ ] download missing info

- [ ] add to wanted
- [ ] remove from wanted

any suggestions ? @da3dsoul

**Comment by bigretromike** [comment]
cross this with some kind of trailer platform.... that would be sweet

**Comment by da3dsoul** [comment]
It would need to be a custom layout. I would make it a filter item in the main menu

**Comment by bigretromike** [comment]
yeah, I was thinking about WindowXML but currently its also not bad (as its in code anyway). plus is that that using current listview give us compatible for most (if not all) skins.

**Comment by bigretromike** [comment]
custom calendar v2 added;
that is concept with bad graphic etc. 
was hell of challenge why it didn't work with keyboard but hell, did it and need to fix two things with it;

**Comment by da3dsoul** [comment]
Some feedback on the new Calendar:
- Dates are inverted for my locale. We use 12/31/2018, not...whatever Europe uses.
- The text can't go over the poster. Basically none of it is legible. White on white, in addition to being too small to read.
- Make the posters 2-3x bigger. Scrolling is fine, but I can barely see them on my 50", so that says plenty.

**Comment by bigretromike** [comment]
There should be option for calendar with dates. Text over was for testing any idea how it should be hmm I can easily see them on 55 so .... Also there is option for that hehe ... But thanks for feedback we can edit it around your suggestions 

On March 24, 2018 3:41:31 AM GMT+01:00, Thomas Baer <notifications@github.com> wrote:
>Some feedback on the new Calendar:
>- Dates are inverted for my locale. We use 12/31/2018, not...whatever
>Europe uses.
>- The text can't go over the poster. Basically none of it is legible.
>White on white, in addition to being too small to read.
>- Make the posters 2-3x bigger. Scrolling is fine, but I can barely see
>them on my 50", so that says plenty.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/230#issuecomment-375840940

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
I actually didn't look at the settings.... I guess I'm too used to you just adding something and needing to add settings myself haha. The text is white and most of the posters are mostly white, so the text needs to be above or below the poster, but not on it

**Comment by bigretromike** [comment]
Context menu have been added - not functional that much but is added and handle all needed action;
