### ISSUE TITLE
mark and move on

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#232]
after watching episode the notification pop up, episodes got marked, but list item didnt moved.

**Comment by da3dsoul** [comment]
Don't break my list progression. That was a pain to get working

**Comment by bigretromike** [comment]
Ah sorry forgot to mention the issue is for stable 2.1.19 not master 

On February 18, 2018 3:59:57 AM GMT+01:00, Thomas Baer <notifications@github.com> wrote:
>Don't break my list progression. That was a pain to get working
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/232#issuecomment-366488779

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
It sometimes don't work 

On February 18, 2018 3:59:57 AM GMT+01:00, Thomas Baer <notifications@github.com> wrote:
>Don't break my list progression. That was a pain to get working
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/232#issuecomment-366488779

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
Hmm. I don't ever have an issue. Try playing with the delay

**Comment by da3dsoul** [comment]
It's a setting

**Comment by bigretromike** [comment]
I'm 120% sure it's that delay. But still annoying maybe new way to move on list or something because the default value don't work from time to time and we don't want force people to use 3-5 sec delay each finished video ;-) 

On February 18, 2018 7:41:47 AM GMT+01:00, Thomas Baer <notifications@github.com> wrote:
>Hmm. I don't ever have an issue. Try playing with the delay
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/232#issuecomment-366496153

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
It's like that because of loading times

**Comment by da3dsoul** [comment]
There's no easy way to do it in Krypton at least

**Comment by bigretromike** [comment]
Then do we got update for Leia ?

On February 18, 2018 7:47:03 AM GMT+01:00, Thomas Baer <notifications@github.com> wrote:
>There's no easy way to do it in Krypton at least
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/232#issuecomment-366496302

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
Idk I use DSplayer and don't update unless I need to

**Comment by bigretromike** [comment]
Ok will look into this before Leia go stable 

On February 18, 2018 8:43:22 AM GMT+01:00, Thomas Baer <notifications@github.com> wrote:
>Idk I use DSplayer and don't update unless I need to
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/232#issuecomment-366498357

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
This will be easier in the rewrite. I'll put it on that milestone

**Comment by da3dsoul** [comment]
Basically, my plan is to call the refresh from the end of the mark as watched script

**Comment by bigretromike** [comment]
Ambitious 

On March 12, 2019 7:44:27 PM GMT+01:00, da3dsoul <notifications@github.com> wrote:
>Basically, my plan is to call the refresh from the end of the mark as
>watched script
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/232#issuecomment-472132324

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
It didn't work...

**Comment by da3dsoul** [comment]
I have another idea. I need to find time to try it

**Comment by bigretromike** [comment]
We done with this one ? i remember asking about this and that time it wasn't a thing. 
now after rewrite as the dev version ain't my main version I cannot test this enough to mark is a closed without feedback from you @da3dsoul

**Comment by da3dsoul** [comment]
I think it's taken care of
