### ISSUE TITLE
You broke titles

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#233]
Use server title does not use the server's title

**Comment by da3dsoul** [comment]
I fixed them

**Comment by bigretromike** [comment]
Try to link commit it's harder to check it from phone 

On March 24, 2018 8:34:46 PM GMT+01:00, Thomas Baer <notifications@github.com> wrote:
>I fixed them
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/233#issuecomment-375918998

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
https://github.com/bigretromike/nakamori/commit/ebbd2f626d55ea2d36d54f8d45cf37babe474d9d
