### ISSUE TITLE
Calendar setting

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#234]
As for now both have pros and cons.
Why not make it as setting 'classic' and 'modern' 
classic without settings and modern as the 'more calendar like' with settings that are now.

I would love to have this even more functional so I could eliminate need to look up for calendar out side of kodi/tv,

@da3dsoul What do you think ? or is it overdo and we should pick one?

**Comment by da3dsoul** [comment]
I think you should wait, because we'll soon have AniList and AniChart support. That'll constitute more calendars of different types, so making some generic implementations and designs will be necessary.

Honestly, Nakamori is getting so big that I'd like to start modularizing it and redesign the menu layout to handle more like Desktop, with sections for basic utilities, calendars, group filters, server actions, etc. Right now we have one or two of each randomly thrown into the main menu.

**Comment by da3dsoul** [comment]
We'll need to discuss whether we want a simple menu layout that works with themes (what we have now), or use custom UI to make it look nicer like Kodi's dashboard. If we go with custom UI, then we could do some really nice things with a dashboard.

**Comment by da3dsoul** [comment]
We could always do both, with the simple menu being a failsafe fallback

**Comment by bigretromike** [comment]
hahaha, I was thinking the same today (about modularizing it). We can go with custom UI if you can handle it, but when saying custom UI you refering to use windows xml or framework for gui or you want to make custom skin ? because I would prefer to not stick with one skin - the one you made is great and give more options than default one but I can imagine that other people would like to use they own ones.

**Comment by da3dsoul** [comment]
Yeah, I have no clue. You can't really do custom UI without looking at least part of a skin in. Skins control layout in Kodi after all.

**Comment by bigretromike** [comment]
yes and no :-)  you can do it with framework so it looks same everywhere or you can do it with windowxml and add support for all skins - or there is a fallback thing that is used if custom.xml is not supported in your skin ? this is something interesting - because without that fallback I wouldn't want to force skin on users.

**Comment by bigretromike** [comment]
also `we'll soon have AniList and AniChart support.` when is that happening and getting release ?

**Comment by da3dsoul** [comment]
We're shooting for a release after I get back and finish up some stuff. It'll be in the release after that.

**Comment by bigretromike** [comment]
Great - but do you have any eta for first and second release ? because there is not much going on in server repo.

**Comment by da3dsoul** [comment]
The first: a weekish to two weeksish
The second: hard to say

**Comment by bigretromike** [comment]
Calendar will be redone in 3.1.0;
We know we need one.
Got few ideas of how it should look - but I'm open for discussion. 
Till then Im closing this issue as the question was answered and we are waiting for AniList/Chart support ;-)
