### ISSUE TITLE
opt-in: what you use statistic

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#236]
Ability to send option/configuration - optional, disable by default;
So we will know if anyone use those no-needed function that I add

**Comment by bigretromike** [comment]
`nakamori-modules-version`
`kodi-version`
`settings.xml` without apikey
I think there is nothing more needed to be honest.
OS is not important that much. 
settings would tell use if there is 'common' default settings that everybody use, and we could know focus on building around those.

I'm thinking about counter to cross that with settings like each enter into calendar would increased counter for 'calendar-use' and that would indicate if someone is having it in menu because he use it or not and left it as default.

What do you think about this @da3dsoul, all is good? half of it is good? none of it is good?

**Comment by da3dsoul** [comment]
Honestly, I think this is better in Server. I'd prefer to know what server features are used most so that we can make Nakamori's UI more intuitive for a normal user. If people like group filters, focus on better filter support, such as adding, editing, and show/hiding them. If people use search a lot, they we can improve the search UI immensely. Etc

**Comment by da3dsoul** [comment]
I could implement trackers and analytics into the API back end, and then the network activity is focused on Server where it should be.

**Comment by da3dsoul** [comment]
I've wanted some analytics for a while, but we need a place to store it as well as proper opt out/in and whatnot

**Comment by bigretromike** [comment]
So you are fine with data usage but you prefer them being in server, so we just api/something?=nakamori, and you will know that it was from nakamori and not desktop? But then you would have to send them somewhere from server, and how we other developers (or me) check that data ? would they be public accessible ? I see your point and shoko would benefit like hell from it, but still that don't resolve any question like 'do people use x or y ?' but ok. 
I will leave this as-is. Wont rush it to 3.0.0 then

**Comment by da3dsoul** [comment]
You seem to forget that I'm kind of the current lead dev of Shoko, and I would be able to access and deliver/give access to you if needed. Also, when Kodi asks for things from the API, it has a header that says, "hey I'm Nakamori", so that's not an issue either.

**Comment by da3dsoul** [comment]
We just need to pass that, and server will know

**Comment by bigretromike** [comment]
I know, but thats 17.x thing ;p

**Comment by bigretromike** [comment]
also do you still use that old debugger of your in nakamori ?
because Im replacing it with something ultra easy to use

**Comment by da3dsoul** [comment]
Before that, we get Mozilla. No one but nakamori calls with Firefox

**Comment by da3dsoul** [comment]
No you can remove it

**Comment by bigretromike** [comment]
also 'current lead dev' congratulation? what happened there ?:P are all Max progress got wiped ? so its you, hidden and cazar ?

**Comment by da3dsoul** [comment]
We have Google Analytics now. It's just a matter of implementing it. This could be done for APIv2, but it would be pointless, so waiting for APIv3 is the better idea

**Comment by bigretromike** [comment]
No thanks, I wont forward user data to place where is muliply people have access, you don't need to worry about this 😃

On March 12, 2019 7:41:06 PM GMT+01:00, da3dsoul <notifications@github.com> wrote:
>We have Google Analytics now. It's just a matter of implementing it.
>This could be done for APIv2, but it would be pointless, so waiting for
>APIv3 is the better idea
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/236#issuecomment-472131119

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
It's anonymous. You are identified as some guy from Poland, or so we think...you could be a VPN user! It's about stats. We are using it to track ban counts and various things like that.

**Comment by bigretromike** [comment]
I don't need Google analitics here 😃 so please don't enforce it. 

On March 12, 2019 7:48:07 PM GMT+01:00, da3dsoul <notifications@github.com> wrote:
>It's anonymous. You are identified as some guy from Poland, or so we
>think...you could be a VPN user! It's about stats. We are using it to
>track ban counts and various things like that.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/236#issuecomment-472133686

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
Well, we wouldn't enforce it. It opt-out easily, and it collects basically nothing.

**Comment by bigretromike** [comment]
You miss the point, will DM you later about it

On March 12, 2019 7:51:33 PM GMT+01:00, da3dsoul <notifications@github.com> wrote:
>Well, we wouldn't enforce it. It opt-out easily, and it collects
>basically nothing.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/236#issuecomment-472134885

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
mk. It's whatever. You know I don't really care either way.

**Comment by da3dsoul** [comment]
We aren't secretive about stuff, nor do we gather anything important. It is kind of cool to see, though.
![image](https://user-images.githubusercontent.com/5205810/54860295-82174000-4cee-11e9-9584-0918940cc14f.png)
![image](https://user-images.githubusercontent.com/5205810/54860291-73c92400-4cee-11e9-8d9a-9f1568cea33b.png)
![image](https://user-images.githubusercontent.com/5205810/54860287-6ad85280-4cee-11e9-972f-8f41e873437b.png)

**Comment by da3dsoul** [comment]
Those are basically the only windows that have any data. We don't give it anything except event and a session ID to distinguish that the user is unique.

**Comment by da3dsoul** [comment]
That's useful because we have a lot of new users who start server, see that it's not simple, close it, and leave. That means that our first time setup experience could use work. I'm not too worried about them, as patience is needed to get started with Shoko.

**Comment by bigretromike** [comment]
testing in progress...
