### ISSUE TITLE
Features from shoko 3.9.0.0

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#237]
Anything we should add from newest shoko server?
Because I recall you writing something that there will be some changes with 3.9 and I don't want to push/commit anything that would interact with you doing something.

**Comment by da3dsoul** [comment]
Already done!

**Comment by da3dsoul** [comment]
I wrote it in such a way that Nakamori wouldn't care

**Comment by bigretromike** [comment]
what about calendar etc ??! I remember you specifically said something about redoing api for that.

**Comment by da3dsoul** [comment]
That's not in 3.9. 3.9 was TvDB. The next version I plan on AniList being a major focus, depending on how messy the EF migration is.
