### ISSUE TITLE
Add serie to "get it later/wishlist" ?

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#238]
I know its not proper place to talk about it (or is it ?) but as we got some kind of calendar with also a filter named "aired today" I would like to have ability to add those series that I like from both of those list (calendar, aired today) to somekind of 'repository'/list and be able to later download those.
This was in shoko when there was torrent support  
We could make small db like the one for search inside nakamori (but that wouldn't sync across clients)
We could make or reuse or there is already something to add those in wishlist ? or add those to wishlist on anidb ? and retrive those via api ?

@da3dsoul

**Comment by da3dsoul** [comment]
We plan on it for Shoko Lists. It just needs proper implemention

**Comment by bigretromike** [comment]
great, but it depends on "how long till implementation" because if its something over month I can just make it for nakamori and just switch when sometimes in future shoko will have that.
