### ISSUE TITLE
hide rating

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#240]
** after and only after version 3.0.0 **

hide rating - all the time (for episodes and/or series)
hide rating after starting playing series - so those rates wont affect your opinion

**Comment by da3dsoul** [comment]
Heh. Later on we'll need to have support for multiple rating sources

**Comment by bigretromike** [comment]
Thats not a problem imo.

**Comment by da3dsoul** [comment]
No it's not. I'm just pointing it out

**Comment by da3dsoul** [comment]
We should go for a more custom settings panel. It'll make handing several things more user friendly

**Comment by bigretromike** [comment]
if more custom settings panel are your thing then maybe somekind od helper-skin? 
Or something to work with more than one skin? I know there are extender to skins so skins use those libraries to get more info etc. Im not skin guy, you are the one :-) with your hacks-and-tricks

**Comment by da3dsoul** [comment]
No I mean like how the YouTube plugin did there's
