### ISSUE TITLE
new content images

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#249]
From begging I used those `plex_*` images as those images were not as important then. 
As there will be big release (3.0.0) I would love to redo those. 
I would stick to nice font-ish images as series related could hurt someone (not everybody like to watch same things)

While doing those, there could be banner/fanart versions because current once are cut in middle to fit the kodi image requirement.

**Comment by da3dsoul** [comment]
Neptunia it is

**Comment by da3dsoul** [comment]
Haha

**Comment by bigretromike** [comment]
hahaha, saw that "no image" Neptunia already in client. Go ahead, anything is better than those old plex icons. It will end up in Neptunia Icon package ;p
