### ISSUE TITLE
Investigate missing fanarts in 'Fanart' view

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#250]
Need to check why "Fanart" view list have so many "default" images; 
Probably `poster` or something.

**Comment by da3dsoul** [comment]
I don't have the issue

**Comment by da3dsoul** [comment]
It's probably a server issue. Update all TvDB data. It'll take a while, but it should fix it

**Comment by bigretromike** [comment]
I updated it yesterday. Will look into this.
Also which version you talking ?:P because Im on 3.0 ;p

**Comment by da3dsoul** [comment]
Idk old

**Comment by bigretromike** [comment]
we don't support `legacy` here ;p

**Comment by bigretromike** [comment]
Yeah - link I thought. No tvDB link, no 'fanart' or 'poster' in images;
