### ISSUE TITLE
hide rating for unwatched episodes

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#262]
Something got broken...

**Comment by da3dsoul** [comment]
I believe it. I forgot to adjust the code that pertains to the settings

**Comment by bigretromike** [comment]
Hahaha great that you know whats wrong 

On September 1, 2018 2:28:02 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>I believe it. I forgot to adjust the code that pertains to the settings
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/262#issuecomment-417856371

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
You had some logic errors. I fixed em

**Comment by bigretromike** [comment]
it worked and its looked you simplyfied it a bit, also you had logic error also :-) you mismatch watched and unwatched :-)
