### ISSUE TITLE
Check for server status on entry and handle appropriately

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#265]
1. First, check for server status at the server address specified. If it returns connection refused or 503, then notify the user that there was a problem connecting to the server.
2. If the server responds with a message, then handle it.
3. If it's starting, then give a progress message and progress.
4. If it's started, then continue.

**Comment by bigretromike** [comment]
You want to include this before release?

**Comment by da3dsoul** [comment]
I'm working on it now. If I give up in the next day, go ahead and release without it

**Comment by bigretromike** [comment]
Look what I added few commits before, 
0. check if `ipaddress` or `port` changed, if not bypass checking (the working one are stored in `good_ip` `good_port`

**Comment by da3dsoul** [comment]
That's not needed. The status endpoint is probably the fastest endpoint in Shoko

**Comment by bigretromike** [comment]
even if - what is the point of asking server if is on on each enter series/filter/groups ? 
ask once, save it and handle the no/bad respond when asking about series/episode/group/filter.

**Comment by da3dsoul** [comment]
Error handling. I don't want to see a message about invalid json if we can't connect. We shouldn't be trying to build a list if we can't connect. The idea of saving values is good, but not there

**Comment by bigretromike** [comment]
if we handle it then instead "invalid json" you get "network error" item, like when you can't connect.

**Comment by bigretromike** [comment]
and we are about speed, we don't need ask server, retrieve information, parse version on each action :-)

**Comment by da3dsoul** [comment]
It's not going to ask about version

**Comment by bigretromike** [comment]
I will wait then as see it in action

**Comment by da3dsoul** [comment]
I'm having issues. I don't know if it's a server issue or what. We'll put this on hold for now

**Comment by bigretromike** [comment]
O-K !

**Comment by bigretromike** [comment]
I will update info in all plugins tommorow and icons, and release it then. This have been moved to another version then.

**Comment by bigretromike** [comment]
done and tested @da3dsoul ?

**Comment by da3dsoul** [comment]
I dunno. It's a pain in the ass to test, since I need to restart server and catch it in startup

**Comment by bigretromike** [comment]
so you want to handle something that you are unable to reproduce ?:alien:

**Comment by da3dsoul** [comment]
Kind of. It's just a 3 minute process to test changes

**Comment by bigretromike** [comment]
Assuming that this is done;
