### ISSUE TITLE
repository - no images/screenshot/fanarts

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#266]
Is it me or when you installing it from repo its missing icons/fanart/screenshots ?!

**Comment by da3dsoul** [comment]
Idk

**Comment by bigretromike** [comment]
You are faster than lightning

**Comment by da3dsoul** [comment]
It sends me an email and I'm usually holding my phone

**Comment by bigretromike** [comment]
fix on repo end;
