### ISSUE TITLE
View episode naming issues

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#269]
```
Bakemonogatari episodes get naming of specials (probably because same episode name)
```

**Comment by da3dsoul** [comment]
Can you provide an explicit example? Names should be correct if they are linked correctly

**Comment by bigretromike** [comment]
`Episode 5.5 (Recap)`

**Comment by da3dsoul** [comment]
I don't have that episode, with good reason

**Comment by bigretromike** [comment]
![extra](https://user-images.githubusercontent.com/6052025/45137499-30bbbf00-b1a9-11e8-93a8-ca83590fe563.png)

**Comment by bigretromike** [comment]
Looks also there is `again` issue with linking because based on file names those aren't recaps of 5.5.
![bake](https://user-images.githubusercontent.com/6052025/45137516-48934300-b1a9-11e8-8e99-c5f6fa4abeea.png)

**Comment by da3dsoul** [comment]
That is a matching error. Open desktop and look at it

**Comment by bigretromike** [comment]
Its matching error inside tvdb. 
Question is why its showing as "pinkishgrey" = User overridden when I never used linking...

**Comment by bigretromike** [comment]
Still even if those are matching errors why in EPISODES they have S before episode name, that name style is reserved by Kodi internaly for SPECIALS;

**Comment by da3dsoul** [comment]
It migrated the links from before for specials. There will likely be many like it. Most people fixed their links, but did it wrong, so I had to migrate them.
Generally, people who didn't fix their links wouldn't notice or care, hence the current situation

**Comment by da3dsoul** [comment]
S means specials

**Comment by bigretromike** [comment]
But if those are "Recommanded by Community" it suxs much... because they are wrong...

**Comment by da3dsoul** [comment]
Or do you mean season

**Comment by bigretromike** [comment]
Like you see on screenshot im in 'epsiodes' episodes should have names 01, 02.

**Comment by da3dsoul** [comment]
They aren't always recommended. If 10 people submit the same link, it's auto approved. It could still be wrong

**Comment by da3dsoul** [comment]
I can't tell if you are in Episode or Special from that screenshot

**Comment by da3dsoul** [comment]
I can tell you that it's linked properly on mine

**Comment by bigretromike** [comment]
nevermid. I removed bad tvDB linking I lost thumbs for episodes but naming is fine.

**Comment by da3dsoul** [comment]
If there are overrides that are wrong then remove them

**Comment by bigretromike** [comment]
which tvdb id you have for it ?

**Comment by da3dsoul** [comment]
Mk. The thumbnail should fix themselves later if you relink it

**Comment by da3dsoul** [comment]
102261

**Comment by bigretromike** [comment]
I updated it, how to send it so its counted toward recommended ?

**Comment by bigretromike** [comment]
OMG. Again its doing same shit. I pick 102261 and I see its ok. I preview tvdb matches and I see different tvdb link

**Comment by da3dsoul** [comment]
It's automatic. You need to override it if it's wrong

**Comment by da3dsoul** [comment]
You can't send it to web cache. Web cache is busted (half working) and we can't access the admin

**Comment by bigretromike** [comment]
No its not automatic.
there is a bug when you try to manual link things.
After few tries it work as intended while earlier linking to same broken id;

**Comment by bigretromike** [comment]
also why not rewrite webcache?! its been ages..

**Comment by da3dsoul** [comment]
I'll make you a damn video with that exact series

**Comment by bigretromike** [comment]
You dont have to I overright it with your id, and after few tries doing exactly the same shokodesktop lined it with right id, and no manualy linking episode by episode was needed;

Still, even if it was bad linking, why in Episode type folder there was S01, S02 when json was type=ep, I dont know... but maybe I will leave it that way because I wouldn't notice other way;
