### ISSUE TITLE
Mark type_dirs as watched acoring to watched mark inside 

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#270]
When you watched all episodes and dir isn't flat it should mark 'episodes' as watched

**Comment by da3dsoul** [comment]
This needs server support first

**Comment by bigretromike** [comment]
why? we have total_size with each category. 
The only thing is the local_size for category which is missing from shoko. Until then I will mark those based on shoko size. Then we can improve those.

**Comment by da3dsoul** [comment]
Don't do that. Server has a way more efficient way of marking in batches

**Comment by bigretromike** [comment]
whats more efficient way than 
```
if count_type == size_type:
    mark_as_watched(dir)
```
?

**Comment by da3dsoul** [comment]
No it's the populate a list by type, gather IDs, and Mark as Watched one by one

**Comment by bigretromike** [comment]
almost done;

**Comment by da3dsoul** [comment]
I completely misunderstood what you meant

**Comment by da3dsoul** [comment]
Nice one

**Comment by bigretromike** [comment]
Im glad you are happy with it 

On September 6, 2018 6:53:19 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>Nice one
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/270#issuecomment-419165587

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
