### ISSUE TITLE
Not every not fully watched series is in Continue Watching

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#271]
This looks like shokoserver error
While both `afro samurai` and `bakemonogatari` are not fully watched in nakamori on `All` list, they arent on `Continue Watching` 
Maybe its designed that way ? because all local episodes are watched ?

**Comment by da3dsoul** [comment]
.... Do you have the setting in Nakamori to only use local files on? That's important and affects watch states as intended

**Comment by bigretromike** [comment]
This is shoko thing. 
Filter is set by default as "Has watched Episodes" + "Has unwatched Episodes"
Those have all episodes watched so they aren't there

So I assume its intended;

**Comment by da3dsoul** [comment]
That's correct. It does not count missing files, as that would piss me off

**Comment by bigretromike** [comment]
@da3dsoul now it can piss off people when they finish watching episodes in Kodi, leave for few days, and want to watch specials. every time they will have to use search or 'all' or specialy make a new filter just to replace contiune one ;p

**Comment by bigretromike** [comment]
strange because "watched episodes" don't say directly those are also specials... but ok, then its not a problem at all. just bad description ;-)

**Comment by da3dsoul** [comment]
Specials are people...episodes, too

**Comment by bigretromike** [comment]
So filters are missing 'non-special episode only' 👍 that would be named - I will leave it for you, because you can't named them 'episodes' because that are for special+non-specials ;-)
Not like it would be easier to have `episodes` (only non-especial episodes) and `episodes and specials` (for both)

user case: watched episodes + unwatched specials = custom filter that help you find series that you downloaded specials for but didn't watch but watched series already.

**Comment by da3dsoul** [comment]
People can make their own filters

**Comment by bigretromike** [comment]
but not conditions for those filters.

**Comment by da3dsoul** [comment]
Is there not? Huh that's a problem
