### ISSUE TITLE
New Language support

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#276]
https://poeditor.com/join/project/vAOV2zSrNK

Include new language for nakamori - and credit people that did it

**Comment by bigretromike** [comment]
Few of them added: https://github.com/bigretromike/nakamori/commit/dca53bd729595be8da7d5741611b48d35ffbd38d

**Comment by bigretromike** [comment]
@Kadantte want to do Arabic ?

**Comment by Kadantte** [comment]
@bigretromike  I can help with that, But how do you know that i can do Arabic xD

**Comment by bigretromike** [comment]
I look you up 👍

**Comment by Kadantte** [comment]
Oh xD , Okay i'll beginn the work on it , i can do it here : https://poeditor.com/join/project/vAOV2zSrNK right ?!

**Comment by bigretromike** [comment]
yup. I will update original file with few strings in few minutes - just saying ;-)

**Comment by bigretromike** [comment]
I updated it, fell free to work on them

**Comment by bigretromike** [comment]
I move to different platform, this is more mature and works better for all the extra things we have:
https://www.transifex.com/nakamori/nakamori/

**Comment by bigretromike** [comment]
@da3dsoul this one respects comments

**Comment by da3dsoul** [comment]
Woot

**Comment by bigretromike** [comment]
just hop in and check it out, you should have a invitation already on your g account

**Comment by da3dsoul** [comment]
Yep

**Comment by bigretromike** [comment]
Closing this.
