### ISSUE TITLE
POEditor? You completely ruined the resource file

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#283]
I completely reorganized the strings.po by hand before, more intelligently, with room to add more in various RELEVANT SECTIONS. Now what? It's a big, mostly unorganized list that will throw off the numbering any time we want to add something new, and more importantly, it's ugly.

</rant>

**Comment by da3dsoul** [comment]
Plus, I don't have access to this poeditor.com account, which I assume you made

**Comment by bigretromike** [comment]
You made yours

On September 27, 2018 3:01:20 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>Plus, I don't have access to this poeditor.com account, which I assume
>you made
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/283#issuecomment-425081629

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
What?

**Comment by bigretromike** [comment]
Make your account there.  Whats the problem. Also no muh was moved. And all the comments are made by hand anyway. 

On September 27, 2018 3:46:44 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>What?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/283#issuecomment-425098802

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
I am just upset because I made the file look nice with nothing but a text editor, and an automated system completely wiped it with no visible benefits. It's not hard to auto-translate those without such a thing. The only reason that I didn't immediately revert the changes is because I noticed too late.

Legitimately, a simple [google search](https://www.google.com/search?q=gnu+gettext+translator&oq=gnu+gettext+translator) yielded plenty of results.

**Comment by bigretromike** [comment]
I message you few times on discord about it. Revert is as you like but make it accessible for people out side github.

On September 27, 2018 3:52:23 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>I am just upset because I made the file look nice with nothing but a
>text editor, and an automated system completely wiped it with no
>visible benefits. It's not hard to auto-translate those without such a
>thing. The only reason that I didn't immediately revert the changes is
>because I noticed too late.
>
>Legitimately, a simple [google
>search](https://www.google.com/search?q=gnu+gettext+translator&oq=gnu+gettext+translator)
>yielded plenty of results.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/283#issuecomment-425100830

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
It'll be too much effort now. I might go do it eventually, but I won't do it for a while.

**Comment by bigretromike** [comment]
Im filling the numering gaps so you need to add string on bottom.  Alot missing but it progress. I didn't want to move them around so poeditor wouldn't marked them as untranslated. Few people helped with translation and its IMO more than I asked. If that mean to sacrifise comments that aint in standard then to bad 

On September 27, 2018 3:55:57 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>It'll be too much effort now. I might go do it eventually, but I won't
>do it for a while.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/283#issuecomment-425102072

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
..... What? Why would you do that? The gaps are there for a reason. As mentioned, when adding new strings, they should be next to the relevant ones. I specifically left gaps so that we don't need to try to figure out what the last number was. We simply increment the number, and in most cases it'll be fine unless the project gets so big that my numbering didn't have enough space.
If that happens, then realistically, we should be packaging our own localization solution rather than using Kodi's half assed gnu gettext implementation.

**Comment by bigretromike** [comment]
If gaps are your concern then we can only import English file but never export it. That way you can break English file and rest will have more standard file 

On September 27, 2018 4:18:47 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>..... What? Why would you do that? The gaps are there for a reason. As
>mentioned, when adding new strings, they should be next to the relevant
>ones. I specifically left gaps so that we don't need to try to figure
>out what the last number was. We simply increment the number, and in
>most cases it'll be fine unless the project gets so big that my
>numbering didn't have enough space.
>If that happens, then realistically, we should be packaging our own
>localization solution rather than using Kodi's half assed gnu gettext
>implementation.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/283#issuecomment-425110219

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
Here is a link to join it: https://poeditor.com/join/project/vAOV2zSrNK

**Comment by bigretromike** [comment]
Make account and I can add you as project admin there.
