### ISSUE TITLE
Player not allways registrating onPlayBackStopped

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#286]
```
---------------------------- first file
16:41:18.824 T:5804  NOTICE: CVideoPlayer::CloseFile()
16:41:18.824 T:5804  NOTICE: VideoPlayer: waiting for threads to exit
16:41:18.828 T:6748  NOTICE: CVideoPlayer::OnExit()
16:41:18.828 T:6748  NOTICE: Closing stream player 1
16:41:18.828 T:6748  NOTICE: Waiting for audio thread to exit
16:41:18.835 T:4948  NOTICE: thread end: CVideoPlayerAudio::OnExit()
16:41:18.835 T:6748  NOTICE: Closing audio device
16:41:18.886 T:6748  NOTICE: Deleting audio codec
16:41:18.886 T:6748  NOTICE: Closing stream player 2
16:41:18.886 T:6748  NOTICE: waiting for video thread to exit
16:41:18.896 T:6272  NOTICE: thread end: video_thread
16:41:18.900 T:6748  NOTICE: deleting video codec
16:41:18.936 T:6748  NOTICE: DXVA::CDecoder::Close - closing decoder
16:41:18.936 T:6748  NOTICE: DXVA::Close - closing decoder context
16:41:18.938 T:5804  NOTICE: VideoPlayer: finished waiting
16:41:18.998 T:6752  NOTICE: -> nakamori.player::onPlayBackStopped <---------------
16:41:18.998 T:6752  NOTICE: -> nakamori.player::onPlayBackEnded <---------------
16:41:18.998 T:6752  NOTICE: -> nakamori.player::mark = 0.75 * total = 1438 = 1078.5 < current = 1325.31604004 <---------------
16:41:19.567 T:5804  NOTICE: CVideoPlayer::CloseFile()
16:41:19.567 T:5804  NOTICE: VideoPlayer: waiting for threads to exit
16:41:19.567 T:5804  NOTICE: VideoPlayer: finished waiting
16:41:19.567 T:5804  NOTICE: CVideoPlayer::CloseFile()
16:41:19.567 T:5804  NOTICE: VideoPlayer: waiting for threads to exit
16:41:19.567 T:5804  NOTICE: VideoPlayer: finished waiting
16:41:19.732 T:6296  NOTICE: -> nakamori.player::sync_thread: not playing anything

---------------------------- second file
17:01:58.580 T:5804  NOTICE: CVideoPlayer::CloseFile()
17:01:58.580 T:5804  NOTICE: VideoPlayer: waiting for threads to exit
17:01:58.584 T:1340  NOTICE: CVideoPlayer::OnExit()
17:01:58.584 T:1340  NOTICE: Closing stream player 1
17:01:58.584 T:1340  NOTICE: Waiting for audio thread to exit
17:01:58.585 T:1872  NOTICE: thread end: CVideoPlayerAudio::OnExit()
17:01:58.585 T:1340  NOTICE: Closing audio device
17:01:58.636 T:1340  NOTICE: Deleting audio codec
17:01:58.636 T:1340  NOTICE: Closing stream player 2
17:01:58.636 T:1340  NOTICE: waiting for video thread to exit
17:01:58.652 T:6608  NOTICE: thread end: video_thread
17:01:58.652 T:1340  NOTICE: deleting video codec
17:01:58.657 T:1340  NOTICE: DXVA::CDecoder::Close - closing decoder
17:01:58.657 T:1340  NOTICE: DXVA::Close - closing decoder context
17:01:58.659 T:5804  NOTICE: VideoPlayer: finished waiting
17:01:59.171 T:2052  NOTICE: -> nakamori.player::sync_thread: not playing anything <---------------
17:01:59.293 T:5804  NOTICE: CVideoPlayer::CloseFile()
17:01:59.293 T:5804  NOTICE: VideoPlayer: waiting for threads to exit
17:01:59.293 T:5804  NOTICE: VideoPlayer: finished waiting
17:01:59.293 T:5804  NOTICE: CVideoPlayer::CloseFile()
17:01:59.293 T:5804  NOTICE: VideoPlayer: waiting for threads to exit
17:01:59.293 T:5804  NOTICE: VideoPlayer: finished waiting
17:02:02.402 T:5508  NOTICE: -> nakamori.player::trakt_thread: not playing anything
```

I was thinking that this is an issue with calculating did_I_watch_mark, but it looks like onPlayBackStopped don't always being executed - what makes did_i_watch_mark being skipped. 
This way episode isin't marked as watched even if it should.

**Comment by da3dsoul** [comment]
I have noticed this, but couldn't figure out why

**Comment by bigretromike** [comment]
player and plugin updated; need confirmation;

**Comment by da3dsoul** [comment]
I'll test it now. I have something that seems to reliably not work

**Comment by bigretromike** [comment]
oh, thats cool because its to random for me. I just put watch mark on `1` its like 14-17seconds in episode and I randomly hit STOP and observe. I could understand from forum-issues that its because player is killed before onPlayBackStopped trigger. And with this we wait till onPlayBackStopped switch playingStatus, and then we allow to exit - and kill all threads made in player.

**Comment by da3dsoul** [comment]
I've noticed it happens more if you let a shorter episode finish. For example Dagashi Kashi S2 has 12 minute episodes and it doesn't seem to ever mark

**Comment by da3dsoul** [comment]
Also no it's not fixed

**Comment by bigretromike** [comment]
just before I dig more, You replace both Player and Plugin

**Comment by da3dsoul** [comment]
Yes

**Comment by bigretromike** [comment]
also you test with seeking or without

**Comment by da3dsoul** [comment]
without

**Comment by bigretromike** [comment]
I tested this with full close Kodi, and for 5 episodes it was all ok. I have mix results when changing something and not deleting *.pyo files manualy or restarting kodi. but probably my sample size was to small. Maybe you will have luck with it

**Comment by bigretromike** [comment]
@da3dsoul Is it fine now, been watching 20+ episodes and all of them worked fine - but I'm still want to know if this is fixed.

**Comment by bigretromike** [comment]
@da3dsoul not a single file failed me after this patch. You still having issues ?

**Comment by da3dsoul** [comment]
I haven't tested the ones that failed for me

**Comment by da3dsoul** [comment]
I can verify that it is not fixed

**Comment by da3dsoul** [comment]
It consistently does not work for short anime (3-15 minutes)

**Comment by bigretromike** [comment]
Will see. Did you try with delay for player option?  So anything 3min should not work you say

On October 9, 2018 3:10:04 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>I can verify that it is not fixed
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/286#issuecomment-428185348

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
Nope no delay and resume works, it just doesn't mark as watched

**Comment by bigretromike** [comment]
I found the problem .. fixing being tested and checking documentation for it.

**Comment by bigretromike** [comment]
the issue that left, was for anything short. Now its all ok. 
If its not, reopen.

**Comment by da3dsoul** [comment]
I'm at the point where I think I still have it, but I can't guarantee that it's from the newer versions, so I'm waiting

**Comment by da3dsoul** [comment]
Okay, I have had it happen again. My first theory is that it's a rare situation when playing through the end of the file. My second theory is that it's from seeking into the end of the episode.

**Comment by bigretromike** [comment]
Please include log.

On October 16, 2018 8:36:23 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>Okay, I have had it happen again. My first theory is that it's a rare
>situation when playing through the end of the file. My second theory is
>that it's from seeking into the end of the episode.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/286#issuecomment-430348682

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
Don't have one! If I can reliably reproduce it, then I'll post one

**Comment by da3dsoul** [comment]
I've thought of a third possibility that I will investigate: 80% isn't low enough for some series when skipping the ending

**Comment by bigretromike** [comment]
I updated default long ago, 80 and its 75 by default 😃

On October 16, 2018 11:07:52 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>I've thought of a third possibility that I will investigate: 80% isn't
>low enough for some series when skipping the ending
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/286#issuecomment-430401328

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
My config is old

**Comment by bigretromike** [comment]
by looking in logs you can see that x% is ok or not :-) that why I asked for log. there is still a debug line there to show the calculation btw. Maybe if kodi will have opening/ending detection that they announce for that coding fest... soon™

**Comment by bigretromike** [comment]
So it was because the % value was to high from what I read.
