### ISSUE TITLE
always vote for unsorted

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#289]
Should be off until watch/file ,

**Comment by da3dsoul** [comment]
Should be always off. Votes are stored per episode and series.

Watched states are per file, so it's plausible for them.

**Comment by bigretromike** [comment]
Until watch/file is not a thing, Im disabling it for unsort files;

**Comment by da3dsoul** [comment]
That's fine, my point was that there's not a use case even when we get file/watch
