### ISSUE TITLE
wrong watch 'icon' in series list

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#290]
Series have 12/12 but still its marked as half watched.
No specials.

`short -> Bikini Warriors` - reference point.

**Comment by da3dsoul** [comment]
Log spam

**Comment by da3dsoul** [comment]
Find out what the json response, specifically 'sizes' says

**Comment by bigretromike** [comment]
I know 😃 I wrote this one so I wont forget about this 

On October 18, 2018 10:58:02 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>Find out what the json response, specifically 'sizes' says
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/290#issuecomment-431158517

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
Fair.....

**Comment by bigretromike** [comment]
ok, I'm using different settings on both testing machines.
one is using server size other use local - where In local I don't have specials so its ignore them.

But I notice Im missing some stats info :-) which is a good thing
