### ISSUE TITLE
Issues with rewrited code

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#294]
List of issues there are currently:
- tested on kodi18+python3
- [x] on clean install the wizard dialog (yes,no) is covered with script menu (script menu shouldn't launch here)
- [x] when picking YES from wizard script menu is launched, not the wizard
- [ ] calendar not working (it works fine from script, but not from plugin)
- [x] menu not working
- [x]  WARNING: CAddonSettings[plugin.video.nakamori]: cannot reference separator setting in old setting condition "eq(-2,true)" for "expireCache" WARNING: CAddonSettings[plugin.video.nakamori]: failed to parse visible condition "eq(-3,true)+eq(-2,true)" of old setting definition for "expireCache"
- [ ] settings.xml lsep visible all the time, confirmed as kodi but: https://forum.kodi.tv/showthread.php?tid=340786
- [x] When entering Information about plugin the `Configure` is disabled (kodi bug?)
- [x] Suppress "Whats new" when installed and not configured - not issue, because its new but still :-)

**Comment by bigretromike** [comment]
menu not working - was issue of using not updated lib;

**Comment by bigretromike** [comment]
WARNING fixed: https://github.com/bigretromike/nakamori.plugin/commit/c063b4d725cdd92a1a59baf1e5ad5a6ba8fb0a65

**Comment by da3dsoul** [comment]
KK. I've not looked at the calendar...

**Comment by da3dsoul** [comment]
Calendar works

**Comment by da3dsoul** [comment]
@bigretromike I suggest making a separate issue or putting the settings issue in the Leia changes issue

**Comment by bigretromike** [comment]
hmmm... I dont know if something broke because me, or with latest commits but when you use latest masters of each plugin/script calendar still dont work from video.plugin.
And I don't see anywhere were was the fix @da3dsoul you did 5 days ago :-)

So I will reopen this one

**Comment by da3dsoul** [comment]
I didn't make a fix. It just works for me

**Comment by bigretromike** [comment]
with every plugin using master?
if so then its kodi18 (or kodi18python3) bug

**Comment by da3dsoul** [comment]
Yeah, it's possible

**Comment by bigretromike** [comment]
Kodi18.x bug (?! not yet confirmed, or something so small change that I don't see it when comparing wizard.xml with calendar.xml) https://forum.kodi.tv/showthread.php?tid=340550

**Comment by bigretromike** [comment]
Wizard from inside "settings" also stop working ...

**Comment by da3dsoul** [comment]
Ah that definitely sounds like Kodi 18 issue, then

**Comment by bigretromike** [comment]
so this is not rewrite fault, moving this out from here.
