### ISSUE TITLE
Recommended Pycharm Plugins to Improve Workflow

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#296]
.ignore : GitIgnore Support
autodoc : helps with documenting types
CodeGlance : A scrolling helper
GapStyle : Color Scheme
GitScope : Some Git tools, helps for submodules
Python Enhancements : Python Code Help and stuff
Rainbow Brackets : Bracket coloring to help with determining scopes
SonarLint : Lots of stuff. This needs more looking into. I plan on contacting them, as they provide better stuff for open source projects.

**Comment by da3dsoul** [comment]
@bigretromike go to sonarcloud.io and make an account and link it to your github. Then I can add you as an admin to https://sonarcloud.io/dashboard?id=nakamori
from there, we can make you a token, and you can set it up. It gives a lot of tips on python stuff

**Comment by bigretromike** [comment]
done.
