### ISSUE TITLE
Rewrite/Redesign the Setup Wizard

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#298]
The wizard was a great idea, and it isn't necessarily poorly designed. It doesn't work great a lot of the time, though...and it sometimes reacts poorly by having not much difference between connection error and login error.
My thoughts are this:
T -> True/Test Succeeded
F -> False/Failed
1. Connection Test
1T. Move on
1F. Display a message that we could not connect, then show the connection dialog
2. Check Server Startup State
2T. Move on
2F. Wait and show a properly cancelable Progress Dialog (It won't show a progress bar, just the current state)
3. Check for valid apikey
3T. Move on
3F. Show Login Dialog

In the settings (possibly a main menu item as well), have a Log Out button instead of the ambiguous User and Password that are blank.

**Comment by bigretromike** [comment]
They are empty because you can set those if something is wrong but 3step check will be better, but what will happend when you change those on shoko, you don't have connection?

On March 12, 2019 7:24:02 PM GMT+01:00, da3dsoul <notifications@github.com> wrote:
>The wizard was a great idea, and it isn't necessarily poorly designed.
>It doesn't work great a lot of the time, though...and it sometimes
>reacts poorly by having not much difference between connection error
>and login error.
>My thoughts are this:
>T -> True/Test Succeeded
>F -> False/Failed
>1. Connection Test
>1T. Move on
>1F. Display a message that we could not connect, then show the
>connection dialog
>2. Check Server Startup State
>2T. Move on
>2F. Wait and show a properly cancelable Progress Dialog (It won't show
>a progress bar, just the current state)
>3. Check for valid apikey
>3T. Move on
>3F. Show Login Dialog
>
>In the settings (possibly a main menu item as well), have a Log Out
>button instead of the ambiguous User and Password that are blank.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/298

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
In that case, 1 will succeed and 3 will fail.

**Comment by bigretromike** [comment]
- [ ] "Cannot connect to Shook Server. Please check your ip settings" is curent behavior for not connecting to ip. We leaving this, or changing to dialog yes/no to run wizard ?

**Comment by bigretromike** [comment]
- [ ] changing ip in settings, having user/password correct prevent from connecting to server, apikey is empty, good_ip, good_port are empty.

**Comment by da3dsoul** [comment]
I'll take care of it. I'm redoing the flow of the wizard, but atm it's just a stub with an error

**Comment by da3dsoul** [comment]
It can use a bit of testing and cleanup for more edge cases, I'm sure, but done
