### ISSUE TITLE
Drop the .lib, .service, etc labels.

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#299]
The tags that state what part of the project an issue pertains to are unnecessary.
They are useful when the project is really big, but we just don't need them. We have two developers, and we both know basically the whole code base (you may not atm since rewrite, but that'll change).

I figured I'd make this to get your input before I just nuke them without asking.

**Comment by bigretromike** [comment]
Which tags you want to drop? 

On March 12, 2019 7:29:18 PM GMT+01:00, da3dsoul <notifications@github.com> wrote:
>The tags that state what part of the project an issue pertains to are
>unnecessary.
>They are useful when the project is really big, but we just don't need
>them. We have two developers, and we both know basically the whole code
>base (you may not atm since rewrite, but that'll change).
>
>I figured I'd make this to get your input before I just nuke them
>without asking.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/299

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
.lib
.player
.plugin
.resource
.script
.service

**Comment by bigretromike** [comment]
You ask for most of them and now you want to merge it? LUL 

On March 12, 2019 7:49:46 PM GMT+01:00, da3dsoul <notifications@github.com> wrote:
>.lib
>.player
>.plugin
>.resource
>.script
>.service
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/299#issuecomment-472134247

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
Nah you added those ones. It's just the issue labels that I want to drop, not the submodules.

**Comment by bigretromike** [comment]
Oh, it make it easier if something broke in single module but if you want drop them sure but if they start be needing them I will readd the anyway

On March 12, 2019 7:55:40 PM GMT+01:00, da3dsoul <notifications@github.com> wrote:
>Nah you added those ones. It's just the issue labels that I want to
>drop, not the submodules.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/299#issuecomment-472136359

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
Fair. It just makes the issue list so colorful that it's distracting. That's even worse when we don't actually read the labels.

**Comment by bigretromike** [comment]
True, true. 

On March 12, 2019 7:59:24 PM GMT+01:00, da3dsoul <notifications@github.com> wrote:
>Fair. It just makes the issue list so colorful that it's distracting.
>That's even worse when we don't actually read the labels.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/299#issuecomment-472137671

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
