### ISSUE TITLE
Better Localization Library (kind of)

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#300]
I'll need to write this myself, and I'll probably add it to the main repo if I can.

The Kodi localization system is a version of the [gettext standard](https://en.wikipedia.org/wiki/Gettext).

There is nothing wrong with it implicitly. What is wrong is that we need to keep everything in a single po file and refer to it by an integer ID which may conflict with Kodi or other addons if we aren't careful.

There is no reason to be bound by that. We should just be able to do things like:
```
import gettext
lang_path = os.path.combine(plugin_path, 'resources', 'language')
e_t = gettext.translation('errors', lang_path)
_e = e_t.gettext
n_t = gettext.translation('notifications', lang_path)
_n = n_t.gettext

error(_e('no_connection'))
notification(_n('marked_as_watched))
```
and have that handle the language BS for us. The best part about this is that it still takes exactly the same format we have. We'd just need to change the IDs to things that make sense and split them up into files that relate to what the purpose is.

**Comment by da3dsoul** [comment]
Due to the settings being handled by Kodi, unless we make our own settings dialog, the settings file will still use Kodi's method for localization. If we know that strings.po is settings, then that's not so bad.

**Comment by bigretromike** [comment]
Localization is fine, why you want to do this?  Check wiki for what range is allowed for addons, also with Same ID there is no issue for two different addons, they read lang file from addon dir, only the translations using kodi reserved IDs are ignored. Whats wrong with it now?

On March 14, 2019 11:58:55 PM GMT+01:00, da3dsoul <notifications@github.com> wrote:
>I'll need to write this myself, and I'll probably add it to the main
>repo if I can.
>
>The Kodi localization system is a version of the [gettext
>standard](https://en.wikipedia.org/wiki/Gettext).
>
>There is nothing wrong with it implicitly. What is wrong is that we
>need to keep everything in a single po file and refer to it by an
>integer ID which may conflict with Kodi or other addons if we aren't
>careful.
>
>There is no reason to be bound by that. We should just be able to do
>things like:
>```
>import gettext
>lang_path = os.path.combine(plugin_path, 'resources', 'language')
>e_t = gettext.translation('errors', lang_path)
>_e = e_t.gettext
>n_t = gettext.translation('notifications', lang_path)
>_n = n_t.gettext
>
>error(_e('no_connection'))
>notification(_n('marked_as_watched))
>```
>and have that handle the language BS for us. The best part about this
>is that it still takes exactly the same format we have. We'd just need
>to change the IDs to things that make sense and split them up into
>files that relate to what the purpose is.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/300

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
I don't like it! That's mainly it. My main issue with it is that we currently have strings split stupidly between addons with numbers that makes no sense, and every time I want to localize something, I need to go find an empty ID, write it up, modify it inevitably, add more, make it even less organized, then forget all of the IDs.

Why shouldn't we use Kodi's? Because there is never a good reason to refer to something by a number if you can refer it to it by a name...unless it is a number, but these are not numbers. They are text.

**Comment by da3dsoul** [comment]
It doesn't help that what tool you use wipes any attempt at trying to organize.

**Comment by bigretromike** [comment]
And I will still used translation related tools, I wont be manage translation by hand, also when you are done with rewrite base you wont ever need to look on old ID's and I can manually scan which ID are empty if you ever need one. 

Also if you want to organize it we wont be able to reuse ID's like we can because string being in 3 places would have to be in 3 section, or if you refer to organizing it by comment then I can find translation software that wont wipe comments if thats all you want.

I would prefer to stick with official way to use translation. If you are so mad on those ID's just write plugin for PyCharm that translate those to names from .po file. ^_^

**Comment by da3dsoul** [comment]
...I really should, though.

**Comment by da3dsoul** [comment]
It just bothers me to have a single file with a list of 200 strings that I can't easily search.

**Comment by bigretromike** [comment]
```
     strings 30000 thru 30999 reserved for plugins and plugin settings
    strings 31000 thru 31999 reserved for skins
    strings 32000 thru 32999 reserved for scripts
    strings 33000 thru 33999 reserved for common strings used in add-ons
```

**Comment by da3dsoul** [comment]
What if 3000 isn't enough!? Clearly we should go for my plan

**Comment by bigretromike** [comment]
also by guidence we should use same simple translation like 'save', 'ok', 'cancel' from kodi's language file instead of adding it to ours, but no one does that and 1000 strings per addon is imo enuoght. 
Especially when you have 1000 for lib, 1000 for script, 1000 for service, 1000 for plugin. Those can overlaps with ID's. 
Also if 1000 wont be enough we will think about your idea, for now its overthinking.

**Comment by bigretromike** [comment]
worst case scenario (which won't happened) is hard code English - by then the project would be as big as Shoko itself, I wouldn't be even mad - but until then 1000 will be enough

**Comment by da3dsoul** [comment]
Hard code English! You said it not me! Let's do it!

**Comment by bigretromike** [comment]
If nakamori get THAT big that we will be needing this, it will be here waiting.
Been long enough to close this for now.
