### ISSUE TITLE
Use Protobuf

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#304]
JSON is slow, especially in Python. Protobuf is fast. This is not going to work for getting data from Shoko yet, but it is planned.

Where this can really shine even before Shoko implements it is in the cache. If we use protobuf to query the persistent cache, then we can speed it up even more, as most of the time that we will spend retrieving data will be serializing and deserializing json.

**Comment by da3dsoul** [comment]
https://github.com/WoLpH/kodi-protobuf

**Comment by bigretromike** [comment]
Just a reminder, if its not in official kodi repo don't force it.

I see that this one is, even if its 3 years old, while the official repo is getting update - but its a reminder.

**Comment by da3dsoul** [comment]
Well, no. That was just something I found to aid in the search if needed. I didn't look far into it, but that build script is crazy. You legit run it, it pip installs it, zips up the installation, and copies it.

**Comment by bigretromike** [comment]
> 
> 
> Well, no. That was just something I found to aid in the search if needed. I didn't look far into it, but that build script is crazy. You legit run it, it pip installs it, zips up the installation, and copies it.

Something like that is legit for Kodi script ? strange because if that was a standard we wouldn't have to deal with outdated PILLOW

**Comment by da3dsoul** [comment]
That's the build script. It doesn't run it in Kodi, but on the dev's machine to package it

**Comment by bigretromike** [comment]
looks like script.module.protobuf3 is not very popular libs, if you want to try and use it any benchmark data would be cool 👍 before adding a chain of dependency

**Comment by bigretromike** [comment]
https://github.com/WoLpH/kodi-protobuf have been abandon for 3 years now.
While upstream https://github.com/protocolbuffers/protobuf is very active.
Its not even ported to v18, not even saying v19py3. 

As much I would love to dive into new technology, the time to port this by ourself to kodi and implement it in Shoko is not worth the 'speed' which is for now a speculation/theory.

This can be reopen if we ever go back to this conversation.
