### ISSUE TITLE
More Windows and Features from Shoko (that are already possible)

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#305]
- [x] /rehashunlinked -> Rehash All in Unrecognized
- [x] /rescanunlinked -> Rescan All in Unrecognized

Proper import folder viewing, adding, editing, etc
- [x] /folder/list -> duh list them
- [ ] /folder/add [POST] -> add one, this will require more work, especially if the client is linux
- [ ] /folder/edit [POST] -> edit, same as above
- [ ] /folder/delete [POST] -> we need to be careful with this

- [ ] /folder/import -> Run Import (folder/scan is included in this, so it's unnecessary)

Generally not needed, but we shall include it anyway
- [ ] /stats_update -> Update All Stats

Proper Queue State
- [x] /queue/get -> Get all queues' states
hash, general, images -> the queues for the below
- [x] /queue/{type}/pause -> pause a queue
- [x] /queue/{type}/start -> unpause a queue
- [x] /queue/{type}/clear -> clear a queue (need to give warning that invalid states may occur)

Bookmarked Series
- [x] /serie/bookmark -> Get bookmarked series
- [x] /serie/bookmark/add?id=ID -> Add a bookmark
- [x] /serie/bookmark/remove?id=ID -> Remove a bookmark

Related to #273, but all of this is possible now with no new API, while most of the stuff in there needs new API.

**Comment by bigretromike** [comment]
updated to reflect 3.4.0
