### ISSUE TITLE
Nakamori as video library source

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#306]
This is very possible, this is something quite new, and no-one did it before.

https://github.com/xbmc/xbmc/pull/13566
https://github.com/xbmc/xbmc/pull/14210

I did somehow be able to make it work once, and then after cleaning library it broken - from last 8h I spend on this it looks like Library is buggy (and when cached something and remove it it still hold something for it, that would explain why it was working all the time until I wipe Library.db), like when you add something and it does scan, after many attempts and edits its start to throw errors like the path is not there. And I was hoping to make it without initially announcing it - but looks like I'm just a human.

When It did worked and added series it worked very well - with exception of missing few infos. 

I came to conclusion that with all those custom object its utterly hared to do anything like this for me - and without proper IDE most of the time. 

Currently its skips all the `Series`, the only thing is does scan are those extra menus if you add them to `tvshow` path. Which is strange. 

I can be probably something trivial that I don't see, so fell free if you have spare time @da3dsoul to mess with this, as for now its not working.

I understand the cons of using nakamori as `video source` but I also see the potential and benefits for supporting this - this is far superior than any scraper for Shoko could be.

easy and dirty instruction is to add video source as `plugin://plugin.video.nakamori/tvshows/<apikey>/`, pick `TV shows` and `Local information only` in `Set Content`, double check if `Selected folder contains a single TV show` is uncheck and hit ok.

**Comment by bigretromike** [comment]
I would be glad if @AkariDN had a time to look it up, as he is the author of those awesome commits about this.

**Comment by da3dsoul** [comment]
Well, following general Kodi and development guidelines. Please attach a debug log of Kodi when trying to do this.

Can you make a new repo plugin.videosource.nakamori? I don't know if there's a convention yet, but that sounds decent. We can move it into a new plugin so it's easy to enable and disable, as well as having its code unique to it, rather than plugin, which provides menus.

**Comment by bigretromike** [comment]
You suppost to make seperate path in video plugin 😃 not seperate plugin 

On April 5, 2019 3:25:38 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>Well, following general Kodi and development guidelines. Please attach
>a debug log of Kodi when trying to do this.
>
>Can you make a new repo plugin.videosource.nakamori? I don't know if
>there's a convention yet, but that sounds decent. We can move it into a
>new plugin so it's easy to enable and disable, as well as having its
>code unique to it, rather than plugin, which provides menus.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/306#issuecomment-480274304

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
Then how do you turn it off?

**Comment by da3dsoul** [comment]
Not everyone wants 45000 anime episodes in their collection of American Cartoons from the early 2000s

**Comment by bigretromike** [comment]
You remove video source from library 

On April 5, 2019 3:47:00 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>Then how do you turn it off?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/306#issuecomment-480281401

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
If you never used library in kodi there are screenshots in first commit in first post 

On April 5, 2019 3:48:15 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>Not everyone wants 45000 anime episodes in their collection of American
>Cartoons from the early 2000s
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/306#issuecomment-480281830

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
Ah I see.

**Comment by da3dsoul** [comment]
oh....I need a nightly haha

**Comment by da3dsoul** [comment]
I see one issue right off the bat. I'll see if I can get it working nicely.

**Comment by da3dsoul** [comment]
@bigretromike don't feel bad. You found a bug...

@AkariDN The way to reproduce this issue (on latest nightly, 4/4/2019) is to make a URL pattern, for example `plugin://plugin.video.nakamori/tvshows/12/ep/4`, change it to something else, ex `plugin://plugin.video.nakamori/tvshows/series/12/ep/4`. When you enter the plugin, even from the Files menu, then it goes to the correct new URL. If you try to scan it, then it uses the old one, no matter what the code says. I'm looking into the db3 files next to see if I can find it.

**Comment by da3dsoul** [comment]
[kodi.log](https://github.com/bigretromike/nakamori/files/3049399/kodi.log)
Here's a debug log. It doesn't say anything helpful, though...

**Comment by da3dsoul** [comment]
I'm having trouble getting anything to show up. If I enter the menus, then they all appear as expected, but the scan returns nothing.

**Comment by bigretromike** [comment]
I see you manage to find more than I did. The fun part is that if you type source as `plugin://plugin.video.nakamori/` and you scan it you can see in top right cornet that it iterate over `Search, Continue watching, etc` (and see that search box apears, info box etc) its funny because I used filter_id=1 which gave me `Continue watching` and when it worked it did iterate over series and in right top corner there was full names of those series and later they would be added. 

Later I was thinking that maybe `/tvshow/` path in addon.xml is limiting it because it would enter `tshows` list items as url=`/menu/series/<id>` but from time to time when I change the code like chaning DirectoryList or ListItem to native xbmc object, or when I added other menus there I would see that it does enter into those episodes and most of the time hit `/episode/types`. 

Funny how it work that one time because it was broken

The only thing you need to remember (but it looks like you know more than I did in 3 days) that when you use it a source for library it wont and CAN'T access settings - thats why some logic dont work.

The original idea was that I would anchor it on `/tvshows/` that would list all items from `All` and it would flat the types and show only episodes and special. Funny enough when I did work it worked quite well it automaticly made Seasons for JoJo, proper naming etc....

But with the clue you found out about Library bugged not using url that would make sense because when I added it first I did change url many times, also I don't know if it should work on scaning for new content (from context menu) or it should be only tested from removing item, cleaning library, source.xml and then reading because other way it remembers settings etc.

I knew you will dig more in few hours than I did in few days, and it frustrating that we are 'thiiiis' close to solve it.

Hope its not another bug like the plugin_routing had.... ^_^

**Comment by bigretromike** [comment]
Before I would add tones of `xbmc.log()` in every path that I would think it goes and see in log where did he scan those files. Thats a good indicator what those it see.

And It does see each extra_menu from add_extra_menu (calendar, search, experiment) but refuse to see series which are kodi_models.ListItems inside DirectoryList. Thats why I wanted dump those, to compare because that could be something with that.

The last this is that I did try once (before it worked) with `li.setProperty('get_stream_details_from_player', 'true')` dunno if that helped or not, because I removed it later - but maybe it did (maybe its a clue).

But with the way Library is bugged the best way to test would be each time wipe clean kodi library and settings.... which would take ages.. or use container hahaha...

I'm just wishing that somehow we (You) manage to overcome this bug, because that would make a Nakamori even more useful.

Oh, the last thing I remember when It used to work, was that files wouldn't worked but I was thinking it was because lack of settings (because items added to library dont have settings), other than that I could list them by Title, Year, etc. Oh and I had issue with marking them as played that's why I was tweaking with `countplay` and later with `studio`. 

The last time it worked was when I added the `xbmc.log()` to your error handler class. And it worked because each time I 'scanned' source it would throw those errors that '3' is not in empty list. But acording to what you wrote and what I tested It was long gone broken and yet Library worked because it was using old cached data, and would iterate over Library items and not the one from plugin.

**Comment by da3dsoul** [comment]
That might help, actually

**Comment by da3dsoul** [comment]
I think I got it. You can't map more than one episode to a single one by the numbers.

**Comment by da3dsoul** [comment]
Stream info doesn't appear to be working, but that may be because I forgot to add it...IDK I've been trying a lot.

**Comment by da3dsoul** [comment]
Fixed the stream info and cleaned it up. All that's left is checking for existence (cleaning DB) and maybe that hash thing.

**Comment by da3dsoul** [comment]
Psh long term. How about now?

**Comment by da3dsoul** [comment]
Okay, movies don't work at all. I'm working on extendedinfoscript quirks, but it's kind of working.

**Comment by da3dsoul** [comment]
A way to improve it would be to get all images from the API, rather than the random ones we would get for the plugin menus.

**Comment by bigretromike** [comment]
I don't belive 

On April 6, 2019 1:54:45 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>I think I got it. You can't map more than one episode to a single one
>by the numbers.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/306#issuecomment-480498139

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
OMG will try it in 1-2 h

On April 6, 2019 2:32:03 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>Psh long term. How about now?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/306#issuecomment-480500419

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
That can be done with small API edit right now 

On April 6, 2019 4:03:22 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>A way to improve it would be to get all images from the API, rather
>than the random ones we would get for the plugin menus.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/306#issuecomment-480506605

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
A small API edit and changing the art to lists

**Comment by bigretromike** [comment]
it was a list before (when I did it) but with only one element :+1:

**Comment by AkariDN** [comment]
Due to Kodi's plugin URL parenting rules if you want to support both movies and tvshows you must use "key=value"-style URLs and two nodes for scanner e.g.:
```
plugin://plugin.video.nakamori/tvshows/?tvshow_id=12&episode=4 - for tvshows
plugin://plugin.video.nakamori/movies/?movie_id=123 - for movies
```
That is why special hardcoded Kodi action parameters ("kodi_action=refresh_info|check_exists") passed as "key=value" too. Other URLs (for normal plugin operations) can be any style.

"get_stream_details_from_player" property do not need anymore - last Kodi builds always update stream details from video player.

For "kodi_action=check_exists" setResolvedUrl is used only to pass result (True/False) to Kodi, returned ListItem is ignored.

**Comment by bigretromike** [comment]
Looks like @da3dsoul figure out why my code didn't worked, but if you already here @AkariDN I would like to thank you for this beautiful functionality in Kodi, without it I would have to make a python scraper that wouldn't even work as good as this approach.

We ain't still in official Kodi repo, but from searching github I couldn't find anything related to `plugin as a source` thing. Hope we will see your work (as you mention it before in PR) soon so we can both check out how it should be done

**Comment by da3dsoul** [comment]
@AkariDN, thanks I had that figured out for movies. The reason that movies fail for us is that we follow AniDB's listing for movies, which isn't a 1-1 mapping of file/episode to movie. An example is Kizumonogatari is all in one "series" with each "Episode" being a part of it. On MovieDB and otherwise, that movie is 3 separate movies, not a single 3-part one like our system has.

I'm not sure if it's a bug, but the entire scan fails if a single episode is a repeat of <series, season, episode number>. For the same reason as movies, the mapping is not always 1-1. Saiki K is listed as 5 episodes in one, as each part was aired during commercial breaks throughout the day, for example. There's not really a "correct" way to list it, but it was released as all 5 parts in one "episode" on Blu-ray. TvDB lists them all separately, though.
To get around it, we need to give absolute (the math term, meaning absolute distance from 0) season and episode numbers to avoid conflicts.

**Comment by da3dsoul** [comment]
I would call it a bug, as even if it's intended, the whole scan shouldn't fail, just the current series. If it's rejected for the above reason, addDirectoryItem() should also return false so that we can find it and handle the reason.

**Comment by AkariDN** [comment]
About real plugin mentioned in PR - unfortunately I'm busy at main job and wasn't able to find time to make it public in official Kodi repository yet. Additional testing, bugfixes, documenting and cooperation with main plugin's author is needed. But you can see current version here: AkariDN/plugin.video.wakanim@0bffd00c502462b3fae012a2b0275f005bcb834a - it works and I'm actively using it.

About episode duplicates - you can use any season/episode numbers but listitem's path (plugin URL) must be unique. Probably scan fails for another reason. addDirectoryItem() cannot check for any "specific errors" because it only adds item to list and don't know about item's future (whether it will be e.g. displayed or passed to scanner), so it cannot do any scanner-specific validations. The only way is to know how media library and scanner work and pass to it listitems with proper data.

**Comment by da3dsoul** [comment]
Hmm. Then I want better logging down the line. Even with debug logging, it just says all is well and scan finished, when nothing gets added

**Comment by AkariDN** [comment]
At least debug logs must contain "VideoInfoScanner: Skipping dir..." if nothing changed. If there are only "Starting scan" and "Finished scan" then something wrong with data returned from plugin... Scanner logs are quite verbose.

**Comment by da3dsoul** [comment]
Hmm nothing is logged between. If it's so verbose, then it should say if you are handing it invalid data.
I can tell you that the only difference made between it not working and it working was to remove the "duplicate" episodes.

**Comment by da3dsoul** [comment]
My guess is that there's sanitizing being done when you give it NFOs that doesn't happen with Python objects

**Comment by da3dsoul** [comment]
NFOs are just text and not typed, so that's a step that's missing

**Comment by AkariDN** [comment]
Make a directory in your plugin with library node url and check what is actually passed to scanner:
```Python
xbmcplugin.addDirectoryItem(handle, 'plugin://plugin.video.nakamori/tvshows/', xbmcgui.ListItem('Library'), True)
```
And here is a simple example with duplicate episodes:
```Python
PLUGIN_NAKAMORI_URL = 'plugin://plugin.video.nakamori/tvshows/'

def test_episodes(handle, tid):
    data = ((1,1),(1,1),(2,2),(2,2))
    eid = tid*100
    for s,ep in data:
        title = 'Episode {0}'.format(ep)
        url = '{0}?eid={1}'.format(PLUGIN_NAKAMORI_URL, eid)
        eid += 1
        li = xbmcgui.ListItem(title)
        li.setInfo('video', {
            'title': title,
            'tvshowtitle': 'TVShow {0}'.format(tid),
            'season': s,
            'episode': ep,
            'plot': url,
            'mediatype': 'episode'})
        li.setMimeType('application/mp4')
        li.setProperty('IsPlayable', 'true')
        li.setContentLookup(False)
        xbmcplugin.addDirectoryItem(handle, url, li, False)
    xbmcplugin.endOfDirectory(handle)

def test_tvshows(handle):
    data = (1,2)
    for tid in data:
        title = 'TVShow {0}'.format(tid)
        url = '{0}?tid={1}'.format(PLUGIN_NAKAMORI_URL, tid)
        li = xbmcgui.ListItem(title)
        li.setInfo('video', {
            'title': title,
            'plot': url,
            'mediatype': 'tvshow'})
        xbmcplugin.addDirectoryItem(handle, url, li, True)
    xbmcplugin.endOfDirectory(handle)

def plugin_main(argv):
    handle = int(argv[1])
    args = parse_qs(argv[2][1:])
    if args and 'tid' in args:
        xbmcplugin.setContent(handle, 'episodes')
        test_episodes(handle, int(args['tid'][0]))
    else:    
        xbmcplugin.setContent(handle, 'tvshows')
        test_tvshows(handle)
```

**Comment by da3dsoul** [comment]
I'll try. We shall see

**Comment by bigretromike** [comment]
@AkariDN can we pass 'watchmark' so when files is imported to Library its marked as watched? If so, which attribute it looks for because from out test it looks like it done not take that info into account.

**Comment by AkariDN** [comment]
'playcount' in listitem's info and 'videolibrary/importwatchedstate' in advancedsettings.xml

**Comment by bigretromike** [comment]
That would make sense because we use `playcount` already. Thanks !

**Comment by bigretromike** [comment]
@AkariDN do you recall adding something to JSON-RPC to make files added from plugin source could be accessed by it ?
I'm sending this command:
```
{"jsonrpc":"2.0","method":"Files.GetFileDetails","params":{"file":"plugin://plugin.video.nakamori/tvshows/98939/play", "properties": ["episode", "title", "uniqueid", "tvshowid"]},"id":1}
```
I tried with file: `plugin://plugin.video.nakamori/plugin://plugin.video.nakamori/tvshows/98939/play` because in db the files are saved with as `strPath = plugin://plugin.video.nakamori/tvshows/98939/play`
while path linked to it is `strPath = plugin://plugin.video.nakamori/` so I combine them, yet the kodi throw at me this kind of error:

```
2019-04-10 13:39:09.492 T:12520  NOTICE: {"jsonrpc":"2.0","method":"Files.GetFileDetails","params":{"file":"plugin://plugin.video.nakamori/tvshows/98939/play", "properties": ["episode", "title", "uniqueid", "tvshowid"]},"id":1}
2019-04-10 13:39:09.493 T:12520 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nakamori/tvshows/98939/play
2019-04-10 13:39:09.493 T:12520  NOTICE: {"error":{"code":-32602,"message":"Invalid params."},"id":1,"jsonrpc":"2.0"}
```

I print the command that I send that's why its there.

I'm not sure if this is not because the plugin was used as source so kodi now can't combine proper file path and searching by full_path_name is broken.

**Comment by AkariDN** [comment]
Plugin URLs are not supported by this function:
```C++
JSONRPC_STATUS CFileOperations::GetFileDetails(const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
{
  std::string file = parameterObject["file"].asString();
  if (!CFile::Exists(file))
    return InvalidParams;
...
```

**Comment by bigretromike** [comment]
Any chance you could make it work ? or any idea how to retrive db_id for item that I have full path to file that was added to db ?! 
I would like to sync Library with Plugin for those who would like to use plugin on one Kodi and Library source on other.

**Comment by AkariDN** [comment]
Unfortunately currently I have no time for this. Create an issue in Kodi repository, I hope somebody fix it.

I'm not an expert in Kodi jsonrpc, maybe there is some easier way except this:
* Export your tvshows from plugin with 'tag' and 'uniqueid' properties (e.g. tag = Nakamori, uniqueid = tvshow/episode id)
* Use VideoLibrary.GetTVShows and find 'tvshowid' by 'uniqueid'
`{"jsonrpc":"2.0", "id":1, "method":"VideoLibrary.GetTVShows","params":{"properties": ["uniqueid"], "filter": {"tag": "Nakamori"}}}`
* Use VideoLibrary.GetEpisodes and find 'episodeid' by 'uniqueid'
```{"jsonrpc":"2.0", "id":1, "method":"VideoLibrary.GetEpisodes","params":{"tvshowid": 1, "properties": ["uniqueid"]}}```

**Comment by bigretromike** [comment]
No problem. Will do ! Also I will check that workaround 

On April 11, 2019 5:16:42 AM GMT+02:00, AkariDN <notifications@github.com> wrote:
>Unfortunately currently I have no time for this. Create an issue in
>Kodi repository, I hope somebody fix it.
>
>I'm not an expert in Kodi jsonrpc, maybe there is some easier way
>except this:
>* Export your tvshows from plugin with 'tag' and 'uniqueid' properties
>(e.g. tag = Nakamori, uniqueid = tvshow/episode id)
>* Use VideoLibrary.GetTVShows and find 'tvshowid' by 'uniqueid'
>`{"jsonrpc":"2.0", "id":1,
>"method":"VideoLibrary.GetTVShows","params":{"properties":
>["uniqueid"], "filter": {"tag": "Nakamori"}}}`
>* Use VideoLibrary.GetEpisodes and find 'episodeid' by 'uniqueid'
>```{"jsonrpc":"2.0", "id":1,
>"method":"VideoLibrary.GetEpisodes","params":{"tvshowid": 1,
>"properties": ["uniqueid"]}}```
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/306#issuecomment-481949174

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
Akari how dare you! Devs aren't allowed to have basic human needs, let alone lives! Do we need to take you to the White Room for educating?

**Comment by bigretromike** [comment]
btw, he dont want to be rude, his just being himself

**Comment by da3dsoul** [comment]
I would hope that is recognizable as a joke. If not, then either the language barrier is more effective than Trump's wall or I worry for your past and future as a world class comedian.

**Comment by bigretromike** [comment]
I know its a joke, dont worry - we live in strange times 🦄

**Comment by bigretromike** [comment]
I clean up as this is going to be linked.

I made and Issue: https://github.com/xbmc/xbmc/issues/15897 not sure if I describe it the way it should be describe. Finger cross that someone pick that up and make fix for Leia.

**Comment by bigretromike** [comment]
@AkariDN hey, any idea why it throws this king of error for every tvshow that is being added to Video Library ?
```
2019-04-15 13:55:01.865 T:7140   ERROR: CScraperParser::Parse: Could not find scraper function GetArt
2019-04-15 13:55:01.865 T:7140   ERROR: ADDON::CScraper::Run: Unable to parse web site
2019-04-15 13:55:01.882 T:7140 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nakamori/tvshows/807
```
We use `setArt()` for our ListItems, but do we need to write some custom function `GetArt` or something?

**Comment by bigretromike** [comment]
Our lord and savior @AkariDN did push fix that end-up in kodi 18.2
While mine issues weren't resolved its a still nice thing to have. 

without `Files.GetFileDetails` fix we can't sync watch from shoko to library after import it's still a stable thing. 

So we having a great functionality for 18.2+

**Comment by da3dsoul** [comment]
We might be able to with DB hacks similar to that watched state manager I've seen but never used

**Comment by bigretromike** [comment]
or if you are able to fix the shit inside kodi c++ code from issue I made :P and then I can make it work with proper API call ;p

**Comment by bigretromike** [comment]
Waiting for approval: https://github.com/xbmc/xbmc/pull/16087
Until then this is really hard (or by somekind of funky/hacky workaround)

**Comment by bigretromike** [comment]
I'm still waiting for them to review my patch, I will announce this feature as part of 3.3.0 maybe we will have working sync between both.

@da3dsoul you said about some DB hacks, still got them ?

Im moving this to 3.3.0;

**Comment by bigretromike** [comment]
As this is possible in 18. (will probably need to add that in notes), I don't think that sync will be possible before 19.0, so moving this to 19.x

**Comment by bigretromike** [comment]
Once again I would like to thank you @AkariDN - your work was a game changer for me :-) thanks.

Also:
- [x] Update Library work fine
- [x] Sync Plugin flags with VideoLibrary flags

**Comment by tamodolo** [comment]
Hello. I tried to use nakamori as video source but it's crashing saying that directory wasn't found

`2024-07-13 16:13:07.058 T:3240     info <general>: CActiveAESink::OpenSink - initialize sink
2024-07-13 16:13:07.094 T:14740   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.nakamori/tvshows/347b8f4d-beb0-4ea6-a9e6-39663c227949/
2024-07-13 16:13:07.098 T:14020   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nakamori/tvshows/347b8f4d-beb0-4ea6-a9e6-39663c227949/) failed
2024-07-13 16:13:07.100 T:14020    info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2024-07-13 16:13:10.974 T:14020 warning <general>: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2024-07-13 16:13:14.078 T:18512    info <general>: Skipped 12 duplicate messages..
2024-07-13 16:13:14.078 T:18512   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'routing.RoutingError'>
                                                   Error Contents: No route to path "/tvshows/347b8f4d-beb0-4ea6-a9e6-39663c227949"
                                                   Traceback (most recent call last):
                                                     File "C:\Users\tamod\AppData\Roaming\Kodi\addons\plugin.video.nakamori\nakamoriplugin.py", line 987, in <module>
                                                       plugin.run(argv)
                                                     File "C:\Users\tamod\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\tamod\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 143, in _dispatch
                                                       raise RoutingError('No route to path "%s"' % path)
                                                   routing.RoutingError: No route to path "/tvshows/347b8f4d-beb0-4ea6-a9e6-39663c227949"
                                                   -->End of Python script error report<--
                                                   
2024-07-13 16:13:14.125 T:17468   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.nakamori/tvshows/347b8f4d-beb0-4ea6-a9e6-39663c227949/
2024-07-13 16:13:14.129 T:14020   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nakamori/tvshows/347b8f4d-beb0-4ea6-a9e6-39663c227949/) failed
2024-07-13 16:13:15.979 T:14020 warning <general>: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running`

**Comment by bigretromike** [comment]
that's probably the case as there been one rewrite with newer python. 
this function was more of experimental because o the lack on Kodi API back then you wouldn't be able to sync watched status of your series, which was a bit issue back then (you would cut the function that was included with shoko)

**Comment by bigretromike** [comment]
> After medling a lot I found a solution to do the same using jellyfin to read KODI and KODI to read jellyfin. The jellyfin plugin can do that just by configuring the server. So I think KODI has the API now as jellyfin is able to do it. But as this plugin seems not maintained I think no direct solution will merge soon...

I never had time to play with jellyfin more, and I'm unable to test that there is both-way-synchronization of watched status if you do that with jellyfin. Also you lose ability to score series, etc. but I assume that's not the problem for you. 

It was experimentally added feature, but the end game of it was that you stream those episodes same way (thru shoko internal server) and the cons (features linked with shoko) was bigger than pros (kodi internal mechanism + speed up while browsing)

**Comment by tamodolo** [comment]
> > After medling a lot I found a solution to do the same using jellyfin to read KODI and KODI to read jellyfin. The jellyfin plugin can do that just by configuring the server. So I think KODI has the API now as jellyfin is able to do it. But as this plugin seems not maintained I think no direct solution will merge soon...
> 
> I never had time to play with jellyfin more, and I'm unable to test that there is both-way-synchronization of watched status if you do that with jellyfin. Also you lose ability to score series, etc. but I assume that's not the problem for you.
> 
> It was experimentally added feature, but the end game of it was that you stream those episodes same way (thru shoko internal server) and the cons (features linked with shoko) was bigger than pros (kodi internal mechanism + speed up while browsing)

Now I see I writed wrong... It's Jellyfin that reads Shoko with Shokofin plugin and Kodi reading Jellyfin using the Jellyfin plugin (not Jellycon as this don't delivers to KODI's native library)

Jellyfin plugin is able to sync watch status with jellyfin and that with Shoko. My reasons to use KODI as a player for Shoko using it's native library is because KODI recomend things, have a continue watching feature and is easy to control on the couch. The later isn't as good as the one Crunchyroll uses but this one also have drawbacks.

I tried PLEX but it's bad. Real bad... And Jellyfin isn't read for couch control... Or at least I didn't found a direct client that would allow that.

**Comment by bigretromike** [comment]
I see - If I recall seeing pulls/merges Shoko should have (had) Recomendation section. 
Maybe adding that one to Nakamori would help?

Because even if I/someone fix issue with using plugin as source, then each wipe/format would results in losing all watched marks on your end. 

Because you use Shoko probably for organizing and tracking series, because if not you could use files directly with animedb plugin (not the best) but some people use it with success.

**Comment by tamodolo** [comment]
> I see - If I recall seeing pulls/merges Shoko should have (had) Recomendation section. Maybe adding that one to Nakamori would help?
> 
> Because even if I/someone fix issue with using plugin as source, then each wipe/format would results in losing all watched marks on your end.
> 
> Because you use Shoko probably for organizing and tracking series, because if not you could use files directly with animedb plugin (not the best) but some people use it with success.

My main problem with using KODI directly (witch I was actualy) is that all metadata needs to be manual (I used media elch) as scrapers do mistakes a lot. For other media libraries/servers, KODI included, they're not designed to merge movies as a series sequel or prequel. Shoko's group system is heaven for this purpose.

I still need to link episodes manualy on Shoko but this is much less work than Media Elch. Mainly because I don't need to link images or worry about folders and naming systems...

Also I would like to avoid accessing media through plugin interface on KODI. It is very wonky. One that control it's internal library system is better. I know that using the plugin system gives more freedom to do whatever you like but also is an interface hell as KODI can't help itself to remember a common list scheme for it but instead it chose one as main (that you can't control) and likes to remember it for each screen you navigates. Or I'm just dumb and don't know how to configure this.

I realy don't know how jellyfin do it's magic. I certainly didn't touch video sources for it to work. Maybe taking a look at it may give ideas about a similar plugin that access Shoko directly.

About recomendation section, KODI just random pick some shows without any data analisys. This is ideal for me as I don't really want to see things I already know but instead something diferent each time. This avoid animes get lost in preferences too.

Also, Jellyfin seems to reacreate watch marks including the last position you stoped the video between wipes. This is also true between jellyfin wipes as I tested a lot of Shokofin configurations before achieving what I wanted. So it seems this info is passing from KODI to jellyfin and then to Shoko. I don't remember if KODI has a rate system. If there's present then it should be possible to pass that info too. Also, Jellyfin inserted it's own options into KODI's context menu. That may be solved that way too.

**Comment by bigretromike** [comment]
If you can test one thing for me, as I dont have time, time and time to test that. Does jellyfin update watch status in both ways ? 

Mark episode as watched on jelly (while kodi is disabled), open kodi and check if that episode is marked also, and same thing with marking other episode as watched in kodi (while jellyfin is disabled). If I recall there was issue with my service that did that and you would end up with different watched states. 

Maybe 2 major version of kodi fixed that thing.

If jellyfin could do that - then why not. after fixing some bugs people requested I could try to do this too, I wanted to play with this feature because on very big collections browsing thru plugin was a bit slow - d3d did some great optimization there that was a really good job back then, praise him for that, but now its now and its a bit slower than it was at it peeks.

**Comment by tamodolo** [comment]
> If you can test one thing for me, as I dont have time, time and time to test that. Does jellyfin update watch status in both ways ?
> 
> Mark episode as watched on jelly (while kodi is disabled), open kodi and check if that episode is marked also, and same thing with marking other episode as watched in kodi (while jellyfin is disabled). If I recall there was issue with my service that did that and you would end up with different watched states.
> 
> Maybe 4 major version of kodi fixed that thing.
> 
> If jellyfin could do that - then why not. after fixing some bugs people requested I could try to do this too, I wanted to play with this feature because on very big collections browsing thru plugin was a bit slow - d3d did some great optimization there that was a really good job back then, praise him for that, but now its now and its a bit slower than it was at it peeks.

Just tested.

![image](https://github.com/user-attachments/assets/761235fa-1973-4b2c-99cc-31a14b47a012)

I was watching Vermeil in Gold (about to drop that....). With KODI closed I opened first ep from Tensura and marked as watched. Opened KODI, jellyfin plugin did the welcome and then I go to the TV shows like the print abobe and there it is. Quite nice!

**Comment by tamodolo** [comment]
I'm also finding the Shokofin plugin very nice as it has options to merge specials based on air date and TVDB (TMDB in the future) to list them in the right spot. This also reflects on KODI too.

**Comment by bigretromike** [comment]
One more week and I will finish my work for few companies, and I can hope on naka-train ;-)
