### ISSUE TITLE
Better debug/log/error_handler ?

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#308]
```
019-04-10 12:54:57.651 T:3004   ERROR: Nakamori|Logger -> There was an error while executing Nakamori.
2019-04-10 12:54:57.651 T:3004   ERROR: Nakamori|Logger -> Nakamori Version 3.1.0~beta20
2019-04-10 12:54:57.651 T:3004   ERROR: Nakamori|Logger -> The url accessed was nakamoriscript.py
2019-04-10 12:54:57.651 T:3004   ERROR: Nakamori|Logger -> Error Setting Watched Status -- Exception: TypeError at ./script.module.nakamori/nakamoriscript.py#L260
```

Im editing `lib/shoko_models/v2.py` and instead of `self.id` I typed `self.id()` and kodi throw this error above... I don't remember how old thing did throw error but it was pointing closer to error that this. Can we make something with it ? because that kind of error if posted in issue wouldn't tell us much - only that its a setting watch issue.

**Comment by da3dsoul** [comment]
I can sort it in reverse, but the lower on the stack, the closer it is

**Comment by bigretromike** [comment]
sorry but `nakamoriscript` is not lower than `v2.py` is :-)

**Comment by bigretromike** [comment]
or maybe its because its because it `RunScript` instead of doing proper python :-)
that would make sense, sadly

**Comment by da3dsoul** [comment]
No I mean that is not a full log. "Lower" means after those lines in the log.

**Comment by bigretromike** [comment]
Lower was nothing 👍

**Comment by da3dsoul** [comment]
Hmm that's a problem

**Comment by bigretromike** [comment]
it give a proper data - it miss when python miss info. For now its ok.
