### ISSUE TITLE
Option to swap Actors x Characters or/and make it permanent for video source 

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#311]
Before it was preferred to swap those, because having them correct didn't  benefit us that much.
Then came support for ExtraInfoScript and it worked ok, because it would get his own list of actors.
Now we have Video Source and we would need to have it swap.

I'm thinking that for Video Source aka `/tvshows/` this should be swapped (without ability to pick) and for anything else (plugin) option to swap those would be nice with default set as normal, and for those like me I can swap them back to show anime characters first over actors.

But if you think that I'm the only person that would use that we can drop the option - less options the better :-) no point in making option just for me :p

Hahah, I have evil idea adding hidden menu that would have all the options I need ahahhahaha like 200 options xD

**Comment by bigretromike** [comment]
Also why I want to swap them back for `/tvshows/` simple, now when he add character it looks like wrong characters are linked with series because it still link them by actors.

**Comment by bigretromike** [comment]
Also I see its half mixed up. The name is ok, the picture if from character. So half work done ;-)

**Comment by da3dsoul** [comment]
Yeah I did it that way because in anime, you don't care what the actor looks like

**Comment by bigretromike** [comment]
DEFINITELY THAT'S MY THING ! :-) but its wrong very bad for Video Source
