### ISSUE TITLE
idea: cut one query without flating directory

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#314]
each time you enter directory/series/group/filter you: `version`, `status`, `ping` and `proper query` this results in same data being send (except random picture) when you using default non-flat directory setting.

Could we somehow rebuild structure from that data, or could we just force cache for that setting? 
I understand that first 3 are a must and are (should be) fast and light, but the 4th is bulky. 

Or could we just change url so we dont ask for `level=2` deep data and just ask for structure - but that would require apiv3 because If I recall correctly I had no idea how to implement the proper data response in apiv2 without iterating over those items :P

- I will probably leave this as APIv3 thing, but I would like to ping you @da3dsoul so you know about what I would like to aim in.
- Cache is fine but on local host it would be probably be slower than asking again (maybe not for big series)
- Creating list for all directories on first query would be memory intensive especially when you are going for smaller folder like specials but you would have to wait for computating all other ones.

**Comment by da3dsoul** [comment]
It's already optimized. It only gets the children when building the directory. Yes, it'll be less wasted data in APIv3

**Comment by bigretromike** [comment]
It's not about how much data is send. Its about redundancy that is not necessary - in this place.
- [x] cache `series` data 
- [x] expire cached data so refresh will refresh watch flags
