### ISSUE TITLE
Issues in 3.1.0

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#316]
- [x] vote for series broken
- [x] vote for episode broken
- [x] inspect file, esc, error
- [x] repo plugin missing news
- [x] moving mouse/keyboard close Information with: `CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running` (old: scrolling 'whats new' close it)
- [x] search 'empty results' exit to Addons (because ActiveWindow)
- [x] '..' from search results end up in main menu and not search menu
- [x] duration=0 for subtitle file, instead of proper media file (old: values in view are mixed up for some series (time, size -> image below))
- [x] playing subtitle file results in episode being marked as watched :-) (issue linked with one above)
- [x] "unmatched parentheses in" for contextmenu-addons items

- [x] '..' from saved search there is message about empty result, which is wrong

**Comment by bigretromike** [comment]
**values in view are mixed up for some series**
![mix_value](https://user-images.githubusercontent.com/6052025/57604772-4d449e00-7565-11e9-819b-529ca13e632b.png)

**Comment by da3dsoul** [comment]
Hahahahaha WTF

**Comment by da3dsoul** [comment]
Actually, I know exactly why that happened

**Comment by da3dsoul** [comment]
The duration isn't valid for those files

**Comment by bigretromike** [comment]
> 
> 
> The duration isn't valid for those files

Shoko, return `duration=0` for those files, because its an subtitle item, next files in `files` is proper mkv file.

**Comment by da3dsoul** [comment]
Files without video shouldn't be listed. If it's just a matter of it picking the wrong stream to pull info from, then that's another issue, but either way it needs fixed.

**Comment by bigretromike** [comment]
@da3dsoul I manage to fix all of them with exception of that search black magic you manage to do. Any chance you can fix that in few days? I would like to push 3.2.0 with those fixes and proper change-log

**Comment by bigretromike** [comment]
Subtitles should be included with episode file, you should pass those to external player if you wish to watch your anime with subtitles that ain't included in video file.

**Comment by bigretromike** [comment]
@da3dsoul I fixed all the issue I found while playing with stable, anything you would like to add before pushing 3.2.0 ?

**Comment by da3dsoul** [comment]
Nah
