### ISSUE TITLE
Add Search results to cache

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#318]
- [x] profile time if marginal don't do it
- [x] option to enable this only visible when cache is on
- [x] ability to set expiration (in days) for search cache

**Comment by bigretromike** [comment]
Looks like I could have been drunk, its already in cache.
btw. on VPN with 3000 series `All` loads in 17s , while from cache it takes 7 sec.

**Comment by da3dsoul** [comment]
That time is purely network and deserialization. There's not much you can do once you have a local cache
