### ISSUE TITLE
Finish: Trakt voting

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#320]
Time to finish this option

I'm probably blind but I cannot find Trakt related settings in Nakamori Settings anymore... Need to check that out.

**Comment by bigretromike** [comment]
I cannot find it because its hidden thanks to a bug, but its still there working

**Comment by bigretromike** [comment]
@da3dsoul care to take this ?

**Comment by da3dsoul** [comment]
I'm putting it off a bit longer to fix in server

**Comment by bigretromike** [comment]
fix it in server or just fix server?

**Comment by da3dsoul** [comment]
Fix it in server. Server itself isn't  broken beyond the major design flaws that we are slowly working on. There's definitely some bugs here and there with ASP.NET, but it should work for the most part

**Comment by bigretromike** [comment]
ok, if its broken in server then Im not doing this today. 
thanks for info.

**Comment by bigretromike** [comment]
I'm not even sure if we have Trakt users anymore :-)
Also it would be trivial if this ever worked on shoko server to sync all previous ratings with Trakt when needed.
