### ISSUE TITLE
Calendar source option: shoko vs external

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#321]
- [ ] option to switch source (so it will work in both modes (dir vs window)
- [ ] make external source for calendar as script (or lib?)

**Comment by da3dsoul** [comment]
It could be done as an extension, but as mentioned previously, any sources for calendar days should be in Shoko, not Nakamori

**Comment by bigretromike** [comment]
not my fault that both anidb api for calendar and shoko way it get data sucks :-)
There are multiply calendars on web, maybe someone want to use other.
I asked numerouse times if plugin system is in work in shoko, so I could make this as an plugin to overwrite calendar behavior on server. Until then I can just take that out from `lib` and move to external solution so if anyone ever would like to use my source then this plugin could be wipe out.

I could try to make it as new calendar in shoko (or "new way" setting for calendar), if you think its worth the hassle

**Comment by da3dsoul** [comment]
When we get AniList going, then we'll have way more data for calendars, as they run AniChart, as well.

**Comment by bigretromike** [comment]
So from what you wrote it looks that there is no point in adding external source calendar to shokoserver.
