### ISSUE TITLE
Improve Calendar UI in WindowXML mode

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#322]
I still don't like how it looks. 
Any suggestion will be considered.

**Comment by bigretromike** [comment]
@da3dsoul any suggestion or should I make it all PINK ?

**Comment by da3dsoul** [comment]
IDK. If you want UI design, talk to  EC. He's pretty good at it.

**Comment by bigretromike** [comment]
when did you put down the role of making designs? You were quite good with it. I wrote here, because I counted on you ;-)

**Comment by da3dsoul** [comment]
I'm not really good at design itself. I'm good at pointing out flaws and suggestions for improvement. Calendars are also one of those things that I'm just not good at. If I were to design something, I'd probably just mash up ClientV2 and AniChart concepts

**Comment by bigretromike** [comment]
![ac](https://user-images.githubusercontent.com/6052025/57955837-33a1ae80-78f7-11e9-8261-4933d11c6141.png)

**Comment by da3dsoul** [comment]
Yeah, I really like AniChart. I'd do some things a bit different

**Comment by bigretromike** [comment]
sadly anidb don't give so much description about series. also having the description that way make from 7 colums to 3 :-), I could see doing one WindowXML more so you can pick your Calendar style. But give me something to work on, if you don't want to make one. what would you change in anichart

**Comment by bigretromike** [comment]
![abb](https://user-images.githubusercontent.com/6052025/57956022-d0fce280-78f7-11e9-8cad-113a2f30cd57.png)
![avb](https://user-images.githubusercontent.com/6052025/57956030-d5290000-78f7-11e9-9753-b872ceb27c55.png)

**Comment by bigretromike** [comment]
or you more into this AC 
![acc](https://user-images.githubusercontent.com/6052025/57956300-d3ac0780-78f8-11e9-8616-b33b24812349.png)

**Comment by da3dsoul** [comment]
The things I would change are what is shown on cards and whatnot, it'll need to be dynamic with fallbacks, as there will be info missing like you mentioned.

**Comment by bigretromike** [comment]
@da3dsoul which AC version you like the most? first with 3x3 or second 5x7-8

**Comment by bigretromike** [comment]
Will do my friend, will do

**Comment by bigretromike** [comment]
![111ac](https://user-images.githubusercontent.com/6052025/58019281-6caf6e00-7b05-11e9-8b77-acdf7f85dd26.png)

Hows that ?

**Comment by bigretromike** [comment]
@da3dsoul the only issue it the size of the font - like it was before that why I got those PIL workaround for titles. For now I had to add custom fonts into default skin - which could end up in your delta skin with proper finishing of Label2 issue.

**Comment by bigretromike** [comment]
Font.xml
```
		<font>
			<name>robo16</name>
			<filename>NotoSans-Regular.ttf</filename>
			<size>16</size>
		</font>
```

**Comment by bigretromike** [comment]
Or edited estaury!!! with fonts mod (latest Leia version)
[skin.estuary1.zip](https://github.com/bigretromike/nakamori/files/3197943/skin.estuary1.zip)

**Comment by da3dsoul** [comment]
The biggest issues I see there are the poster squishing instead of cropping and the titles being cut off

**Comment by bigretromike** [comment]
posters are issue from anidb - I use same, so if they dont have it Nakamori don't have it. same goes to shoko. nothing much I can do about it. the title yeah, thats no issue.

**Comment by da3dsoul** [comment]
I'm referring to squished posters, not missing ones

**Comment by bigretromike** [comment]
And I'm referring those too. 
If there is a Poster Anidb use it if not they use something wider than taller. Not much I can do about it.

**Comment by bigretromike** [comment]
@da3dsoul 29-06-2019 
https://anidb.net/perl-bin/animedb.pl?show=calendar&do=schedule&last.anime.week=26&last.anime.year=2019

same images. same dimensions

**Comment by da3dsoul** [comment]
Crop it. If we don't have pillow, then I can make an endpointb with cropping

**Comment by bigretromike** [comment]
even with external source image ?
even if not sure. 

to make it work with PILLOW it would be downloaded to temp and with new layout its not needed, also how you crop it when you dont detect face/title.

Go for it anyway I just move it ahead to have non hentai content there hehe

**Comment by bigretromike** [comment]
Also which solution you prefer for font, injecting into used skin ? or with delta skin updated ? (for both k17 and k18 version ?)

**Comment by da3dsoul** [comment]
You'll want to use APIv3 later. I'll handle what info is filtered (no hentai on non-hentai users).
You handle how it gets displayed. I can rewrite the API code in Nakamori when it gets there, just keep in mind that some things will be organized differently and we may have better info.

**Comment by da3dsoul** [comment]
I prefer that we don't require a specific skin.

**Comment by bigretromike** [comment]
so we inject in any skin the font we want to use;
any recommendation for font that support jp ?

**Comment by da3dsoul** [comment]
I have no clue. Roboto is a nice free font, but no clue

**Comment by bigretromike** [comment]
yeah, roboto was first I wanted to use but it didn't work for some reason, but I fix that but went with arial. Ok. I will make few ajustments with font, injection, make long title cut in good place, and description will have scroll that will work (maybe), but most of those from shoko are missing description and the number of episode that will be aired

**Comment by bigretromike** [comment]
Any buttons you want to have on those 'series boxes' ? like on AC? or we leave info about airing date on the bottom part ? I just put that to see if its on right height.

**Comment by da3dsoul** [comment]
We'll have buttons be context menus, as there's not much we can do, other than possibly show related series and/or more info

**Comment by bigretromike** [comment]
I see a lot of options: releated, info, add to wishlist, send to ... (pick anything like pushbullet etc), enter series (when something on calendar is already in your collection), cast, hide series from calendar (if needed for any reason)

**Comment by bigretromike** [comment]
Issue with injecting custom size/font is when you are using default skin, because that one is installed not in your addons but in base directory, so you would have A) force user to use copy of default skin (with tweaks already in it, while updating it from time to time and checking for compatibility issues - ex. k17 this skin version, k18 that version) B) generate descriptions as image and while clicking on it dialog box come out and let you read full text in default font. 
If user use non default skin then its not a problem to inject our font/size.

I got that sweet injector from my senpai repository, its a bit buggy but it clear as day and night that you wont be able to edit font of default skin from inside kodi and making long ass manuals/videos just to change that is not worth it because the main goal is to be as user friendly as possible (ip + login/password) with ability to tweak everything for power users.

I will try the PILLOW method once again and check out the results - it shouldn't take THAT much space, and later I could implement garbage collection in service so the old one get wiped.

**Comment by da3dsoul** [comment]
We can probably read the current skin from settings, then determine the location and patch it in to whatever skin is needed

**Comment by bigretromike** [comment]
I will short it for you:
- any installed in addons skin = compatible
- default skin is in kodi directory and not addon folder = not compatible (need manual or script from outside kodi)

**Comment by da3dsoul** [comment]
Ah, I see. You won't have write access. We can detect that and make a patched copy....

**Comment by da3dsoul** [comment]
This is quickly becoming not in the scope of Nakamori. I would probably make this a separate add-on and see if they'll accept it in the main repo

**Comment by bigretromike** [comment]
any addon that modify any other addon (or skin) is forbidden. 
I will see how long it take to generate those description and if the time will be too long or the results not pleasing I will go with B) our skin with tweaks for k17 it would be easy because you set minimal python version in addon.xml so k17 wouldn't install k18 skin. and for k18 someone will have to get latest version from stable k18 each time some version get release and apply patches.

**Comment by bigretromike** [comment]
![acv2](https://user-images.githubusercontent.com/6052025/58152880-f8440e80-7c6d-11e9-81de-6d9251e5da7b.png)
@da3dsoul

**Comment by da3dsoul** [comment]
Nice

**Comment by bigretromike** [comment]
I'm happy that you like it. there still a lot of cleaning and I would like to have a popup window when you click on any element of series item, with detail information (for now it could be full description) and button that would be also as a right click option.

Any idea how it should look like ?

**Comment by da3dsoul** [comment]
Maybe look at the extendinfo window. It's super nice

**Comment by bigretromike** [comment]
hahaha, did you think why I waste extra time to make it work with nakamori ?:-) hahahha

But back on the topic, its nice, but its plain. Will shoko download cast for anime in calendar ?( would be awesome but I doubt) 
I could make it work with extendinfo script but I doubt that all shows on calendar will have it info on the site it take info from

![extra](https://user-images.githubusercontent.com/6052025/58154637-5e329500-7c72-11e9-8f29-bcc76a65846f.png)

I can make similar window with description being longer and cast cut of - but I would need to know what info we can get 👍

**Comment by bigretromike** [comment]
The best would be info if given series is in your collection, if so all info about it (latest watched episode, how many local episode you got) so you check check with calendar how far behind you are :-), how many episode there is for given series

**Comment by da3dsoul** [comment]
It can try. If it's a season 2 or something, it can fall back on cast for that

**Comment by bigretromike** [comment]
In ideal work calendar series should be stored so when you get episode for it you update info about series, while having big flexibility with showing new releases/calendar - also its not like each episode you create series just link to it.
If you want calendar to work with extendedinfo we need 3rd party ids (like id's from other sites, that info is available on anidb but only for series entries not in calendar if I recall)

**Comment by da3dsoul** [comment]
No we have that. No worries 😊

**Comment by bigretromike** [comment]
If so Im making that window then

**Comment by bigretromike** [comment]
Base: 
![extrainfo-view](https://user-images.githubusercontent.com/6052025/58171978-8bde0500-7c97-11e9-9617-fe145254d7cf.png)

Ours:
![naka-extrainfo-view](https://user-images.githubusercontent.com/6052025/58171989-91d3e600-7c97-11e9-918f-cafbaf89d0e9.png)

**Comment by bigretromike** [comment]
@da3dsoul how can I migrate servershoko settings to daily version? because it throw error with old config ?:-) did not one think of it ?

**Comment by bigretromike** [comment]
wiped and added mysql/anidb creds
nvm.

Will migrate rest of settings if needed
