### ISSUE TITLE
Rearrange Settings 

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#323]
I have no idea how long it will take to fix https://github.com/xbmc/xbmc/issues/15252 but it looks like some option as broken because you cannot set those from settings menu.

I can try and rearrange those so we don't have to use those 'hidden' values, example: moving Video Setting higher etc. or merging all 'trakt support' items in one category (so moving Play (No scrobble)) to same category for Trakt.

**Comment by bigretromike** [comment]
@da3dsoul any opinion on this?

**Comment by da3dsoul** [comment]
For one, scrobbling isn't a trakt thing explicitly. From nakamori, it should just tell Shoko where it's at, and Shoko should handle it.

I'm not sure how we'll clean up and make the settings as nice as I'd like them to be without that being fixed, other than building our own settings UI, which I'd prefer not to do.

**Comment by bigretromike** [comment]
Dead end? 

On May 18, 2019 1:23:01 AM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>For one, scrobbling isn't a trakt thing explicitly. From nakamori, it
>should just tell Shoko where it's at, and Shoko should handle it.
>
>I'm not sure how we'll clean up and make the settings as nice as I'd
>like them to be without that being fixed, other than building our own
>settings UI, which I'd prefer not to do.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/323#issuecomment-493625667

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
No, I mean there's no point. Trakt should be handled by Shoko, so we can avoid needing to have settings for it

**Comment by bigretromike** [comment]
Trakt is one of many missing settings you missing the point here 

On May 18, 2019 8:45:13 AM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>No, I mean there's no point. Trakt should be handled by Shoko, so we
>can avoid needing to have settings for it
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/323#issuecomment-493653471

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
Fair, but that's the one you mentioned

**Comment by bigretromike** [comment]
Remove `syncwatched`, `sync_to_library` from plugin 
- sync watched is deprecated because we have play/play_without_marking
- sync_to_library is not needed because the sync is on service side and I want to do something with that

- [ ] suncwatched
- [ ] sync_to_library
