### ISSUE TITLE
External Player not marking as watched (Leia 18.1) (Naka 3.2.0)

### ISSUE THREAD

**Issue by shibeobi12** [bigretromike/nakamori#324]
As title says, when I watch anything with Nakamori, it does not get marked as watched. I do, as of 3.2.0, get a message saying Nakamori failed to mark as watched. External player works with standard Kodi fare, just not Nakamori. I was recommended to post my playercorefactory.xml, so here's that as well. I can post whatever else is needed, just let me know.

![example](https://user-images.githubusercontent.com/50844560/58044982-0a9b3c80-7af6-11e9-8b8d-d4dc82a35186.png)

**Comment by bigretromike** [comment]
I got a fix for this, will be pushing in few minutes.
Also yes, its a bug in Kodi18 after someone clean up code (this time it wasn't @da3dsoul 👍 )

Also the loop changed and there was also issue from our end.

**Comment by bigretromike** [comment]
Please update on dev channel and open issue if its not resolved - only have on mind that `playcountminimumtime` is ignored for now its your normal % to mark is as watched divine by half (to mitigate fastforwarding) it should be allways anything below 50% so you should be fine.
