### ISSUE TITLE
Can you update this in the repo?

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#327]
I added a Japanese font to the NotoSans default. I also fixed some placement issues.
EDIT: I'll reup in a bit. There's a problem it seems.

**Comment by bigretromike** [comment]
next time, update version, thanks

**Comment by da3dsoul** [comment]
Oh. Hang on

**Comment by bigretromike** [comment]
`Thumbs.db` I see you

**Comment by bigretromike** [comment]
I updated version, is it the same ?

**Comment by bigretromike** [comment]
this one is bigger

**Comment by da3dsoul** [comment]
Different zip layout, though slightly. There was an error in that one.

**Comment by da3dsoul** [comment]
Wrong settings in Winrar or something

**Comment by bigretromike** [comment]
updating

**Comment by da3dsoul** [comment]
You'll like this.
![scr](https://i.imgur.com/gVYT0zL.jpg)

**Comment by da3dsoul** [comment]
BTW fabulous OST

**Comment by bigretromike** [comment]
I would like it if you included my fix (if you didnt already for that label2 issue)

also updated; 
will wait for dev to update (1 minut) and will force stable after

**Comment by da3dsoul** [comment]
Which one? I can add it in and reup

**Comment by bigretromike** [comment]
https://github.com/phil65/skin.estuary/pull/255/commits/abdf48e9976f2aa0b782867cc52400ba9a206a9a

**Comment by bigretromike** [comment]
remove thumb.db and .gitignore and bump version

**Comment by da3dsoul** [comment]
Doing it already haha
[skin.estuary_delta.zip](https://github.com/bigretromike/nakamori/files/3206574/skin.estuary_delta.zip)

**Comment by da3dsoul** [comment]
kk. Should be good now.

**Comment by da3dsoul** [comment]
But yeah, now if someone wants to use the japanese (kanji) title, Kodi can show it without a custom (looking) skin.

**Comment by bigretromike** [comment]
what about this ?


[Migu.zip](https://github.com/bigretromike/nakamori/files/3206580/Migu.zip)

**Comment by da3dsoul** [comment]
Dunno. I used Yu Mincho Demibold

**Comment by da3dsoul** [comment]
Merged it with NotoSans

**Comment by bigretromike** [comment]
If you did it once, could you just add this as another font option ? :-)

**Comment by da3dsoul** [comment]
I could. Adding a font isn't hard. That font is 3MB, though. Is it really nice enough to warrant it? I added a screenie above of the current one.

**Comment by bigretromike** [comment]
just add it. its not RAM its just a Disk space.

**Comment by bigretromike** [comment]
compare screen also would be nice 👍

**Comment by bigretromike** [comment]
While I have you here any suggestion what I can do to overcome this 
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'puf' is not defined
                                            Traceback (most recent call last):
                                              File "C:\Users\brm\AppData\Roaming\Kodi\addons\script.module.nakamori\lib\windows\series_info.py", line 66, in onInit
                                                li = series.get_listitem()
                                              File "C:\Users\brm\AppData\Roaming\Kodi\addons\script.module.nakamori-lib\lib\shoko_models\v2.py", line 736, in get_listitem
                                                self.url = self.get_plugin_url()
                                              File "C:\Users\brm\AppData\Roaming\Kodi\addons\script.module.nakamori-lib\lib\shoko_models\v2.py", line 726, in get_plugin_url
                                                return puf(nakamoriplugin.show_series_menu, self.id)
                                            NameError: global name 'puf' is not defined
                                            -->End of Python script error report<--
```

**Comment by da3dsoul** [comment]
You hard code the string. That's the only option for now.

**Comment by bigretromike** [comment]
nope

**Comment by bigretromike** [comment]
I wanted to be cool and reuse v2.Series to get series info and make ListItem, as last resort I can just do what v2 does and make it by hand with all the serialization.
I tried moving imprort to the top, then I tried to make puf in that module but it throws that nakamoriplugin cannot be imported.

**Comment by da3dsoul** [comment]
It's because you can't init puf without a handle, which only plugins have. You can hardcode the URL string to get around it

**Comment by da3dsoul** [comment]
I'm working on that font. It isn't the right size, so I'm resizing it to match the English ones

**Comment by bigretromike** [comment]
strange because injector didnt have to do that
I hardcoded in in the v2 file for now, and will probably push it to dev when i finish with this window, i will tag you so you can look and it and figure wtf.

**Comment by da3dsoul** [comment]
Noto-Migu
![migu](https://i.imgur.com/oQUUg5g.jpg)
Noto-Yu Mincho
![yu mincho](https://i.imgur.com/gVYT0zL.jpg)

**Comment by da3dsoul** [comment]
[skin.estuary_delta.zip](https://github.com/bigretromike/nakamori/files/3206896/skin.estuary_delta.zip)

**Comment by bigretromike** [comment]
both repos updated with same version. 
Imo as nice looking as Mincho is Migu is more readable for me
