### ISSUE TITLE
trakt support

### ISSUE THREAD

**Issue by anzerman** [bigretromike/nakamori#33]
Not sure if this is in the works or not. will you add trakt scrobbling support to the plugin?

**Comment by bigretromike** [comment]
Mind to elaborate more on this manner ?
5 gru 2015 08:40 "anzerman" <notifications@github.com> napisał(a):

**Comment by bigretromike** [comment]
I dont use trakt, so could you write (show) more about what would you like to see be added

**Comment by anzerman** [comment]
Hi,

I guess the best way to understand is the existing Kodi plugin. This works with TV shows but I haven't been able to get it to work with anime. https://github.com/trakt/script.trakt

It may be that this functionality will fall back to the server rather than the plugin but not sure. 
let me know if you need more info :)

**Comment by bigretromike** [comment]
so scrobbling is sending what you watch right ? and you would like to have this in nakamori ?
I my self dont use trakt, but this should be a big problem :+1: 

Let me add this as ToDo but after i smooth things out with primary data exchange

**Comment by bigretromike** [comment]
Oh, btw ? Can we use trakt script but feed it with aditional info ? I will check that also maybe thats the optimal way

**Comment by bigretromike** [comment]
But the main question is trakt support anime that well ? I find it lack greatly with anime support. 
But we will see ;-) can be added anyway

**Comment by AreFinstad** [comment]
hmmmm Trakt supports Anime, most of my shows on JMM is already connected to Anime, sadly the Community linking tool in JMM does not have many links up for review to confirm everyones links and so on.

the main thing with Scrobbling is that it feeds what you are watching aswell as where in the video you are, so if you have a tool with Trakt scrobbling then trakt would know how many minutes you are in the show or whatever. and ofc it would also change the watchstate on trakt when you have hit 80-85% of the episode or movie.

the main this is that it starts feeding this when you start playing and not just at the end when you are done watching.

**Comment by bigretromike** [comment]
the start feed is easy because we use Play() function that use the build-in function so 
play()
feedinfo
play
feedinfo
The main problem would be feed it in middle... but i think you could use the official one, because it MUST get info about what you watch form kodi itself rather than being feed so I will probably work this way :-)

I think it will be not big problem ! :-) I created account on trakt also so noooooo worries

**Comment by bigretromike** [comment]
https://github.com/bigretromike/nakamoriplugin/issues/57#issuecomment-172265451

**Comment by bigretromike** [comment]
- [ ] voting 
- [ ] scrobbling

**Comment by bigretromike** [comment]
The thing that just kill me was that JMM dont support trakt voting... awww
Sorry but Voting is out for now.

**Comment by bigretromike** [comment]
Using official trakt plugin break compatibility. 
But if that will work its better than inventing wheel again ;-)
Working on it

**Comment by bigretromike** [comment]
https://github.com/japanesemediamanager/jmmserver/pull/211

After this merge Nakamori and JMM will have ability to do Scrobbling ;-)

**Comment by bigretromike** [comment]
@anzerman @AreFinstad Are you guys interested in Voting via Trakt also? 
Btw. The problem with trakt I see is that in JMM there is alot of series that are set as Movies in Trakt, that why JMM cant figure traktid that way.

**Comment by AreFinstad** [comment]
yeah, trakt voting would be great. and yeah, linking is still a thing that needs to be handled more.
ill review and confirm any link i get on the queue.... sadly noone is sharing links :(

**Comment by bigretromike** [comment]
How can i shear those ?
20 sty 2016 15:59 "AreFinstad" <notifications@github.com> napisał(a):

**Comment by AreFinstad** [comment]
you need to link them in JMMD on the main series page. 
if the fields are auto searched by JMM it will not upload always tho for some weird reason.
best way to make sure is to click the change season button and reconfirm the episode number and you are good to go. that will upload to the JMM servers where we can review the links uploaded and then confirm them for everyone. meaning everyone will get the same links that is admin confimed by me or anyone else with the rights.

**Comment by AreFinstad** [comment]
ofc, you can also ask Leo for rights on that... remember to send him your AniDB account name in that case.

**Comment by bigretromike** [comment]
I probably dont need it to spoof it for test purpose :-)
Just asking how its done

**Comment by bigretromike** [comment]
Currently JMMServer dont support 'movies' only 'episodes' in Trakt. This will need to be fixed on JMM Server side.

**Comment by bigretromike** [comment]
API is not fully implemented inside JMM Server:
https://github.com/japanesemediamanager/jmmserver/issues/116#issuecomment-183766578

Thats why scroobing dont work with them. And we want to change that ;-)

**Comment by bigretromike** [comment]
Added this: https://github.com/bigretromike/nakamori/commit/95cfef822503116bdc8ece0226b9f703e5ca0395

Probably need to tweak it a bit - but should be ok.
