### ISSUE TITLE
Making some error nice to eye

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#333]
for example, when you are not connected in `main()` loop you: 
`raise RuntimeError(plugin_localize(30155)) `

But pop up ugly confusing shit.
![error](https://user-images.githubusercontent.com/6052025/58322805-54e82a80-7e22-11e9-911f-3312ccbbcaa8.png)

**Comment by da3dsoul** [comment]
This could one of two issues. Either I fucked up with my parameters to eh.exception, or the resources don't translate that into something useable.

**Comment by bigretromike** [comment]
I hope that you will look into it in near future, because I wouldn't want to go back to previous ancient error handling method.

**Comment by bigretromike** [comment]
Looks like this was fixed;
I just double check it;
