### ISSUE TITLE
Watch marks dissapears from Series when navigating Filter

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#334]
Step-by-step:
- enter 'ALL'
- Remember which series are marked as watched
- Enter any series
- Navigate to '..' or go back (backspace)
- The Series that was marked as watch are missing icon the indicate being watched

To refresh you need to '..' from Filter and enter it again.

**Comment by da3dsoul** [comment]
That sounds like a Kodi big, since that is cached by Kodi when you back into a filter

**Comment by bigretromike** [comment]
Please no... in this rate I will move to mpv...

**Comment by da3dsoul** [comment]
I know how to fix it, but it'll increase your load time in All

**Comment by bigretromike** [comment]
is this fix or workaround ? because I almost made issue 👍

**Comment by bigretromike** [comment]
It's not only in 'All' also seasons and its only affect 'Watched flag'

**Comment by da3dsoul** [comment]
Workaround. You disable directory caching

**Comment by bigretromike** [comment]
I did? So its strange it affects only 1 type of flag. Pushing ?

**Comment by da3dsoul** [comment]
The workaround is to disable caching. It hasn't been done yet. That was prolly a language barrier issue.

**Comment by bigretromike** [comment]
more like a mental shortcut issue.

**Comment by bigretromike** [comment]
This does not affect `Search` yet, disabling cache don't resolve issue in `ALL` - it looks more and more that's not Kodi fault.

**Comment by bigretromike** [comment]
My bad, disabling does resolve it - so it is a Kodi bug after all.

**Comment by bigretromike** [comment]
@da3dsoul looks like it could be our issue
I wanted to create the smallest possible example of the issue. 
I used my previouse code from pull request, and while using `cachetodisk` the issue is not present. 
[plugin.video.14573.zip](https://github.com/bigretromike/nakamori/files/3226237/plugin.video.14573.zip)

**Comment by bigretromike** [comment]
Updated version I set watch icon as we do currently. 
It could be something with your ListItem custom object. not sure.
I don't have time to snip your code to check whats wrong - also Im unable post this with my current xbmc issue because this prove that nothing wrong there.

[plugin.video.14573_2.zip](https://github.com/bigretromike/nakamori/files/3226326/plugin.video.14573_2.zip)

**Comment by da3dsoul** [comment]
I can verify that it doesn't happen on Kodi 17, with or without cache, so regardless, it is Kodi's fault. Kodi is supposed to take extended classes so that you can extend functionality and subscribe to ListItem back end stuff. If that's what causes the issue, then okay, but still not our fault, per say.

**Comment by da3dsoul** [comment]
I'm starting a new job in a few hours, so I've no time to help with this for at least a day.

**Comment by bigretromike** [comment]
Thanks for the info.

I'm hopping when you have time you can make example that show the issue, because I don't want to do offline nakamori version just to show this bug.

**Comment by da3dsoul** [comment]
IKR

**Comment by bigretromike** [comment]
Have a good day at new work

**Comment by da3dsoul** [comment]
You should update the Kodi issue with what we've seen and say we'll keep looking at it and keep them posted.

**Comment by bigretromike** [comment]
While I was writing the update for issue I added your custom ListItem, still no issue. Trying to add DirectoryListing() but now its fails without error ;-)

**Comment by bigretromike** [comment]
Version with copy of DirectoryListing() but not using it because it don't show anything.
Just in case...
[plugin.video.14573_v3.zip](https://github.com/bigretromike/nakamori/files/3226619/plugin.video.14573_v3.zip)

**Comment by bigretromike** [comment]
I was hoping that this would be fixed. 
I'm starting to doubt in that and that its and Kodi issue because I enabled cache all over others Objects and I never was able to reproduce this issue anywhere but `Filter`

Until you find the time to fix it, or user being impact by slower loading times of `Filters` I'm disabling cache for `Filters`.
