### ISSUE TITLE
Average rating for series rating

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#336]
Show what is the average rating from episodes to make your decision easier.

**Comment by da3dsoul** [comment]
APIv3

**Comment by bigretromike** [comment]
Not realy,  im doing this now. Please fix shoko stream end. Its anoying like hell to not being able to skip 

On May 27, 2019 9:52:13 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>APIv3
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/336#issuecomment-496294463

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
How are you doing this now? There's no API for ratings from different sources, except in APIv3.
Also, yes I'll try to get to it today, but I'm busy, so I might not. I have work stuff

**Comment by bigretromike** [comment]
Based of episodes rating 

On May 27, 2019 9:55:18 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>How are you doing this now? There's no API for ratings from different
>sources, except in APIv3.
>Also, yes I'll try to get to it today, but I'm busy, so I might not. I
>have work stuff
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/336#issuecomment-496294954

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
I would avoid using that, but it's still an interesting metric that we could look into

**Comment by bigretromike** [comment]
Added;
