### ISSUE TITLE
Issues in 3.4.0

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#358]
- [x] error when canceling on long shoko init
- [x] Search `sewayaki` enter, enter, go back and keyboard show up, (regression)
- [x] enter Search, right click on query, remove, and keyboard show up
- [x] enter Search, New Search, back - you have to double back to exit search
- [x] A-Z Search, decode :-) (`j`)
~~- [ ] when exiting kodi 17.6 it freeze, ~~~~service regression~~
- [x] 404 in loop

**Comment by bigretromike** [comment]
Search sewayaki enter, enter back keyboard ??? Why

**Comment by bigretromike** [comment]
17.6 exit frezee?

**Comment by bigretromike** [comment]
freeze 17.6:
```
ERROR: CPythonInvoker(12, .../plugin.video.nakamori/nakamoriplugin.py): script didn't stop in 5 seconds - let's kill it
```

**Comment by bigretromike** [comment]
I'm not sure if freeze is nakamori fault or not. Will test that out in few days.

**Comment by bigretromike** [comment]
@da3dsoul could you confirm or denied freezes on ancient_kodi17.6 ?

**Comment by da3dsoul** [comment]
Deny

**Comment by bigretromike** [comment]
looks like the crash is something on my setup.

**Comment by bigretromike** [comment]
log for 404 
```
ERROR: Nakamori|Logger -> HTTP Error 404: Not Found -- Exception: HTTPError at ./script.module.nakamoriplayer/lib/nakamori_player.py::player_loop#L252
```
