### ISSUE TITLE
Rebuild every url/structure

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#363]
Need to rebuild every menu item url.
Because `..` is broken without that.

**Comment by da3dsoul** [comment]
Just add a slash to the end of them

**Comment by bigretromike** [comment]
not really

**Comment by da3dsoul** [comment]
Oh I misunderstood what you meant with this

**Comment by bigretromike** [comment]
the solutions are one of those:
- 1. add parent folder to series url: `plugin/menu/filter/1/series/1`
- 2. overwrite parent folder location - unsure if even possible

I will be rewriting paths so they resemble path that was taken. but that's for tomorrow morning.

**Comment by bigretromike** [comment]
affected: kore, webui
