### ISSUE TITLE
kodi-plugin-routing new version

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#365]
@da3dsoul there been new version release
https://github.com/tamland/kodi-plugin-routing/releases

can we move to official once or do we have to do something ?

**Comment by da3dsoul** [comment]
I need to split and redo my PRs to them, then most of my fixes will make it into the official release

**Comment by bigretromike** [comment]
Yes please do. now its 0.2.3 vs your 0.2.4.

**Comment by bigretromike** [comment]
I saw you rebase it, if PR wont be accepted any chance to rename or change version to something bigger so we don't end up having both with same name/version.

**Comment by bigretromike** [comment]
I think this is handle right now. But I would probably would like it to be fork anyway, currently there is no alternative to this plugin and I don't know how well it will get support. But lets see where we end up with it. 
Closing because we already had issue with not changing names :-) twice.
