### ISSUE TITLE
Routes need to be reworked

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#372]
It was mentioned in #370, but this clearly needs more discussion and thought.

- Routes need to basically mirror the folder structure for Kore (and probably other things) to work right. When it goes up a level, you just cut the last part of the URL off, and vice-versa when entering a folder. (edit: and we dont want double same folder when going one level up)
- They need to make sense.
- They need to not end in a slash or number. This is a Kodi bug, but it still matters.
- They need to support deep, varying trees. Filters are super flexible, and it is kind of a pain for systems that aren't. eg. `/tags/tag/series/episode-types/episodes` and `/All/Group/Group/Series/Episodes` need to both work and follow the other rules.
- They need to be easily debuggable/troubleshootable. I should be able to look at the URL and know what Nakamori is trying to do and why it might be failing.
- They need to be able to handle Filters that Apply at the Series Level.
- They need to be able to handle Groups!

I know you don't use groups, but that's also why it seems that any time you mess with routes or menus, my groups and fancy filters stop working. I don't know if we need to implement Unit Tests or something, but that has long been a problem, and it bothers me every time it happens. Likewise, I imagine it goes both ways, like with your Kore and transcoder support.

**Comment by da3dsoul** [comment]
@bigretromike is there a reason you nested the routes? Does it need to respond to both, or is it mainly accept the lack of parameters?
```
@plugin.route()
@plugin.route()
def do_something()
```
That is what I mean by nesting.

**Comment by bigretromike** [comment]
When I nested something it was for supporting both that ends and don't ends with `/` because thats show kodi add `/` at end when you add item as part of main menu for kodi.

**Comment by da3dsoul** [comment]
Okay, then it's no longer needed. Good to know. Routing "fixed" that.
