### ISSUE TITLE
Can you update the repo for Kod Plugin Routing

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#373]
I fixed a bug that apparently broke someone else's plugin....oops

**Comment by bigretromike** [comment]
looks you already forgot how to do that. 

and you did not update version number - how will it update when its same version ?:-)

**Comment by bigretromike** [comment]
Why in master https://github.com/da3dsoul/kodi-plugin-routing/tree/7c40f79d51aad39fb195847a64de77c6c827f0d4 give 404 ?

**Comment by da3dsoul** [comment]
I don't think you ever showed me but IDR. Anyway busy. Will check it later

**Comment by da3dsoul** [comment]
You grabbed the wrong branch. The master branch is for PRing against tamland's. Development is for nakamori.

**Comment by da3dsoul** [comment]
I updated the pointer, though idk if you wanted that pointed to your fork of my fork....

**Comment by bigretromike** [comment]
your was fine, always. 

So I recall you: you push to stable and once per day repo update itself, you push to master and once every hour dev repo update itself.

**Comment by da3dsoul** [comment]
It is. It was 2.4 now 2.4.2

**Comment by bigretromike** [comment]
can you link it to body build `master` and `stable` ?

**Comment by da3dsoul** [comment]
What? I don't understand

**Comment by bigretromike** [comment]
nevermind.
`stable` had old version, I updated it.
