### ISSUE TITLE
Shortcuts Do Not Work

### ISSUE THREAD

**Issue by ElementalCrisis** [bigretromike/nakamori#375]
Every time I try to use a shortcut I created I get the following error. The content shows up on the main screen but if I try to click a series it errors out. 

![image](https://user-images.githubusercontent.com/9443295/77881518-01015b80-7214-11ea-90d4-770e1339b31b.png)

**Comment by kaigame** [comment]
This was fixed in a dev release, but I've had to switch back to stable due to changes in the dev version.

**Comment by ElementalCrisis** [comment]
That's good to know, what changes made you revert back?

**Comment by kaigame** [comment]
The dev release is currently broken, any large series doesn't load at all,
there was an announcement on discord.

**Comment by ElementalCrisis** [comment]
Ah that's unfortunate. I'm sure @bigretromike and @da3dsoul will get it working in no time.

**Comment by da3dsoul** [comment]
Nope.

**Comment by bigretromike** [comment]
Yeah - its on my list.
Don't worry. its small issue with "/" at the end. I fixed it before I will fix it again.
No current eta, with all the COVID19 outbreaks here its hard to do stuff now :(

**Comment by bigretromike** [comment]
Anyway thanks for posting !
I'm planing to redo some of my old code so it will be handle better (by me) 👍

**Comment by ElementalCrisis** [comment]
No rush, Nakamori is still usable and that's really all that matters.

**Comment by SteveMavic** [comment]
Problem no longer exists I believe?

**Comment by ElementalCrisis** [comment]
Probably, we can close. :)
