### ISSUE TITLE
Error String or Buffer

### ISSUE THREAD

**Issue by ArtexJay** [bigretromike/nakamori#376]
When  I try to use nalamori within Kodi, I get the following error:
 "expected string or buffer at /plugin.video.nakamori/nakamoriplugin.py#L662
This occurred 1 times."

**Comment by da3dsoul** [comment]
In the Kodi log, it should have a bigger stack trace. Can you post that?

**Comment by ArtexJay** [comment]
where, can i find that? I am pretty new to using kodi and shoko

**Comment by da3dsoul** [comment]
Depends on what you're running Kodi on. In Windows, `%appdata%\\Kodi\\kodi.log`

**Comment by ArtexJay** [comment]
[kodi.log](https://github.com/bigretromike/nakamori/files/4726593/kodi.log)

This is the one i found.

**Comment by da3dsoul** [comment]
Says it's an auth error. The default user/pass is Default with a blank password.

**Comment by ArtexJay** [comment]
I tried to re-authenticate within kodi but when i click the button it in the naknomi settings nothing appears. I saw it earlier to day and actually tried to do a clean reinstall of Kodi with Shoko but the field does not appear for me.

**Comment by ArtexJay** [comment]
did a factory reset on the device, it was not trouble.

I have a theory that it might have gotten broken when i altered the account of shoko to include a password. By default it automatically recognizes the default account that shoko used.
