### ISSUE TITLE
Viewtype applied/saved per entry, not per list?

### ISSUE THREAD

**Issue by Andy2244** [bigretromike/nakamori#377]
If i change the viewtype inside a selection _(recently watched, unwatched, seasons)_ for a series/entry, it is only applied to this entry, not set as new default for all entries in the list or globally. It is also saved per entry, so every series/entry now gets it own viewtype, which makes it impossible/annoying to quickly change the view.

Is there a workaround to define the default viewtype for those entries?

PS: This is in 18.8 + 3.5.3

**Comment by da3dsoul** [comment]
Edit the skin

**Comment by da3dsoul** [comment]
Sadly, that's the only way.

**Comment by Andy2244** [comment]
mhh ok

**Comment by da3dsoul** [comment]
Because I'm so nice, and not at all because I've done it myself, here's an example. For estuary, moving these around changes the order. The default is the top https://github.com/phil65/skin.estuary/blob/3b37f5165a28b1c761609fd910a190976c1e6e89/xml/MyVideoNav.xml#L11

**Comment by da3dsoul** [comment]
You can change this in the add-ons folder without compiling anything

**Comment by Andy2244** [comment]
> For estuary, moving these around changes the order.

Also works for Quartz, the order is in the `<views>50,51,52,53,54,55,500,501,502</views>` tag.
