### ISSUE TITLE
[enhancement] better watched detection for external players

### ISSUE THREAD

**Issue by Andy2244** [bigretromike/nakamori#378]
From what i can see nakamori directly marks a item as watched, if a external player closes, independent of the actual playtime or whatever was set in the settings.

Kodi has this "crutch" setting "playcountminimumtime" in playercorefactory.xml to prevent the most obvious faulty cases, where you just quickly open/close a item. If set to a medium value like 19min, works reasonably well, yet nakamori has nothing similar for external players.

So would be nice to either respect this setting or enhance it with a custom percentage based setting for external players.

**Comment by bigretromike** [comment]
Hello, thanks for submit.

Nakamori handled this the way you describe. Sadly the function that I used for it is currently broken in Kodi. 
Let me link the issue:
https://github.com/xbmc/xbmc/issues/16183

This used to work with 17.x 

I will try to look into this and find other `hook` to support it.

**Comment by bigretromike** [comment]
@Andy2244 could you write what Kodi version are you using ?

**Comment by Andy2244** [comment]
18.8

**Comment by bigretromike** [comment]
I'm still waiting for Kodi to fix issue. Sorry for that.
