### ISSUE TITLE
Install Repo Down?

### ISSUE THREAD

**Issue by ElementalCrisis** [bigretromike/nakamori#379]
We've gotten a reports from users who are trying to install Nakamori and getting an error message regarding the repo being down.

Let us know if you need us to host it if hosting is the issue.

**Comment by bigretromike** [comment]
nah, I was in middle of migration. which ended.
should be good. thanks for offering.

**Comment by ElementalCrisis** [comment]
Awesome, glad to hear its back up!

**Comment by bigretromike** [comment]
Don't worry. Thanks for issue. I could send notification that I will be down, but with the  Pandemic it's hard to organize. 
Stay safe

**Comment by ElementalCrisis** [comment]
You too!
