### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by ashmitsinghsaggu** [bigretromike/nakamori#380]
it is asking me to enter an shoko server ip address and port by default its 127.0.0.1
port 8.1.1.1. what should i do???

**Comment by kaigame** [comment]
You do have Shoko Server installed right? Nakamori won't work on it's own, it's a frontend for the server portion

**Comment by ashmitsinghsaggu** [comment]
how to install it? :(

**Comment by ashmitsinghsaggu** [comment]
how to install it? :(

**Comment by kaigame** [comment]
there is plenty of documentation on the website,

Go to the website: https://shokoanime.com/ and follow the instructions

**Comment by da3dsoul** [comment]
He came on discord. Resolved as it can be.
