### ISSUE TITLE
Nakamori 3.6.0 from DEV Repo has Broken "Related Series" Folders.

### ISSUE THREAD

**Issue by Kristijan1001** [bigretromike/nakamori#398]
The newest version of the addon has broken the series that a grouped up with eachother. For example going into 
Nakamori > A-Z All > Dragon Ball > Selecting a Dragon Ball Series does nothing, kodi does a quick please wait and nothing happens. So you are not able to view the episodes.

For single series it works fine, this only breaks the ones that are grouped each other. On the older version the grouping works fine and selecting the series opens all the episodes just fine. But the issue with that version is that Recently added or favorites is not working.

Tested on Kodi 17.9 Leia

**Comment by bigretromike** [comment]
Hello,
I'm in middle of work related to nakamori, but please provide ShokoServer version.

**Comment by bigretromike** [comment]
Also please have on mind, that "DEV" repo was always intended to be broken before getting into stable.

**Comment by da3dsoul** [comment]
This came over from discord. He's tried 3.5.3 and the dev version. He's using the latest stable of shoko: 4 something... doesn't matter. It hasn't changed in a long time

**Comment by bigretromike** [comment]
> 
> 
> This came over from discord. He's tried 3.5.3 and the dev version. He's using the latest stable of shoko: 4 something... doesn't matter. It hasn't changed in a long time

shoko latest stable would be 4.1.0, probably he is using grouping as you did before.
We are in middle fixing nakamori to work with currect shoko+kodi combo, should be a few weeks.
Thanks for the info

**Comment by Kristijan1001** [comment]
> > This came over from discord. He's tried 3.5.3 and the dev version. He's using the latest stable of shoko: 4 something... doesn't matter. It hasn't changed in a long time
> 
> shoko latest stable would be 4.1.0, probably he is using grouping as you did before.
> We are in middle fixing nakamori to work with currect shoko+kodi combo, should be a few weeks.
> Thanks for the info

I am using the latest stable build 4.1.0. Thanks for the reply. Glad it is being worked on.

**Comment by bigretromike** [comment]
@Kristijan1001 could i ask why you stick with kodi 17.9 ? is that media box or your preference ?

**Comment by Kristijan1001** [comment]
@bigretromike sorry i meant 18.9 lol. I am on it cause Nakamori works the best for it.

**Comment by bigretromike** [comment]
@Kristijan1001 I'm asking you for a bit more time. I'm doing really big thing for nakamori, and the ETA is on the last day of September, but thanks to @SteveMavic support, I'm more than sure that we will hit release much much sooner.

**Comment by bigretromike** [comment]
mean time im more than sure than switching grouping series option in ShokoServer/Desktop should fix this issue .

**Comment by da3dsoul** [comment]
Aye. Thanks @SteveMavic. I feel bad for abandoning this, but I'm not changing my mind. You can shoot me an email if you ever have questions. I did this for a good while. My email is my username at Gmail.

**Comment by Kristijan1001** [comment]
@bigretromike Any updates on this ?

**Comment by Kristijan1001** [comment]
> @Kristijan1001 yes, its in production. I got covid so I had to stop it for a bit. But I'm getting better and better, so I will resume work in next week.

Sorry to hear u got covid. Looking forward to the updated :).
