### ISSUE TITLE
Restore Shoko Menu

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#454]
- #475
    - #482
    - #483
    - #484
    - #485
    - #486
- #476
    - #487
    - #488
    - #489
    - #490
- #477
    - #491
    - #492
    - #493
    - #503
        - #504
- #478
    - #494
    - #495
- #479
    - #496
- #480
    - #497
    - #498
- #481
    - #499
    - #500

**Comment by ablakers** [comment]
I installed 4.0.0 from the zip before it's on the repo and I'm getting an error whenever I try to load All

`2021-11-01 17:51:19.021 T:15916   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\ablakers\AppData\Roaming\Kodi\addons\plugin.video.nakamori\nakamoriplugin.py", line 509, in <module>
                                                       plugin.run()
                                                     File "C:\Users\ablakers\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\ablakers\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\ablakers\AppData\Roaming\Kodi\addons\plugin.video.nakamori\nakamoriplugin.py", line 90, in list_groups_by_filter_id
                                                       y = kodi_models.list_all_groups_by_filter_id(filter_id)
                                                     File "C:\Users\ablakers\AppData\Roaming\Kodi\addons\plugin.video.nakamori\models\kodi_models.py", line 864, in list_all_groups_by_filter_id
                                                       list_of_listitems.append((g.id, ThisType.group, get_listitem_from_group(g)))
                                                     File "C:\Users\ablakers\AppData\Roaming\Kodi\addons\plugin.video.nakamori\models\kodi_models.py", line 140, in get_listitem_from_group
                                                       set_rating(li, rate_type='anidb', rate_value=float(x.rating), votes=int(x.votes), default=True)
                                                   TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
                                                   -->End of Python script error report<--`

I can go through Seasons, Years, Tags, Search, etc to find titles and I can start playing them from there, although the text in Nakamori's context menu items isn't showing for any except _Mark as (Un)watched_ and _-Below are Kodi's Items-_ I tried sideloading nakamori.script and nakamori.service in case they're still needed but got dependency errors.

Kodi 19.3 on Windows 10 21H1 x64

**Comment by bigretromike** [comment]
@ablakers thank you for installing. 

for issue with "All" Are you maybe using "group series" option in shoko ?
About context menu, there is less items for sure, because I'm readding them back one by one (which one you are missing the most ?)
No, there is not need to sideload script and service - everything needed for nakamori will be inside one package so there wont be any more issues with mixed version or too much modulation where its not needed.

**Comment by bigretromike** [comment]
@ablakers the 'All' should work now, but if your are using "series grouping" options inside shoko you will probably have to give me a more time because last time I tried to switch to grouping anidb ban me thanks to shoko ;-)

**Comment by ablakers** [comment]
Turning off Shoko's series grouping for now gets 'All' working again, thanks

**Comment by bigretromike** [comment]
I'm reimporting my collection to test it against series grouping settings - but thank you for feedback

**Comment by bigretromike** [comment]
@SteveMavic interested in this, this shouldn't be a hard thing to implement and you could play with `listitem` items; its scheduled on 4.1rc so nothing that need to be done asap

**Comment by bigretromike** [comment]
Looks like you done it @SteveMavic
