### ISSUE TITLE
Kodi no longers plays the files locally but streams them instead. Which results in no external subtitles. & Tags are broken and show as "Other"

### ISSUE THREAD

**Issue by Kristijan1001** [bigretromike/nakamori#470]
This is something @da3dsoul did in the older version, to make the files play locally instead. This makes it so you can watch the series with subtitles if a external subtitle file is present. 

![image](https://user-images.githubusercontent.com/24441639/140603841-ba5bdca5-2aef-4f63-bcd9-90a7d1ca7474.png)

Also tags are broken and show as "Other" 

![image](https://user-images.githubusercontent.com/24441639/140603894-67012c41-5de8-43ed-9b55-63f573f6f6b2.png)

**Comment by bigretromike** [comment]
First part is understandable. 

The tag part confuse me a bit.

@Kristijan1001 Could you write what you expect and what you get instead ?

**Comment by bigretromike** [comment]
@Kristijan1001 I added support for playing files that you have mapped or have access to them as it was before. ds doesn't know what he is talking about, there were never a function/hack/tweak that forced kodi to play files from its library - maybe he mixed up project he put his fingers in ?! 

I would like to ask for information needed to fix? `tags` and `Other` ?

**Comment by Kristijan1001** [comment]
> @Kristijan1001 I added support for playing files that you have mapped or have access to them as it was before. ds doesn't know what he is talking about, there were never a function/hack/tweak that forced kodi to play files from its library - maybe he mixed up project he put his fingers in ?!
> 
> I would like to ask for information needed to fix? `tags` and `Other` ?

The place below the covers or wherever depending on the theme you have. Where it used to say for example "Ecchi, Action, Shounen" Now it only says "Other" and nothing else.

**Comment by bigretromike** [comment]
Could you check how you have your Tag Filtration setup ?

![obraz](https://user-images.githubusercontent.com/6052025/140619546-fd305455-f721-44ac-bab7-57e4785e0d39.png)

**Comment by Kristijan1001** [comment]
> @Kristijan1001 Could you check how you have your Tag Filtration setup ?
> 
> ![obraz](https://user-images.githubusercontent.com/6052025/140619546-fd305455-f721-44ac-bab7-57e4785e0d39.png) ![obraz](https://user-images.githubusercontent.com/6052025/140619588-f035b879-bfac-4cef-bd9c-874de0c559d9.png)
> 
> For best results I would suggest deleting settings from (win): appdata\Roaming\Kodi\userdata\addon_data\plugin.video.nakamori\

Yes u are right. Sorry for the trouble. There was something messed up with the theme i was using.

**Comment by bigretromike** [comment]
Glad to hear that plugin is working as intended.
Fell free to leave feedback or request for functions that were in older version but are not :-)
