### ISSUE TITLE
[Feature Request] Please remove the "Episodes" & "Specials" Folders or give us an option to turn them off. They ugly and would rather have all episodes/specials in one folder.

### ISSUE THREAD

**Issue by Kristijan1001** [bigretromike/nakamori#471]
This is really ugly bruh lol

![kodi_N74NALYaZo](https://user-images.githubusercontent.com/24441639/140627480-a35dff4c-7116-4bd2-ba69-b860490a86d0.png)

![kodi_rfhWBcX2JE](https://user-images.githubusercontent.com/24441639/140627481-1bff2169-0eaf-4a4b-a043-6d2ccec7dc1c.png)

**Comment by bigretromike** [comment]
@Kristijan1001 You requested, I delivered; 
Also a notice: if "ugly" referred to pictures - you could replaced those with ease with your wont picture pack, if not then I got setting for you - the "default" aka "server sort" with this option turn off (Browsing - Tweaks - Group episode types together) is funky, to mitigate this use different sort method (arrow to the left inside series view) or enable "Add Episode Number to Title" so you will know what you are watching.

**Comment by Kristijan1001** [comment]
> @Kristijan1001 You requested, I delivered; Also a notice: if "ugly" referred to pictures - you could replaced those with ease with your wont picture pack, if not then I got setting for you - the "default" aka "server sort" with this option turn off (Browsing - Tweaks - Group episode types together) is funky, to mitigate this use different sort method (arrow to the left inside series view) or enable "Add Episode Number to Title" so you will know what you are watching.

Thanks alot for your work. Yeah another picture would work also. Can the Anime Cover be pulled for a picture instead of the text covers.

**Comment by bigretromike** [comment]
> 
> 
> > @Kristijan1001 You requested, I delivered; Also a notice: if "ugly" referred to pictures - you could replaced those with ease with your wont picture pack, if not then I got setting for you - the "default" aka "server sort" with this option turn off (Browsing - Tweaks - Group episode types together) is funky, to mitigate this use different sort method (arrow to the left inside series view) or enable "Add Episode Number to Title" so you will know what you are watching.
> 
> Thanks alot for your work. Yeah another picture would work also. Can the Anime Cover be pulled for a picture instead of the text covers.
> 
> Edit, Just checked previous version, and this is how it used to work. It just loaded the anime cover and let you chose episodes or specials.

@Kristijan1001 
Sorry as English is not may native language, but I don't quite grasp the idea. It used same pictures as it does now - but those where in resource pack. 
Do I understand it correctly, that you want nakamori to use series cover (from shoko) for episode types (ex. episodes, specials, credits) instead of now-default once (text "episodes", text "specials", text "credits") ?

**Comment by Kristijan1001** [comment]
> > > @Kristijan1001 You requested, I delivered; Also a notice: if "ugly" referred to pictures - you could replaced those with ease with your wont picture pack, if not then I got setting for you - the "default" aka "server sort" with this option turn off (Browsing - Tweaks - Group episode types together) is funky, to mitigate this use different sort method (arrow to the left inside series view) or enable "Add Episode Number to Title" so you will know what you are watching.
> > 
> > 
> > Thanks alot for your work. Yeah another picture would work also. Can the Anime Cover be pulled for a picture instead of the text covers.
> > Edit, Just checked previous version, and this is how it used to work. It just loaded the anime cover and let you chose episodes or specials.
> 
> @Kristijan1001 Sorry as English is not may native language, but I don't quite grasp the idea. It used same pictures as it does now - but those where in resource pack. Do I understand it correctly, that you want nakamori to use series cover (from shoko) for episode types (ex. episodes, specials, credits) instead of now-default once (text "episodes", text "specials", text "credits") ?

Here is the example from previous version nakamori. Basically once you open it has the anime cover instead of "special" cover.

![image](https://user-images.githubusercontent.com/24441639/140644699-c1fa2343-5e1a-4c3d-ad2d-d5fdbc7cca23.png)

**Comment by Kristijan1001** [comment]
This is how it is now:

![image](https://user-images.githubusercontent.com/24441639/140644738-08a94b6a-c6c0-4a79-9fc5-035daa0b88cb.png)

**Comment by Kristijan1001** [comment]
I think the older version is using the KODI built in Seasons Manager to handle this, where as the newer version has custom folders names "episodes" & "specials".

**Comment by bigretromike** [comment]
> 
> 
> I think the older version is using the KODI built in Seasons Manager to handle this, where as the newer version has custom folders named "episodes" & "specials".

No, you are wrong on this.
It use the same thing as I wrote it then and now, but then I used "seasons" category and different sort methods. Now as I rewrite most of junk code left from to many abstractions I'm adding stuff a bit different. 
Names were taken from shoko directly, now we parse them and could even translate. 

The goal is not rewrite Nakamori in the way it used to work, but some parts are going back into it - nothing to worry about.

try b11;

**Comment by bigretromike** [comment]
or even b12 ;-)

**Comment by Kristijan1001** [comment]
> > I think the older version is using the KODI built in Seasons Manager to handle this, where as the newer version has custom folders named "episodes" & "specials".
> 
> No, you are wrong on this. It use the same thing as I wrote it then and now, but then I used "seasons" category and different sort methods. Now as I rewrite most of junk code left from to many abstractions I'm adding stuff a bit different. Names were taken from shoko directly, now we parse them and could even translate.
> 
> The goal is not rewrite Nakamori in the way it used to work, but some parts are going back into it - nothing to worry about.
> 
> try b11;

Was just about to post u already uploaded new one gonna check out now

**Comment by Kristijan1001** [comment]
> or even b12 ;-)

Looks better :), Covers are still not there.

![image](https://user-images.githubusercontent.com/24441639/140645530-2059245d-0570-4222-8ab0-7c994f2c5c9b.png)

**Comment by bigretromike** [comment]
> 
> 
> > or even b12 ;-)
> 
> Looks better :), Covers are still not there.
> 
> ![image](https://user-images.githubusercontent.com/24441639/140645530-2059245d-0570-4222-8ab0-7c994f2c5c9b.png)

Because you didn't change your settings inside: Browsing > Tweaks > Use Series art.... (you need to have view higher than Basic)

**Comment by Kristijan1001** [comment]
> > > or even b12 ;-)
> > 
> > 
> > Looks better :), Covers are still not there.
> > ![image](https://user-images.githubusercontent.com/24441639/140645530-2059245d-0570-4222-8ab0-7c994f2c5c9b.png)
> 
> Because you didn't change your settings inside: Browsing > Tweaks > Use Series art.... (you need to have view higher than Basic)

Haha perfect it works. I didn't expect for you to add a whole new setting in 2 minutes. Thats why didnt bother to check lol. Thanks for the awesome updates. Check the android post i made there seems to be an issue.

**Comment by Kristijan1001** [comment]
Really bad nitpick from me. If we can capitalize the "s" in specials. If not all good this is just me being petty at this point, u did an awesome job :) 

![image](https://user-images.githubusercontent.com/24441639/140645737-9cbbfcaa-9eac-43ef-82a5-ccb1ae279849.png)

**Comment by bigretromike** [comment]
I will probably check later why you have "seasons" in left top corner while "seasons" are not documented. 
But that's for later.

Glad you liked it.

Check B13 for capital thing, you are right, default KODI naming is Capital for specials;

**Comment by bigretromike** [comment]
@Kristijan1001 btw, which skin are you using ? It will help narrow the "Season" lock thing

**Comment by Kristijan1001** [comment]
> @Kristijan1001 btw, which skin are you using ? It will help narrow the "Season" lock thing


Thank you. It works perfectly now, but anyway The Kodi skin is Aura:

https://forum.kodi.tv/showthread.php?tid=328558

For Matrix need to use this one (This is why my tags didn't work earlier, cause the skin is a port and it had them broken):

https://www.reddit.com/r/Addons4Kodi/comments/mcmife/project_aura_kodi_matrix_skin_release/

**Comment by bigretromike** [comment]
oh, that could explain why I knew that skin but didn't find it for matrix. 
lot of skins ain't still ported sadly.

If there any more suggestion what was used and helpful from previous nakamori version that you would like to see back in 4.0.0 fell free to write about it 👍 
every feedback count

**Comment by bigretromike** [comment]
"lock view: seasons" is hardcoded sort method inside aurora skin. Default skin behaviour is different - it allow nakamori to allow/disallow valid sort methods. nothing to do with it.

**Comment by Kristijan1001** [comment]
> oh, that could explain why I knew that skin but didn't find it for matrix. lot of skins ain't still ported sadly.
> 
> If there any more suggestion what was used and helpful from previous nakamori version that you would like to see back in 4.0.0 fell free to write about it 👍 every feedback count

As of right now everything seems to be working fine. I can't think off anything from the old versions that is needed.
As for feature add i would go with if possible:

- Possibility of Streaming .srt .ass etc. Subtitles that are picked right from the folder where the episode is located.
- Make Kodi Generate "Screen Captures" for episodes. So it has screen captures instead of this:

![image](https://user-images.githubusercontent.com/24441639/140647456-99f00cb5-44a4-4d9c-9b47-90c27f9eb811.png)

**Comment by bigretromike** [comment]
I could replace that ugly yet funny picture with something else on nakamori side, but generating thumbnails for episodes should be a ShokoServer task, they were retiring from using tvdb anyway and were looking for replacment. 

Thats should be a task for Shokoserver because each kodi instant would do this job again and again (including your mobile android).

Possiblity of streaming subtitles are there - by accident I would tell. If you would map your collection on phone the same way as you have it on your ShokoServer machine then Nakamori would access those files directly without streaming them thru ShokoServer WebAPI, that way kodi would look up for name_of_your_anime_episode.*  subs and load those. 

But I remember that I used to inject subtitles anyway into kodi, but that was a very hacky way of doing so. You had to add subtitles extension to ShokoServer settings as video, that way they would be surf as "files" under episode and Nakamori would help you pick them out of normal media files. That was very hacky way to do. I will look into those but until shoko support subtitles in a proper way (external subtitles that is) there is nothing I could do without abusing both ends.

**Comment by Kristijan1001** [comment]
> I could replace that ugly yet funny picture with something else on nakamori side, but generating thumbnails for episodes should be a ShokoServer task, they were retiring from using tvdb anyway and were looking for replacment.
> 
> Thats should be a task for Shokoserver because each kodi instant would do this job again and again (including your mobile android).
> 
> Possiblity of streaming subtitles are there - by accident I would tell. If you would map your collection on phone the same way as you have it on your ShokoServer machine then Nakamori would access those files directly without streaming them thru ShokoServer WebAPI, that way kodi would look up for name_of_your_anime_episode.* subs and load those.
> 
> But I remember that I used to inject subtitles anyway into kodi, but that was a very hacky way of doing so. You had to add subtitles extension to ShokoServer settings as video, that way they would be surf as "files" under episode and Nakamori would help you pick them out of normal media files. That was very hacky way to do. I will look into those but until shoko support subtitles in a proper way (external subtitles that is) there is nothing I could do without abusing both ends.

Seems fair. For the Thumbnails wouldn't mind that tbh, maybe have it as an optional option. The way I use Kodi, is only 1 Build, That I FTP to all my devices when needed. It would be a bandaid fix for thumbnails, but better than none i guess ?

**Comment by bigretromike** [comment]
Thumbnails are something ShokoServer need to address - from remote database or generated locally.
But I will add option to replace that white image for something inside image/icon pack so end user can replace it also. It look very back with dark themed skin.

**Comment by Kristijan1001** [comment]
> Thumbnails are something ShokoServer need to address - from remote database or generated locally. But I will add option to replace that white image for something inside image/icon pack so end user can replace it also. It look very back with dark themed skin.

Yeah, That will work. Could it be done like this:

![image](https://user-images.githubusercontent.com/24441639/140648327-1606c6ba-0afb-4ceb-837a-c0bff3000813.png)

**Comment by bigretromike** [comment]
The cover you are marking is thumbnail for episode or fanart depending on view you are using.
Also its based on skin you use.

I will try to do something better than 90% being white in dark theme ;-)

**Comment by bigretromike** [comment]
@Kristijan1001 https://github.com/bigretromike/nakamori/issues/473
I'm currently not replacing episode thumb with series covers - but will consider it a bit later. 

I will also reconsider generating thumbnails if shokoserver wont handle it in anyway, but its a good idea to make issue on shokoserver issue page. 

One of the functionality will end up in Nakamori if shoko wont provide proper thumbnails - until then, those two images from default image/icon pack need to stick.

**Comment by Kristijan1001** [comment]
> @Kristijan1001 #473 I'm currently not replacing episode thumb with series covers - but will consider it a bit later.
> 
> I will also reconsider generating thumbnails if shokoserver wont handle it in anyway, but its a good idea to make issue on shokoserver issue page.
> 
> One of the functionality will end up in Nakamori if shoko wont provide proper thumbnails - until then, those two images from default image/icon pack need to stick.

Thanks. Either way its no that big of a deal. I have brought this up already in the Shoko Discord server months ago. ¯\_(ツ)_/¯

**Comment by bigretromike** [comment]
> 
> 
> > @Kristijan1001 #473 I'm currently not replacing episode thumb with series covers - but will consider it a bit later.
> > I will also reconsider generating thumbnails if shokoserver wont handle it in anyway, but its a good idea to make issue on shokoserver issue page.
> > One of the functionality will end up in Nakamori if shoko wont provide proper thumbnails - until then, those two images from default image/icon pack need to stick.
> 
> Thanks. Either way its no that big of a deal. I have brought this up already in the Shoko Discord server months ago. ¯\_(ツ)_/¯

Months? It's been on "need to do" for years ;-)

Fell free to post ideas/feedback here on github, I don't promise to fix/add/patch everything as quick as I did today, but I will do my best to "keep on keeping on" :)

**Comment by Kristijan1001** [comment]
> > > @Kristijan1001 #473 I'm currently not replacing episode thumb with series covers - but will consider it a bit later.
> > > I will also reconsider generating thumbnails if shokoserver wont handle it in anyway, but its a good idea to make issue on shokoserver issue page.
> > > One of the functionality will end up in Nakamori if shoko wont provide proper thumbnails - until then, those two images from default image/icon pack need to stick.
> > 
> > 
> > Thanks. Either way its no that big of a deal. I have brought this up already in the Shoko Discord server months ago. ¯_(ツ)_/¯
> 
> Months? It's been on "need to do" for years ;-)
> 
> Fell free to post ideas/feedback here on github, I don't promise to fix/add/patch everything as quick as I did today, but I will do my best to "keep on keeping on" :)

Yeah all good. If i think of something else i'll post it here. You should probably update the official site with this version, also Repo seems to be wiped ? 

Not many people will be able to find it here on github.

**Comment by bigretromike** [comment]
that's a good point.
I postpone it because I had a felling not everything is working correct.
But that's probably best next goal.

**Comment by bigretromike** [comment]
@Kristijan1001 DEV-Repo is up and running btw.
