### ISSUE TITLE
[BUG] Nakamori on Kodi Android, Doesn't play any files. 

### ISSUE THREAD

**Issue by Kristijan1001** [bigretromike/nakamori#472]
Nakamori doesn't play anything on Android Phone, Connected to the same network. It just says error check the logs. Can't find the logs on the phone, there are not in the same as the PC Kodi for some reason.

Tested on Latest Kodi Version Clean Install.

**Comment by bigretromike** [comment]
b13, is working fine;
try those locations:
```
    /data/org.xbmc.kodi/cache/temp/kodi.log
    /sdcard/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
    /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log   <-- mine is here
```

**Comment by Kristijan1001** [comment]
> kodi 19.3.0 (git:20211024) + nakamori 4.0.0-b13, is working fine; try those locations for log and include it.
> 
> ```
>     /data/org.xbmc.kodi/cache/temp/kodi.log
>     /sdcard/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
>     /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log   <-- mine is here
> ```
> 
> It could be fault from:
> 
> * access issue
> * network issue
> * hardware doesn't support decoding of that file

I will try now. Also want to mention i tested

> kodi 19.3.0 (git:20211024) + nakamori 4.0.0-b13, is working fine; try those locations for log and include it.
> 
> ```
>     /data/org.xbmc.kodi/cache/temp/kodi.log
>     /sdcard/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
>     /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log   <-- mine is here
> ```
> 
> It could be fault from:
> 
> * access issue
> * network issue
> * hardware doesn't support decoding of that file

Latest one just checked it works. This is weird because the earlier one didn't work, I even made sure to test it with clean kodi before posting it, still didn't work. 


Latest version works fine.

**Comment by Kristijan1001** [comment]
I have a question not related to the topic. Didn't want to make new post just to ask. What is Eigakan ? I see it mentions subtitles and stuff, but can't find anything on Google about it. Is it possible to stream .srt .ass subtitles over Kodi, cause as of right now and how it worked in the past, I can only do that on my PC since it is a direct play and not streamed.

**Comment by bigretromike** [comment]
> 
> 
> > kodi 19.3.0 (git:20211024) + nakamori 4.0.0-b13, is working fine; try those locations for log and include it.
> > ```
> >     /data/org.xbmc.kodi/cache/temp/kodi.log
> >     /sdcard/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
> >     /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log   <-- mine is here
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It could be fault from:
> > 
> > * access issue
> > * network issue
> > * hardware doesn't support decoding of that file
> 
> Latest one just checked it works. This is weird because the earlier one didn't work, I even made sure to test it with clean kodi before posting it, still didn't work.
> 
> Latest version works fine.

It could be around ~ 5-6 version ago that I fixed one typo related with playing items, maybe it was that.

**Comment by bigretromike** [comment]
> 
> 
> I have a question not related to the topic. Didn't want to make new post just to ask. What is Eigakan ? I see it mentions subtitles and stuff, but can't find anything on Google about it. Is it possible to stream .srt .ass subtitles over Kodi, cause as of right now and how it worked in the past, I can only do that on my PC since it is a direct play and not streamed.

Glad you asked, its not strange that you couldn't fine any information about it.
It was my side project related with nakamori. 

Basically it was a ffmpeg wrapper with small api server that would stream anything from ShokoServer to Kodi thru Nakamori with basic control. It was working fine with my only TV that didn't handle all those fancy codecs etc. I wrote it because there werent any other options for me (as I dont use Plex, jellyfin was still new, emby never worked) and I wanted to keep everything inside Kodi. 
In month or two I will reconsider removing all options related to it or resurrect project. 

Also you seeing it because Aura don't support the new settings from K19 and show every hidden setting there is.
