### ISSUE TITLE
Setting for replacing "no thumb for episode" image to something from icon/image pack

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamori#473]

**Comment by bigretromike** [comment]
New option in settings: 
Browser -> Tweaks -> Replace missing image...

**Comment by Kristijan1001** [comment]
> New option in settings: Browser -> Tweaks -> Replace missing image...

How do use the Image/Icon pack from where ? How would I go in setting a custom image ?

**Comment by bigretromike** [comment]
Or if they are "excelent" I can add them as `default` ;-)

**Comment by Kristijan1001** [comment]
> Or if they are "excelent" I can add them as `default` ;-)

Haha nah its fine its just a black background rlly generic.

**Comment by bigretromike** [comment]
^_^
