### ISSUE TITLE
CAddonInstallJob[plugin.video.nakamori]: The dependency on xbmc.python version 2.14.0 could not be satisfied.

### ISSUE THREAD

**Issue by bananathepirate** [bigretromike/nakamori#506]
https://github.com/bigretromike/nakamori/releases/tag/4.0.0

Kodi v19.3 (Matrix)

manual installation failed, wrong python version

**Comment by ElementalCrisis** [comment]
So I had to manually install [script.module.routing](https://mirrors.kodi.tv/addons/matrix/script.module.routing/) to get it to install but its crashing and erroring quite a bit. 

```
2022-02-01 17:19:37.041 T:161008   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Ricky\AppData\Roaming\Kodi\addons\plugin.video.nakamori\nakamoriplugin.py", line 509, in <module>
                                                       plugin.run()
                                                     File "C:\Users\Ricky\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\Ricky\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\Ricky\AppData\Roaming\Kodi\addons\plugin.video.nakamori\nakamoriplugin.py", line 90, in list_groups_by_filter_id
                                                       y = kodi_models.list_all_groups_by_filter_id(filter_id)
                                                     File "C:\Users\Ricky\AppData\Roaming\Kodi\addons\plugin.video.nakamori\models\kodi_models.py", line 864, in list_all_groups_by_filter_id
                                                       list_of_listitems.append((g.id, ThisType.group, get_listitem_from_group(g)))
                                                     File "C:\Users\Ricky\AppData\Roaming\Kodi\addons\plugin.video.nakamori\models\kodi_models.py", line 140, in get_listitem_from_group
                                                       set_rating(li, rate_type='anidb', rate_value=float(x.rating), votes=int(x.votes), default=True)
                                                   TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
                                                   -->End of Python script error report<--
                                                   
```

**Comment by bigretromike** [comment]
@bananathepirate sorry for keeping you wait. Did you resolved the problem or its still there ?

I didn't test nakamori agains 19.3, will try to do it

**Comment by bigretromike** [comment]
@bananathepirate no issue with installing it from repository: shokunin.monogatari.pl/repo/repository.nakamori.zip

Which matrix version are you using ? - we stopped using hacked/tweaked routing plugin version that ds did, we using official one:
https://kodi.tv/addons/matrix/script.module.routing

**Comment by bigretromike** [comment]
@ElementalCrisis @bananathepirate 
I checked both version for WIndows (32 & 64-bit) both works fine when installing manually - by installing from zip, from "latest releases" or from repostiory. 

Double check if you dont use older nakamori version, hacked routing plugin or non vanilla matrix release. 
If needed try portable kodi with profile switch to use clean profile without wiping yours. 

Nakamori 4.x needs Python 3.x Kodi version.

**Comment by bigretromike** [comment]
@ElementalCrisis thats super strange. Are you wiping profile on your machine when deleting kodi ?

I tried it on two different machines with same results - still cannot reproduce this issue :(

**Comment by ElementalCrisis** [comment]
I was able to get it working.

I recently had to reinstall Windows so installed it on a fresh copy, used the repo link from your site and installed Nakamori. No install errors or running errors like before. 

I have no idea what is different about this time vs last time, lol.

I'll get a blog post written up this weekend for it. Let me know if there is anything in particular, you'd like me to mention.

**Comment by bigretromike** [comment]
@ElementalCrisis nothing particular - maybe other than something along "if you have issue with Nakamori, please use github to report issue, as the Nakamori Stuff ain't present on Discord", the older I get the less time for "messing with code" I have, but I don't plan to remove Nakamori from my heart and my "not so" daily use-case. 
You guys probably saw it already but if I'm online I don't have time for discords and reading backlogs, and if I have few spare minutes and I can fix issue for someone using shoko+naka, I would love to have the issue write down on github.

Oh, one more thing, If you could add information that Nakamori is rewritten in Python3 so some features we cut of to boost release time. If there are features that are missing that people would like to see back in code-base, github is the best place to do it.
