### ISSUE TITLE
X

### ISSUE THREAD

**Issue by Kristijan1001** [bigretromike/nakamori#514]
X

**Comment by Kristijan1001** [comment]
Ignore

**Comment by bigretromike** [comment]
This was fixed in shoko server by me :-) should work with daily build

**Comment by Kristijan1001** [comment]
> This was fixed in shoko server by me :-) should work with daily build

Thanks. So will need the nightly build for it ? I remembered I posted something similar awhile back. Then tested it and it seemed the tags showed up if you click info on a series in the default theme. I wanted it to be in the info section, but tried like 10 themes and none of them showed it. So I thought it Is theme fault so decided to remove post

**Comment by bigretromike** [comment]
Will resolve the crash definitly !.

Make screen shot and show me where you want and what you want. I will check it later and think out something if its useful ;)

**Comment by Kristijan1001** [comment]
> Will resolve the crash definitly !.
> 
> Make screen shot and show me where you want and what you want. I will check it later and think out something if its useful ;)

It would basically be somewhere here like example "Tags: Blah Blah etc.. "

![image](https://user-images.githubusercontent.com/24441639/171962940-4e4b928b-aa97-415e-95f5-734d23e6c3d0.png)

**Comment by bigretromike** [comment]
Without changing anything in skin I can only make it work like this (with ability to shorten for given length because long list will move plot out of view) - I think this will do - also its affected by show/hide function. I will push this later with other tweaks stay tune and it will be available soonish in repo.

![obraz](https://user-images.githubusercontent.com/6052025/172001554-74cf2fe2-ce56-471a-9209-03d1d9156c61.png)

**Comment by Kristijan1001** [comment]
> Without changing anything in skin I can only make it work like this (with ability to shorten for given length because long list will move plot out of view) - I think this will do - also its affected by show/hide function. I will push this later with other tweaks stay tune and it will be available soonish in repo.
> 
> ![obraz](https://user-images.githubusercontent.com/6052025/172001554-74cf2fe2-ce56-471a-9209-03d1d9156c61.png)

Thanks a lot I will check it out. For it pushing out of the screen not sure if we are referring to the same thing. But most skins have an option to scroll through the synopsis, so maybe that wouldn't be an issue ?

**Comment by Kristijan1001** [comment]
Just tested it. Works fine. On other skins it shows when pressing the info button. On it own when scrolling it only shows the synopsis at least from the skins I tested. I use artic horizon at the moment. It is good enough, before there was no way to see it either way. Thanks for the help.

**Comment by bigretromike** [comment]
@Kristijan1001 with official skin tags would show up when you hit 'I' or from context menu Information. 

Glad it helped you, I find it useful but sadly would like to see it a bit differently - but you are right, its skin issue.

**Comment by da3dsoul** [comment]
I've considered updating part of my skin. Sadly, with their texture format, it's a pita to version control

**Comment by bigretromike** [comment]
@da3dsoul if you do ping me, and I will readd it back to repo
