### ISSUE TITLE
Could not connect to repository

### ISSUE THREAD

**Issue by toprak** [bigretromike/nakamori#517]
I mean shoko is opened did everything according to ur guide but no good

**Comment by da3dsoul** [comment]
What version of Kodi? 20 probably won't work yet

**Comment by toprak** [comment]
@da3dsoul yes its 20.

**Comment by da3dsoul** [comment]
Try with 19, just to see if it can connect. I didn't see any issues with the repo

**Comment by bigretromike** [comment]
Also it should work with 20 too.

**Comment by bigretromike** [comment]
Are you using this file to install repo ? https://shokunin.monogatari.pl/repo/repository.nakamori.zip

**Comment by bigretromike** [comment]
Make sure the shoko is running (try accessing it tru webui) if its running then close Kodi, rerun Nakamori if nothing helps, thry 
Kodi -> Nakamori -> Settings -> Configuration Wizard and Login Wizard. 

I recall Kodi sometimes having issue with not saving settings until you exit kodi - but that was in 20-beta.

**Comment by da3dsoul** [comment]
Ah you got it working on Nexus? Nice. I see they changed a lot in the api for list item info

**Comment by bigretromike** [comment]
> Ah you got it working on Nexus? Nice. I see they changed a lot in the api for list item info
Yes, yes I did. Long time ago :-) But I know you use some fanky setup in kodi19.

@toprak any luck with wizards ?

**Comment by toprak** [comment]
@bigretromike yes, wizard worked well, thank you guys for help!
