### ISSUE TITLE
Last Github Version, Main Menu is viewed as "Addon" instead of "TVShow" or whatever it was before, which limits the Skin View Types you can have on some Skins.

### ISSUE THREAD

**Issue by Kristijan1001** [bigretromike/nakamori#520]
Basically in the newest one i can't change my view type to Posters because something changed and the main/home page is not viewed as content/series anymore. Any way to fix this ?

**Comment by bigretromike** [comment]
@Kristijan1001 I have idea what could be the source of this issue. 

@SteveMavic didn't your last touched view types?

**Comment by bigretromike** [comment]
https://github.com/bigretromike/nakamori/commit/b84550ddd8ecaf09fe461dadc56be3dc94eccb53#r136646289

**Comment by Kristijan1001** [comment]
> @Kristijan1001 I have idea what could be the source of this issue.
> 
> @SteveMavic didn't your last touched view types?

Nice ping me when it is fixed. For now i will stay on the older version.

**Comment by Kristijan1001** [comment]
Will this be fixed @bigretromike seems like a quick update.

**Comment by bigretromike** [comment]
> Will this be fixed @bigretromike seems like a quick update.

You are right. Sorry. was hoping @SteveMavic will handle that. I need to rebuild my IDE env.
Please ping me at next weekend If I wont deliver this fix.

**Comment by Kristijan1001** [comment]
> > Will this be fixed @bigretromike seems like a quick update.
> 
> You are right. Sorry. was hoping @SteveMavic will handle that. I need to rebuild my IDE env. Please ping me at next weekend If I wont deliver this fix.

Pinged :D

**Comment by bigretromike** [comment]
One more week and I will finish my work for few companies, and I can hope on naka-train ;-)

**Comment by bigretromike** [comment]
fixed with 4.1.4

**Comment by Kristijan1001** [comment]
Thank you ;D
