### ISSUE TITLE
Favorites not working, they don't get synced with Shoko. Also once added they show in Kodi Nakamori Favorites and can't be removed.

### ISSUE THREAD

**Issue by Kristijan1001** [bigretromike/nakamori#521]
So if you add a favorite in Kodi using the Nakamori menu , the favorite shows up in kodi but doesnt sync with Shoko. Also you are unable to unfavorite the show u favorited to get it removed from the kodi nakamori "Favorite" category.

**Comment by bigretromike** [comment]
favorites never synced with shoko it was always a build-in-micro-database that stored those, but It would be a good idea to sync them - will check if api has that.

**Comment by bigretromike** [comment]
fixed with 4.1.4
