### ISSUE TITLE
Kodi 16.1 RC2 - Search intermittently doesn't work for tags and alternate titles

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#70]
It always works for the Title that nakamori lists. For tags, I tested two easy ones: violence and comedy. I couldn't figure out what made it work or not work. Alternate titles sometimes works. I tried Boku dake ga Inai Machi and Erased. It worked about half and half (I have the romaji title as default and search the official title). I can pastebin or Dropbox logs after this. Let me know

**Comment by bigretromike** [comment]
Im happy that this was found :-) this way I know someone other than me use it ;-) 
Will investigate if this is a Kodi 16.1 problem or not - but will fix it :+1: 

Alot of people dont use search, I remamber that search was broken for few good weeks and nobody noticed. Thanks for issue!

**Comment by da3dsoul** [comment]
Yeah, I just started using Kodi and Nakamori last week, and the search feature is fantastic when it works. It's great for people who aren't as avid as a watcher as myself who use the library.
