### ISSUE TITLE
Kodi 16.1 RC2 - Group Filters Sorted by AniDB rating throw an error

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#74]
They also don't work. I didn't test other sorting. Name sorting works, obviously, else you'd have heard it by now.

**Comment by da3dsoul** [comment]
This one happens with JMM 3.4.6.4

**Comment by da3dsoul** [comment]
07:28:17 T:4336   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'xml.etree.ElementTree.ParseError'>
                                            Error Contents: no element found: line 1, column 0
                                            Traceback (most recent call last):
                                              File "C:\Users\da3ds\AppData\Roaming\Kodi\addons\plugin.video.nakamoriplugin-1.3.1\nakamori.py", line 666, in <module>
                                                buildTVShows(parameters)
                                              File "C:\Users\da3ds\AppData\Roaming\Kodi\addons\plugin.video.nakamoriplugin-1.3.1\nakamori.py", line 192, in buildTVShows
                                                e=tree.XML(getHtml(params['url'],''))
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\xml\etree\ElementTree.py", line 1301, in XML
                                                return parser.close()
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\xml\etree\ElementTree.py", line 1654, in close
                                                self._raiseerror(v)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
                                                raise err
                                            ParseError: no element found: line 1, column 0
                                            -->End of Python script error report<--
07:28:17 T:8568   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.nakamoriplugin/?mode=4&name=AniDB%20Highly%20Rated&url=http%3a%2f%2f127.0.0.1%3a8111%2fJMMServerKodi%2fGetMetadata%2f1%2f0%2f10
07:28:17 T:8568   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nakamoriplugin/?mode=4&name=AniDB%20Highly%20Rated&url=http%3a%2f%2f127.0.0.1%3a8111%2fJMMServerKodi%2fGetMetadata%2f1%2f0%2f10) failed

**Comment by bigretromike** [comment]
Could you write how do you change sorting ? because in Kodi you cannot pick AniDB rating sort :-)

**Comment by da3dsoul** [comment]
I didn't realize sorting was handled entirely in Kodi. The sorting of that group is set in JMM, with a filter of include everything with an AniDB rating >6.5

**Comment by bigretromike** [comment]
There are 2 kinds of sorting. One is sorting on list view inside kodi other is by creating "virtual" groups you define by Filter and sorting methods. 
So yeah, two kind of sorting, with exception that the second one can only be made via JMM Desktop :-)

**Comment by bigretromike** [comment]
Yeah. Looks like JMM Throw error with this one

**Comment by bigretromike** [comment]
Because it cut xml respond in half.
