### ISSUE TITLE
Ongoing Kodi Compatibility Issue

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#90]
This is not to report individual bugs. This is a checklist for new versions of Kodi that require no changes.

**Comment by da3dsoul** [comment]
As of now, this is fully compatible with 16.1 on Windows (10) and Android (6). 17 nightlies as if may 1 2016 on both as well.

**Comment by bigretromike** [comment]
- [ ] https://github.com/bigretromike/nakamoriplugin/issues/91
