### ISSUE TITLE
Wide Banners Not Being Used In Wide Displays

### ISSUE THREAD

**Issue by ElementalCrisis** [bigretromike/nakamori#92]
As you can see in the image below, Nakamori is just using a cropped version of the image it selected for the series.

![kodi_2016-05-05_03-54-22](https://cloud.githubusercontent.com/assets/9443295/15042021/54576b4c-1275-11e6-93bb-b06e4539b57e.png)

JMM does support Wide Banners and you can see that the series selected in Nakamori has wide banners available. 

![jmmdesktop_2016-05-05_03-54-53](https://cloud.githubusercontent.com/assets/9443295/15042033/6c7ad4c0-1275-11e6-9310-82d3bd373ba9.png)

The cropped ones should be used when the series does not have a wide banner available which you can see there are some in my collection that don't that are just blank. 

Skin: Eminence 2.0 - http://forum.kodi.tv/showthread.php?tid=237538

**Comment by bigretromike** [comment]
I see what you want. From the what I remember JMM send information about big art (poster) and thumb so yes, I see the potential for this also. I would also see this as &arg for JMM to not clutter the output data for people not using wide images. This will be done!

**Comment by da3dsoul** [comment]
I'm familiar with this as well. I posted it in a discussion on another issue. Lots of image and info issues with Kodi 17 it seems.

**Comment by da3dsoul** [comment]
One more series URL is not going to hurt. This should be provided by JMM

**Comment by ElementalCrisis** [comment]
An update on this, running JMM 3.6 and Nakamori 1.4.0 and now I have no wide banners at all. 

![kodi_2016-06-26_03-48-38](https://cloud.githubusercontent.com/assets/9443295/16361816/e0cb2524-3b50-11e6-97ad-9959f529e368.png)

**Comment by bigretromike** [comment]
3.6 dont give any more images than thumbs because new scheme etc..

**Comment by da3dsoul** [comment]
Fixed
