### ISSUE TITLE
Wrong Image Being Displayed For Series

### ISSUE THREAD

**Issue by ElementalCrisis** [bigretromike/nakamori#93]
For some reason, the image being displayed for the series Onegai Teacher is from the anime Beet The Vandel Slayer. While i do have this series it's currently not in my collection nor has it ever been added to the database I'm using. I'm also using a fresh copy of both JMM Server and JMM Desktop so no left over images or info. 

![kodi_2016-05-05_04-07-03](https://cloud.githubusercontent.com/assets/9443295/15042216/fa45d362-1276-11e6-9c11-97b56c19b0ce.png)

**Comment by bigretromike** [comment]
The empty image bug in JMM cause in Kodi using different images. Not sure if from url that it gets or from cache it use. 
Im more than 99,99% sure that you have this image in JMM Database the best would be to examine XML file that you ask JMM for.

**Comment by da3dsoul** [comment]
If you enable the log spam in the settings, it'll dump the entire XML

**Comment by ElementalCrisis** [comment]
BRM and I figured it out. 

The correct image was being shown in the XML but not in Kodi. For some unknown reason Kodi was pulling the incorrect image from it's thumbnail cache in \AppData\Roaming\Kodi\userdata\Thumbnails. Deleting all files and folder in there fixed the issue. 

![kodi_2016-05-05_04-57-05](https://cloud.githubusercontent.com/assets/9443295/15043116/a480dcee-127e-11e6-91eb-5ff908cba5a8.png)

**Comment by bigretromike** [comment]
Yeah that was one sick bug there. Still im not sure if this is more Kodi related or blank/corrupt JMM image bug related. But soon the JMM will be fix - by me (if no one will be faster)

**Comment by bigretromike** [comment]
@ElementalCrisis is this issue still there, or was it fixed after fixing blank image bug ?

**Comment by ElementalCrisis** [comment]
I only have three series in my collection for testing at the moment, I'll add around 40-50 more to see if I can reproduce this.

**Comment by ElementalCrisis** [comment]
Looks like this is no longer an issue, going to assume it's been fixed.
