### ISSUE TITLE
Wide Image Display Issues

### ISSUE THREAD

**Issue by ElementalCrisis** [bigretromike/nakamori#94]
I've noticed that some series simply won't display the wide image even when JMM has fanart for the series. It appears to be random as my small collection of 36 is having issues displaying the wide image for three series. 

Here are some examples. 

![kodi_2016-05-05_04-09-30](https://cloud.githubusercontent.com/assets/9443295/15042303/87476302-1277-11e6-8adb-08aa6f225ab7.png)
![kodi_2016-05-05_04-10-10](https://cloud.githubusercontent.com/assets/9443295/15042304/87497458-1277-11e6-8f01-48835160b8d1.png)
![kodi_2016-05-05_04-10-49](https://cloud.githubusercontent.com/assets/9443295/15042305/874b296a-1277-11e6-8bcd-1d5c4baa2eec.png)

**Comment by ElementalCrisis** [comment]
Did some research, each series has entries for empty fanart in JMM Desktop so it probably ended up selecting that "image" to use which is why they are not being shown.

**Comment by ElementalCrisis** [comment]
Another similar issue, seems for the series Break Blade Nakamori is using the poster instead of the fanart. 

![kodi_2016-05-05_05-05-45](https://cloud.githubusercontent.com/assets/9443295/15043157/0dc13c94-127f-11e6-8a81-5ebd308bd046.png)

https://cloud.githubusercontent.com/assets/9443295/15042033/6c7ad4c0-1275-11e6-9310-82d3bd373ba9.png

**Comment by bigretromike** [comment]
@ElementalCrisis could you confirm this is still unfixed ?

**Comment by ElementalCrisis** [comment]
I'll need to do some more testing but wide banners do not show up properly. 

Nakamori 1.4.0 and JMM 3.6
![kodi_2016-06-24_05-27-32](https://cloud.githubusercontent.com/assets/9443295/16337711/603fb09e-39cc-11e6-83c2-723b0de45e10.png)

**Comment by ElementalCrisis** [comment]
Ignore my comment above, forgot there was a separate issue for that bug. 

Back on topic, will continue testing on a bigger collection but it displayed everything correctly. Looks like it's been fixed.
